### ISSUE TITLE
Issues in Calculate accuracy of disaggregation

### ISSUE THREAD

**Issue by deploy15** [nilmtk/nilmtk#204]
After several hours to figure out this issue, i tried to post it for our contribution

![disaggregation accuracy](https://cloud.githubusercontent.com/assets/6690768/5059007/85ead164-6d0b-11e4-9b74-36130766c713.JPG)

![diaggregation accuracy1](https://cloud.githubusercontent.com/assets/6690768/5059016/bad7bbd0-6d0b-11e4-8367-c6544db6a012.JPG)

What could be the problem

**Comment by t7reyeslua** [comment]
Hi!....I am trying to run nilmtk but I am having some issues when I reach: f1 = f1_score(disag_elec,elec).
I have tried following both the Demo of NILMTK v0.2 for BuildSys 2014 and the original tutorial in the user manual. I am using the REDD data for both. I have already pulled the latest version from git of both nilmtk and nilm_metadata but still the same result. What could be the problem?

===================================================
/home/t7/anaconda/lib/python2.7/site-packages/sklearn/metrics/metrics.py:1771: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/elecmeter.py:786: PendingDeprecationWarning: object.__format__ with a non-empty format string is deprecated
  .format(self.building(), self.instance(), stat_name))
Traceback (most recent call last):

  File "<ipython-input-5-9b5a04a7cbc9>", line 1, in <module>
    f1_score(disag_elec, elec)

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/metrics.py", line 222, in f1_score
    'when_on'):

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/electric.py", line 785, in align_two_meters
    sections = master.good_sections()

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/elecmeter.py", line 635, in good_sections
    nodes, results_obj, loader_kwargs)

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/elecmeter.py", line 685, in _get_stat_from_cache_or_compute
    key_for_cached_stat = self.key_for_cached_stat(results_obj.name)

  File "/home/t7/Dropbox/Documents/TUDelft/Thesis/Software/nilmtk/nilmtk/elecmeter.py", line 786, in key_for_cached_stat
    .format(self.building(), self.instance(), stat_name))

ValueError: Unknown format code 'd' for object of type 'str'

**Comment by JackKelly** [comment]
@t7reyeslua I've started [a new issue](https://github.com/nilmtk/nilmtk/issues/353) for your bug (as I don't think it's related to the bug discussed above).
