### ISSUE TITLE
Clearing cache in the IAWE dataset.

### ISSUE THREAD

**Issue by RishiBaijal** [nilmtk/nilmtk#328]
Usage:
```
elec.clear_cache()
```

Stack trace:

```
Clearing cache...done.
Removed building1/elec/cache/meter1/
Removed building1/elec/cache/meter2/
Removed building1/elec/cache/meter3/
Removed building1/elec/cache/meter4/
Removed building1/elec/cache/meter5/
ERROR:root:HDF5 error back trace

  File "H5Gstab.c", line 386, in H5G__stab_remove
    unable to remove entry
  File "H5B.c", line 1676, in H5B_remove
    unable to remove entry from B-tree
  File "H5B.c", line 1402, in H5B_remove_helper
    key not found in leaf node
  File "H5Gnode.c", line 872, in H5G_node_remove
    unable to decrement object link count
  File "H5O.c", line 1623, in H5O_link
    can't delete object from file
  File "H5O.c", line 2212, in H5O_delete
    can't delete object from file
  File "H5O.c", line 2261, in H5O_delete_oh
    unable to delete file space for object header message
  File "H5Omessage.c", line 2111, in H5O_delete_mesg
    unable to delete file space for object header message
  File "H5Ostab.c", line 288, in H5O_stab_delete
    unable to free symbol table
  File "H5Gstab.c", line 497, in H5G__stab_delete
    unable to delete symbol table B-tree
  File "H5B.c", line 1748, in H5B_delete
    can't remove B-tree node
  File "H5Gnode.c", line 949, in H5G_node_remove
    unable to decrement object link count
  File "H5O.c", line 1623, in H5O_link
    can't delete object from file
  File "H5O.c", line 2212, in H5O_delete
    can't delete object from file
  File "H5O.c", line 2261, in H5O_delete_oh
    unable to delete file space for object header message
  File "H5Omessage.c", line 2111, in H5O_delete_mesg
    unable to delete file space for object header message
  File "H5Ostab.c", line 288, in H5O_stab_delete
    unable to free symbol table
  File "H5Gstab.c", line 497, in H5G__stab_delete
    unable to delete symbol table B-tree
  File "H5B.c", line 1748, in H5B_delete
    can't remove B-tree node
  File "H5Gnode.c", line 949, in H5G_node_remove
    unable to decrement object link count
  File "H5O.c", line 1623, in H5O_link
    can't delete object from file
  File "H5O.c", line 2212, in H5O_delete
    can't delete object from file
  File "H5O.c", line 2261, in H5O_delete_oh
    unable to delete file space for object header message
  File "H5Omessage.c", line 2111, in H5O_delete_mesg
    unable to delete file space for object header message
  File "H5Olayout.c", line 560, in H5O_layout_delete
    unable to free raw data
  File "H5Dchunk.c", line 4272, in H5D__chunk_delete
    unable to delete chunk index
  File "H5Dbtree.c", line 1184, in H5D__btree_idx_delete
    unable to delete chunk B-tree
  File "H5B.c", line 1727, in H5B_delete
    unable to load B-tree node
  File "H5AC.c", line 1323, in H5AC_protect
    H5C_protect() failed.
  File "H5C.c", line 3574, in H5C_protect
    can't load entry
  File "H5C.c", line 7954, in H5C_load_entry
    unable to load entry
  File "H5Bcache.c", line 143, in H5B__load
    wrong B-tree signature

End of HDF5 error back trace

problems deleting the node ``/building1/elec/cache/meter6``
Traceback (most recent call last):
  File "test.py", line 115, in test_single_meter_group
    print ("Timeframe: ", elec.get_timeframe())
  File "/Users/rishi/Documents/Master_folder/IIITD/5th_semester/Independent_Project/nilmtk/nilmtk/metergroup.py", line 1557, in clear_cache
    meter.clear_cache()
  File "/Users/rishi/Documents/Master_folder/IIITD/5th_semester/Independent_Project/nilmtk/nilmtk/elecmeter.py", line 792, in clear_cache
    self.store.remove(key_for_cache)
  File "/Users/rishi/Documents/Master_folder/IIITD/5th_semester/Independent_Project/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)
  File "/Users/rishi/Documents/Master_folder/IIITD/5th_semester/Independent_Project/nilmtk/nilmtk/datastore/hdfdatastore.py", line 171, in remove
    self.store.remove(key)
  File "/Users/rishi/anaconda/lib/python2.7/site-packages/pandas-0.14.1_345_ge226bac-py2.7-macosx-10.5-x86_64.egg/pandas/io/pytables.py", line 856, in remove
    s._f_remove(recursive=True)
  File "/Users/rishi/anaconda/lib/python2.7/site-packages/tables/node.py", line 561, in _f_remove
    self._g_remove(recursive, force)
  File "/Users/rishi/anaconda/lib/python2.7/site-packages/tables/group.py", line 936, in _g_remove
    super(Group, self)._g_remove(recursive, force)
  File "/Users/rishi/anaconda/lib/python2.7/site-packages/tables/node.py", line 541, in _g_remove
    self._g_delete(parent)
  File "hdf5extension.pyx", line 905, in tables.hdf5extension.Node._g_delete (tables/hdf5extension.c:8577)
HDF5ExtError: HDF5 error back trace

  File "H5Gstab.c", line 386, in H5G__stab_remove
    unable to remove entry
  File "H5B.c", line 1676, in H5B_remove
    unable to remove entry from B-tree
  File "H5B.c", line 1402, in H5B_remove_helper
    key not found in leaf node
  File "H5Gnode.c", line 872, in H5G_node_remove
    unable to decrement object link count
  File "H5O.c", line 1623, in H5O_link
    can't delete object from file
  File "H5O.c", line 2212, in H5O_delete
    can't delete object from file
  File "H5O.c", line 2261, in H5O_delete_oh
    unable to delete file space for object header message
  File "H5Omessage.c", line 2111, in H5O_delete_mesg
    unable to delete file space for object header message
  File "H5Ostab.c", line 288, in H5O_stab_delete
    unable to free symbol table
  File "H5Gstab.c", line 497, in H5G__stab_delete
    unable to delete symbol table B-tree
  File "H5B.c", line 1748, in H5B_delete
    can't remove B-tree node
  File "H5Gnode.c", line 949, in H5G_node_remove
    unable to decrement object link count
  File "H5O.c", line 1623, in H5O_link
    can't delete object from file
  File "H5O.c", line 2212, in H5O_delete
    can't delete object from file
  File "H5O.c", line 2261, in H5O_delete_oh
    unable to delete file space for object header message
  File "H5Omessage.c", line 2111, in H5O_delete_mesg
    unable to delete file space for object header message
  File "H5Ostab.c", line 288, in H5O_stab_delete
    unable to free symbol table
  File "H5Gstab.c", line 497, in H5G__stab_delete
    unable to delete symbol table B-tree
  File "H5B.c", line 1748, in H5B_delete
    can't remove B-tree node
  File "H5Gnode.c", line 949, in H5G_node_remove
    unable to decrement object link count
  File "H5O.c", line 1623, in H5O_link
    can't delete object from file
  File "H5O.c", line 2212, in H5O_delete
    can't delete object from file
  File "H5O.c", line 2261, in H5O_delete_oh
    unable to delete file space for object header message
  File "H5Omessage.c", line 2111, in H5O_delete_mesg
    unable to delete file space for object header message
  File "H5Olayout.c", line 560, in H5O_layout_delete
    unable to free raw data
  File "H5Dchunk.c", line 4272, in H5D__chunk_delete
    unable to delete chunk index
  File "H5Dbtree.c", line 1184, in H5D__btree_idx_delete
    unable to delete chunk B-tree
  File "H5B.c", line 1727, in H5B_delete
    unable to load B-tree node
  File "H5AC.c", line 1323, in H5AC_protect
    H5C_protect() failed.
  File "H5C.c", line 3574, in H5C_protect
    can't load entry
  File "H5C.c", line 7954, in H5C_load_entry
    unable to load entry
  File "H5Bcache.c", line 143, in H5B__load
    wrong B-tree signature

End of HDF5 error back trace

problems deleting the node ``/building1/elec/cache/meter6``

```

This is similar to a problem that I had faced in the COMBED dataset. Apparently the meter given in this stack trace also happens to be defective. That issue can be found here: https://github.com/nilmtk/nilmtk/issues/326

**Comment by nipunreddevil** [comment]
Works fine for me. Closing.

**Comment by JackKelly** [comment]
there is something a little odd happening here that we should (some time) get to the bottom of.  I've opened a new issue: #402
