### ISSUE TITLE
'No object named /building2/elec/meter7 in the file'

### ISSUE THREAD

**Issue by RishiBaijal** [nilmtk/nilmtk#332]
Usage:
```
elec.get_timeframe()
```
Stack trace:
```
ERROR:root:'No object named /building2/elec/meter7 in the file'
Traceback (most recent call last):
  File "test.py", line 125, in test_single_meter_group
    print ("Timeframe: ", elec.get_timeframe())
  File "/Users/rishi/Documents/Master_folder/IIITD/5th_semester/Independent_Project/nilmtk/nilmtk/metergroup.py", line 1335, in get_timeframe
    elif meter.get_timeframe().empty:
  File "/Users/rishi/Documents/Master_folder/IIITD/5th_semester/Independent_Project/nilmtk/nilmtk/elecmeter.py", line 91, in get_timeframe
    return self.store.get_timeframe(key=self.key)
  File "/Users/rishi/Documents/Master_folder/IIITD/5th_semester/Independent_Project/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)
  File "/Users/rishi/Documents/Master_folder/IIITD/5th_semester/Independent_Project/nilmtk/nilmtk/datastore/hdfdatastore.py", line 219, in get_timeframe
    data_start_date = self.store.select(key, [0]).index[0]
  File "/Users/rishi/anaconda/lib/python2.7/site-packages/pandas-0.14.1_345_ge226bac-py2.7-macosx-10.5-x86_64.egg/pandas/io/pytables.py", line 658, in select
    raise KeyError('No object named %s in the file' % key)
KeyError: 'No object named /building2/elec/meter7 in the file'
```

Coincidentally, this happens only with the COMBED dataset and not the IAWE dataset. There might be something wrong with the meter given in the stack trace.

**Comment by JackKelly** [comment]
Please provide more details ;)

**Comment by nipunreddevil** [comment]
@RishiBaijal : Debugging this should be trivial.
Can you check if `/building2/elec/meter7` exists in the data set H5 or not. I can also do this. Want you to learn!

**Comment by RishiBaijal** [comment]
Yeah. `/building2/elec/meter7` does not exist. However, clearly the function tries to find it. Why does it go up to meter7 when it should stop at meter6 and continue processing? Is this a problem with the h5 file or is it a problem with the function? (Note that the h5 file that I am working on was the latest one that I had taken from the website. For good measure, I will download the h5 file and try it again.)
