### ISSUE TITLE
HDFDataStore appending error

### ISSUE THREAD

**Issue by MingjunZhong** [nilmtk/nilmtk#350]
I am using HDFDataStore to store results, but it quite often has errors like this:

``` python
File "/home/mzhong/nilmtk/nilmtk/nilmtk/disaggregate/afhmm_sac.py", line 615, in disaggregate
    output_datastore.append(meter,pd.DataFrame(predictions[meter]))

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/docinherit.py", line 36, in __get__
    return self.get_with_inst(obj, cls)

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/docinherit.py", line 44, in get_with_inst
    @wraps(self.mthd, assigned=('__name__','__module__'))

TypeError: 'NoneType' object is not callable
```

That is when I append DataFrame or other values, it had this error. Any ideas what's wrong?
Thanks!!!

**Comment by JackKelly** [comment]
Is that the full stack trace?  If not, please can you copy and paste the full stack trace into this issue queue?  Thanks loads.

**Comment by MingjunZhong** [comment]
It seem when I close the Spyder window and reopen it and then run, it will be working.


Appliance: '/building2/elec/meter3:('sockets', 1)'
Traceback (most recent call last):

  File "<ipython-input-21-3481056bed14>", line 1, in <module>
    debugfile('/home/mzhong/2015-ideal/nilmtk-afhmmsac/demo_nilmtk.py', wdir='/home/mzhong/2015-ideal/nilmtk-afhmmsac')

  File "/home/mzhong/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 600, in debugfile
    debugger.run("runfile(%r, args=%r, wdir=%r)" % (filename, args, wdir))

  File "/home/mzhong/anaconda/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals

  File "<string>", line 1, in <module>

  File "/home/mzhong/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)

  File "/home/mzhong/2015-ideal/nilmtk-afhmmsac/demo_nilmtk.py", line 50, in <module>
    varianceSac = Var_Sac[i],varianceModelNoise = Var_Noise[j])

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/disaggregate/afhmm_sac.py", line 615, in disaggregate
    output_datastore.append(meter,pd.DataFrame(predictions[meter]))

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/docinherit.py", line 36, in __get__
    return self.get_with_inst(obj, cls)

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/docinherit.py", line 44, in get_with_inst
    @wraps(self.mthd, assigned=('__name__','__module__'))

TypeError: 'NoneType' object is not callable

**Comment by JackKelly** [comment]
is `output_datastore` definitely instantiated as a list by line 615 in `afhmm_sac.py`?

**Comment by PMeira** [comment]
Closing due to inactivity. If I were to guess, I'd say the HDF file is still open somewhere else.
