### ISSUE TITLE
F1_score problem

### ISSUE THREAD

**Issue by skoczmanx** [nilmtk/nilmtk#371]
Hello, 
after run this code, I have ValueError: Shape of passed values is (2, 0), indices imply (2, 1263).
 Can you take a look and tell what I'm doing wrong ? 

```python
from nilmtk.disaggregate import CombinatorialOptimisation, FHMM
from nilmtk import DataSet, HDFDataStore
from nilmtk.utils import print_dict
from nilmtk.metrics import f1_score
import matplotlib.pyplot as plt
import os

class CoDisag:
    def __init__(self,train_elec, test_elec, output = None):
        self.train_elec = train_elec #elec.select_top_k(first_top_num)
        self.test_elec = test_elec #elec.mains()
        if output is None:
            self.output = 'out'
        else:
            self.output = output

    def train(self):
        self.co = CombinatorialOptimisation()
        #self.co = FHMM()
        self.co.train(self.train_elec)

    def disag(self, appliance2compare):
        self.output_file = os.path.join(self.output, 'iawe_disag_' + appliance2compare +  '.h5')
        print self.output_file
        output = HDFDataStore(self.output_file, 'w')
        self.co.disaggregate(self.test_elec, output)
        output.store.keys()
        output.close()
        self.appliance2compare = appliance2compare

    def getDisagApplianceActiveEnergy(self):
        disag = DataSet(self.output_file)

        disag_elec = disag.buildings[1].elec
        f1 = f1_score(disag_elec, self.train_elec)
        f1.index = disag_elec.get_labels(f1.index)
        f1.plot(kind='barh', figsize=(10,6))
        plt.ylabel('appliance');
        plt.xlabel('f-score');

        disag.store.close()
        return disag_elec[self.appliance2compare].total_energy().to_dict()['active']


first_top_num = 10
appliance2compare = 'television'

train_set = DataSet('data/iawe.h5')
train_set.set_window(start=None, end='2013-08-05')
train_elec = train_set.buildings[1].elec

test_set = DataSet('data/iawe.h5')
test_set.set_window(start='2013-08-05', end=None)
test_elec = test_set.buildings[1].elec
test_elec_mains = test_elec.mains()

coDisag = CoDisag(train_elec, test_elec_mains, 'out')
coDisag.train()
coDisag.disag(appliance2compare)

disagEnergy = coDisag.getDisagApplianceActiveEnergy()
```

```
Traceback (most recent call last):
  File "D:/Bil/AKA/NilMtkTest/CoDisag.py", line 65, in <module>
    disagEnergy = coDisag.getDisagApplianceActiveEnergy()
  File "D:/Bil/AKA/NilMtkTest/CoDisag.py", line 38, in getDisagApplianceActiveEnergy
    f1 = f1_score(disag_elec, self.train_elec)
  File "c:\nilmtk-master\nilmtk\metrics.py", line 222, in f1_score
    'when_on'):
  File "c:\nilmtk-master\nilmtk\electric.py", line 799, in align_two_meters
    yield pd.DataFrame({'master': master_chunk, 'slave': slave_chunk})
  File "C:\Anaconda\lib\site-packages\pandas\core\frame.py", line 208, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "C:\Anaconda\lib\site-packages\pandas\core\frame.py", line 336, in _init_dict
    dtype=dtype)
  File "C:\Anaconda\lib\site-packages\pandas\core\frame.py", line 4627, in _arrays_to_mgr
    return create_block_manager_from_arrays(arrays, arr_names, axes)
  File "C:\Anaconda\lib\site-packages\pandas\core\internals.py", line 3544, in create_block_manager_from_arrays
    construction_error(len(arrays), arrays[0].shape, axes, e)
  File "C:\Anaconda\lib\site-packages\pandas\core\internals.py", line 3513, in construction_error
    raise e
ValueError: Shape of passed values is (2, 0), indices imply (2, 1263)
Closing remaining open files:data/iawe.h5...donedata/iawe.h5...doneout\iawe_disag_television.h5...done
```

**Comment by nipunreddevil** [comment]
I think you are getting this error because `disag_elec` does not contain any data. `test_elec` contains data for 1263 minutes on '2013-08-05'.

Can you do `disag_elec.plot()`?

NB: I've edited your issue to make code more readable. May I please request you to follow the markup as I've done. Makes much easier to read the code. Also, it would be great if you can modify your example to be a minimal working example which illustrates the problem.

For instance, I ran the following code (emulating your setup) and it works perfectly for me.

```python

from nilmtk import *
import matplotlib.pyplot as pl
train = DataSet("/Users/nipunbatra/Copy/Dataset/iawe.h5")
train.set_window(start=None, end='2013-08-05')
test = DataSet("/Users/nipunbatra/Copy/Dataset/iawe.h5")
test.set_window(start='2013-08-05', end=None)

from nilmtk.disaggregate import CombinatorialOptimisation
co = CombinatorialOptimisation()
co.train(train.buildings[1].elec)
disag_filename ='co-disag.h5'
output = HDFDataStore(disag_filename, 'w')
co.disaggregate(test.buildings[1].elec.mains(), output)
output.close()
disag = DataSet(disag_filename)
disag_elec = disag.buildings[building_number].elec
disag_elec = disag.buildings[1].elec
disag_elec.plot()
plt.savefig("demo.png")
```

![demo](https://cloud.githubusercontent.com/assets/60985/6900501/f309ae54-d6d4-11e4-98f6-899f75de02ca.png)

**Comment by nipunreddevil** [comment]
I ran the code for computing F1-score and I am able to reproduce this error.

```python

In [36]: from nilmtk.metrics import f1_score

In [37]: f1 = f1_score(disag_elec, elec)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-37-adbd2cdc7f12> in <module>()
----> 1 f1 = f1_score(disag_elec, elec)

/Users/nipunbatra/git/nilmtk/nilmtk/metrics.pyc in f1_score(predictions, ground_truth)
    220         for aligned_states_chunk in align_two_meters(pred_meter, 
    221                                                      ground_truth_meter,
--> 222                                                      'when_on'):
    223             aligned_states_chunk.dropna(inplace=True)
    224             aligned_states_chunk = aligned_states_chunk.astype(int)

/Users/nipunbatra/git/nilmtk/nilmtk/electric.pyc in align_two_meters(master, slave, func)
    777         master_chunk = master_chunk.resample(period_alias)
    778 
--> 779         yield pd.DataFrame({'master': master_chunk, 'slave': slave_chunk})
    780 

/Users/nipunbatra/anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc in __init__(self, data, index, columns, dtype, copy)
    206                                  dtype=dtype, copy=copy)
    207         elif isinstance(data, dict):
--> 208             mgr = self._init_dict(data, index, columns, dtype=dtype)
    209         elif isinstance(data, ma.MaskedArray):
    210             import numpy.ma.mrecords as mrecords

/Users/nipunbatra/anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc in _init_dict(self, data, index, columns, dtype)
    334 
    335         return _arrays_to_mgr(arrays, data_names, index, columns,
--> 336                               dtype=dtype)
    337 
    338     def _init_ndarray(self, values, index, columns, dtype=None,

/Users/nipunbatra/anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc in _arrays_to_mgr(arrays, arr_names, index, columns, dtype)
   4625     axes = [_ensure_index(columns), _ensure_index(index)]
   4626 
-> 4627     return create_block_manager_from_arrays(arrays, arr_names, axes)
   4628 
   4629 

/Users/nipunbatra/anaconda/lib/python2.7/site-packages/pandas/core/internals.pyc in create_block_manager_from_arrays(arrays, names, axes)
   3542         return mgr
   3543     except (ValueError) as e:
-> 3544         construction_error(len(arrays), arrays[0].shape, axes, e)
   3545 
   3546 

/Users/nipunbatra/anaconda/lib/python2.7/site-packages/pandas/core/internals.pyc in construction_error(tot_items, block_shape, axes, e)
   3511     implied = tuple(map(int, [len(ax) for ax in axes]))
   3512     if passed == implied and e is not None:
-> 3513         raise e
   3514     raise ValueError("Shape of passed values is {0}, indices imply {1}".format(
   3515         passed,implied))

ValueError: Shape of passed values is (2, 0), indices imply (2, 1263)
```

**Comment by nipunreddevil** [comment]
Any idea @JackKelly.
I get the same error with other metric functions. Something going wrong in `align_two_meters` function.

**Comment by JackKelly** [comment]
My hunch would be that, at the end of the `align_two_meters` function, either `slave_chunk` or `master_chunk` is empty.  This does look like a case that we need to handle in our code...

**Comment by JackKelly** [comment]
If someone could write a unittest which demonstrates this bug then that would be a great start.  I've made a start in [test_metrics.py](https://github.com/nilmtk/nilmtk/blob/master/nilmtk/tests/test_metrics.py) but it appears that we don't yet have any test data in `nilmtk/data` that has sufficient metadata to allow it to pass through the entire disag pipeline :(  (if you uncomment the code in `test_f1()` you'll see what I mean).  Unfortunately I have very limited time to work on NILMTK at the moment so will need someone else to write a unittest if at all possible.

**Comment by skoczmanx** [comment]
Can you share some datasets from tutorials ?

**Comment by JackKelly** [comment]
@skoczmanx you're welcome to my dataset, UK-DALE: http://www.doc.ic.ac.uk/~dk3810/data/   I probably shouldn't share other peoples' data without their permission.

**Comment by skoczmanx** [comment]
Thank you very much

**Comment by evellynsc** [comment]
I got this ValueError when computing F1-score for house 4 of REDD dataset, using CO algorithm for disaggregation.

**Comment by JackKelly** [comment]
I've just pushed some code which should fix the ValueError.  Please re-open this issue if necessary ;)

**Comment by evellynsc** [comment]
Thanks, @JackKelly!! It's working now! ;D
