### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by skoczmanx** [nilmtk/nilmtk#375]
After run this code:

```python
__author__ = 'm.skoczek'

from nilmtk import *
import matplotlib.pyplot as plt

B_NUM = 1

train = DataSet("data/ukdale.h5")
train.set_window(start=None, end='2014-07-15')
test = DataSet("data/ukdale.h5")
test.set_window(start='2014-07-15', end=None)

from nilmtk.disaggregate import CombinatorialOptimisation
co = CombinatorialOptimisation()
co.train(train.buildings[B_NUM].elec)
disag_filename ='co-disag.h5'
output = HDFDataStore(disag_filename, 'w')
co.disaggregate(test.buildings[B_NUM].elec.mains(), output)
output.close()
disag = DataSet(disag_filename)
disag_elec = disag.buildings[B_NUM].elec
disag_elec.plot()
plt.savefig("demo.png")

verif = DataSet("data/ukdale.h5")
verif.set_window(start='2014-07-05', end=None)
verif_elec = verif.buildings[B_NUM].elec
verif_elec.plot()
plt.savefig("demo_o.png")

import pprint as pp
pp.pprint(verif_elec['fridge'].total_energy())
pp.pprint(disag_elec['fridge'].total_energy())

pp.pprint(disag_elec.proportion_of_energy_submetered())

from nilmtk.metrics import f1_score
f1 = f1_score(disag_elec, test.buildings[B_NUM].elec)
pp.pprint(f1)
```

I receive this error
```
Done training!
Traceback (most recent call last):
  File "D:/Bil/AKA/NilMtkTest/forum_ukdale.py", line 18, in <module>
    co.disaggregate(test.buildings[B_NUM].elec.mains(), output)
  File "c:\nilmtk\nilmtk\disaggregate\combinatorial_optimisation.py", line 105, in disaggregate
    state_combinations = cartesian(centroids)
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 525, in cartesian
    cartesian(arrays[1:], out=out[0:m, 1:])
  File "C:\Anaconda\lib\site-packages\sklearn\utils\extmath.py", line 523, in cartesian
    out[:, 0] = np.repeat(arrays[0], m)
  File "C:\Anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 393, in repeat
    return repeat(repeats, axis)
ValueError: negative dimensions are not allowed
```

This error appears only on ukdale dataset.

**Comment by JackKelly** [comment]
Thanks for the bug report.  I'm looking into this bug right now.

One quick comment: your code trains a model on all 53 channels in house 1 of UK-DALE.  This is almost certainly a bad idea!  Indeed, on my machine I can't replicate your problem because I get a memory error:

```python
MemoryError                               Traceback (most recent call last)
<ipython-input-2-146fc165e436> in <module>()
     14 disag_filename ='co-disag.h5'
     15 output = HDFDataStore(disag_filename, 'w')
---> 16 co.disaggregate(test.buildings[B_NUM].elec.mains(), output)
     17 output.close()

/home/dk3810/workspace/python/nilmtk/nilmtk/disaggregate/combinatorial_optimisation.py in disaggregate(self, mains, output_datastore, **load_kwargs)
    103         # Get centroids
    104         centroids = [model['states'] for model in self.model]
--> 105         state_combinations = cartesian(centroids)
    106         # state_combinations is a 2D array
    107         # each column is a chan

/usr/local/lib/python2.7/dist-packages/sklearn/utils/extmath.pyc in cartesian(arrays, out)
    518     n = np.prod([x.size for x in arrays])
    519     if out is None:
--> 520         out = np.empty([n, len(arrays)], dtype=dtype)
    521 
    522     m = n // arrays[0].size

MemoryError: 
```

My suggestion would be to select the top-K appliances per house.  For house 1 in UK-DALE, that's the fridge freezer, washer dryer, HTPC, dish washer and kettle.  In general, you can select the top k using code like this:

```python
submeters = elec.meters_directly_downstream_of_mains()
grouped = submeters.groupby('type') # optional step to group all lights together, for example
top_k = grouped.select_top_k(group_remainder=False)
```

I'll keep digging into this error but I suspect it's caused by trying to learn an intractably large model ;)

**Comment by JackKelly** [comment]
Yes, so, when I train a model on only the top 5 appliances, the code runs fine.  This code is what I used:

```python
from nilmtk import *
import matplotlib.pyplot as plt
from nilmtk.disaggregate import CombinatorialOptimisation

B_NUM = 1

train = DataSet("/data/mine/vadeec/merged/ukdale.h5")
train.set_window(start=None, end='2014-07-15')
test = DataSet("/data/mine/vadeec/merged/ukdale.h5")
test.set_window(start='2014-07-15', end=None)

co = CombinatorialOptimisation()
elec = train.buildings[B_NUM].elec.meters_directly_downstream_of_mains()
top_k = elec.select_top_k(group_remainder=False)
co.train(top_k)

disag_filename ='co-disag.h5'
output = HDFDataStore(disag_filename, 'w')
co.disaggregate(test.buildings[B_NUM].elec.mains(), output)
output.close()
```
