### ISSUE TITLE
MemoryError for FHMM

### ISSUE THREAD

**Issue by dongchen1999** [nilmtk/nilmtk#377]
```python
Traceback (most recent call last):
  File "change_data.py", line 68, in <module>
    fhmm.train(elec)
  File "/home/dong/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 242, in train
    learnt_model_combined = create_combined_hmm(new_learnt_models)
  File "/home/dong/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 132, in create_combined_hmm
    A_combined = compute_A_fhmm(list_A)
  File "/home/dong/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 88, in compute_A_fhmm
    result = np.kron(result, list_A[i + 1])
  File "/home/dong/anaconda/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 782, in kron
    result = concatenate(result, axis=axis)
MemoryError
```

**Comment by JackKelly** [comment]
In general, when submitting a bug report, please make sure you supply all the details listed in [our guide for submitting a bug report](https://github.com/nilmtk/nilmtk/#submitting-a-bug-report).  In particular, please supply a minimal code example to allow us to replicate your bug, and please format your comment so it is easy to read (I have edited your comment to show you how).

However, my hunch would be that the issue here is that perhaps you are trying to build an FHMM model with too many appliances. i.e. the model is intractably large.  Please see [this comment](https://github.com/nilmtk/nilmtk/issues/375#issuecomment-91564334) for more details (and please, in future, search to issue queue before posting.  A search for `MemoryError` would have found the comment I just linked to).
