### ISSUE TITLE
ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by dongchen1999** [nilmtk/nilmtk#378]
```python
Traceback (most recent call last):
  File "do_fhmm.py", line 76, in <module>
    fhmm.disaggregate(top_5_train_elec, output1)
  File "/home/dong/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 374, in disaggregate
    predictions = self.disaggregate_chunk(chunk)
  File "/home/dong/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 265, in disaggregate_chunk
    learnt_states_array.append(self.model.predict(temp))
  File "/home/dong/anaconda/lib/python2.7/site-packages/hmmlearn/base.py", line 283, in predict
    _, state_sequence = self.decode(obs, algorithm)
  File "/home/dong/anaconda/lib/python2.7/site-packages/hmmlearn/base.py", line 266, in decode
    logprob, state_sequence = decoder[algorithm](obs)
  File "/home/dong/anaconda/lib/python2.7/site-packages/hmmlearn/base.py", line 199, in _decode_viterbi
    framelogprob = self._compute_log_likelihood(obs)
  File "/home/dong/anaconda/lib/python2.7/site-packages/hmmlearn/hmm.py", line 185, in _compute_log_likelihood
    obs, self._means_, self._covars_, self._covariance_type)
  File "/home/dong/anaconda/lib/python2.7/site-packages/sklearn/mixture/gmm.py", line 59, in log_multivariate_normal_density
    X, means, covars)
  File "/home/dong/anaconda/lib/python2.7/site-packages/sklearn/mixture/gmm.py", line 605, in _log_multivariate_normal_density_full
    cv_sol = linalg.solve_triangular(cv_chol, (X - mu).T, lower=True).T
  File "/home/dong/anaconda/lib/python2.7/site-packages/scipy/linalg/basic.py", line 154, in solve_triangular
    a1, b1 = map(np.asarray_chkfinite,(a,b))
  File "/home/dong/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 613, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

**Comment by JackKelly** [comment]
Thanks for your bug report.  A few points:

1. please supply a minimal code example to allow us to replicate your bug (see [our guide for submitting a bug report](https://github.com/nilmtk/nilmtk/#submitting-a-bug-report))
2. please check to see if #374  is the same as your issue.  If so then please close this current issue and use issue #374 instead.
