### ISSUE TITLE
HDF5 error while disaggregating iAWE dataset using CO

### ISSUE THREAD

**Issue by akshay-sn** [nilmtk/nilmtk#393]
Hello,

I tried to train and disaggregate iAWE dataset using CO. During disaggregation call when the start and end time periods is greater than couple of days, there is a HDF5 error.

Previous issue #216 was very similar to current error. However, the status of the issue is closed, but the error still appears. Please let me know, how it can be resolved to disaggregate for longer time periods.

Bests,
Akshay

```python
Traceback (most recent call last):

  File "<ipython-input-1-3f9c06e06651>", line 1, in <module>
    runfile('/Users/akshay/Dropbox_50/Dropbox/Thesis_Antonio/Code/NILM-Loc/tests/co_loc_test_iawe.py', wdir='/Users/akshay/Dropbox_50/Dropbox/Thesis_Antonio/Code/NILM-Loc/tests')

  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)

  File "/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/sitecustomize.py", line 78, in execfile
    builtins.execfile(filename, *where)

  File "/Users/akshay/Dropbox_50/Dropbox/Thesis_Antonio/Code/NILM-Loc/tests/co_loc_test_iawe.py", line 72, in <module>
    plain_co, vampire_power_in_original = utils.disaggregate_original_co(settings.h5_iawe, h5_disag_iawe_original,dataset_start_date_disag, dataset_end_date_disag)

  File "/Users/akshay/Dropbox_50/Dropbox/Thesis_Antonio/Code/NILM-Loc/misc/utils.py", line 55, in disaggregate_original_co
    plain_co.disaggregate(elec.mains(), output_plain_co)

  File "/Users/akshay/Desktop/NILMTK/nilmtk/nilmtk/disaggregate/combinatorial_optimisation.py", line 264, in disaggregate
    output_datastore.save_metadata(building_path, building_metadata)

  File "/Users/akshay/Desktop/NILMTK/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)

  File "/Users/akshay/Desktop/NILMTK/nilmtk/nilmtk/datastore/hdfdatastore.py", line 188, in save_metadata
    node._v_attrs.metadata = metadata

  File "/Users/akshay/anaconda/lib/python2.7/site-packages/tables/attributeset.py", line 455, in __setattr__
    self._g__setattr(name, value)

  File "/Users/akshay/anaconda/lib/python2.7/site-packages/tables/attributeset.py", line 397, in _g__setattr
    self._g_setattr(self._v_node, name, stvalue)

  File "hdf5extension.pyx", line 704, in tables.hdf5extension.AttributeSet._g_setattr (tables/hdf5extension.c:6695)

HDF5ExtError: HDF5 error back trace

  File "H5A.c", line 259, in H5Acreate2
    unable to create attribute
  File "H5Aint.c", line 275, in H5A_create
    unable to create attribute in object header
  File "H5Oattribute.c", line 347, in H5O_attr_create
    unable to create new attribute in header
  File "H5Omessage.c", line 224, in H5O_msg_append_real
    unable to create new message
  File "H5Omessage.c", line 1945, in H5O_msg_alloc
    unable to allocate space for message
  File "H5Oalloc.c", line 1142, in H5O_alloc
    object header message is too large

End of HDF5 error back trace

Can't set attribute 'metadata' in node:
 /building1 (Group) ''.
```

**Comment by nipunreddevil** [comment]
Hi Akshay,
It is possible for you to show us the complete code?

**Comment by akshay-sn** [comment]
Hi Nipun,

please find the code!
---

from nilmtk.dataset_converters import download_dataport
from nilmtk.dataset_converters import convert_redd
from nilmtk import DataSet
import nilmtk
from nilmtk.disaggregate import CombinatorialOptimisation
from nilmtk.metrics import fraction_energy_assigned_correctly
from nilmtk import HDFDataStore
import numpy as np

source = '/Users/akshay/Dropbox_50/Dropbox/Thesis_Antonio/Datasets/iAWE/Electricity'
outputhdf5 = '/Users/akshay/Desktop/NILMTK/Testing/iawe.h5'
disagout = '/Users/akshay/Desktop/NILMTK/Testing/iawe-disag-original.h5'

print("Converting...")
#convert_redd(source, outputhdf5)
iawe = DataSet(outputhdf5)

print("Training...")
#redd.set_window(start=None, end='2011-05-01 00:00:00')
iawe.set_window(start='2013-05-24 00:00:00', end='2013-08-21 00:00:00')

elec = iawe.buildings[1].elec
co = CombinatorialOptimisation()
co.train(elec)


print("Disagreggating...")

iawe.set_window(start='2013-05-24 00:00:00', end='2013-07-20 00:00:00')
mains = elec.mains()
output = HDFDataStore(disagout, 'w')
co.disaggregate(mains, output)
output.close()

print("Metrics...")
disag = DataSet(disagout)
disag_elec = disag.buildings[1].elec


f= fraction_energy_assigned_correctly(disag_elec,elec)

**Comment by nipunreddevil** [comment]
I was able to replicate the bug.

```python

In [1]: from nilmtk import DataSet

In [2]: import nilmtk

In [3]: from nilmtk.disaggregate import CombinatorialOptimisation

In [4]: from nilmtk.metrics import fraction_energy_assigned_correctly

In [5]: from nilmtk import HDFDataStore

In [6]: import numpy as np

In [7]: outputhdf5 = '/Users/nipunbatra/Copy/Dataset/iawe.h5'

In [8]: iawe = DataSet(outputhdf5)

In [9]: iawe.set_window(start='2013-05-24 00:00:00', end='2013-08-21 00:00:00')

In [10]: elec = iawe.buildings[1].elec

In [11]: co = CombinatorialOptimisation()

In [12]: co.train(elec)

In [13]: iawe.set_window(start='2013-05-24 00:00:00', end='2013-07-20 00:00:00')

In [14]: mains = elec.mains()

In [15]: disagout = 'iawe-disag.h5'

In [16]: output = HDFDataStore(disagout, 'w')

In [17]: co.disaggregate(mains, output)

HDF5ExtError                              Traceback (most recent call last)
<ipython-input-17-a2892f84e6bf> in <module>()
----> 1 co.disaggregate(mains, output)

/Users/nipunbatra/git/nilmtk/nilmtk/disaggregate/combinatorial_optimisation.pyc in disaggregate(self, mains, output_datastore, **load_kwargs)
    262         }
    263 
--> 264         output_datastore.save_metadata(building_path, building_metadata)
    265 
    266     # TODO: fix export and import!

/Users/nipunbatra/git/nilmtk/nilmtk/docinherit.pyc in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__','__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

/Users/nipunbatra/git/nilmtk/nilmtk/datastore/hdfdatastore.pyc in save_metadata(self, key, metadata)
    186             node = self.store.get_node(key)
    187 
--> 188         node._v_attrs.metadata = metadata
    189         self.store.flush()
    190 

/Users/nipunbatra/anaconda/lib/python2.7/site-packages/tables/attributeset.pyc in __setattr__(self, name, value)
    453 
    454         # Set the attribute.
--> 455         self._g__setattr(name, value)
    456 
    457         # Log new attribute addition.

/Users/nipunbatra/anaconda/lib/python2.7/site-packages/tables/attributeset.pyc in _g__setattr(self, name, value)
    395             value = stvalue[()]
    396 
--> 397         self._g_setattr(self._v_node, name, stvalue)
    398 
    399         # New attribute or value. Introduce it into the local

hdf5extension.pyx in tables.hdf5extension.AttributeSet._g_setattr (tables/hdf5extension.c:6695)()

HDF5ExtError: HDF5 error back trace

  File "H5A.c", line 256, in H5Acreate2
    unable to create attribute
  File "H5A.c", line 505, in H5A_create
    unable to create attribute in object header
  File "H5Oattribute.c", line 347, in H5O_attr_create
    unable to create new attribute in header
  File "H5Omessage.c", line 224, in H5O_msg_append_real
    unable to create new message
  File "H5Omessage.c", line 1945, in H5O_msg_alloc
    unable to allocate space for message
  File "H5Oalloc.c", line 1142, in H5O_alloc
    object header message is too large

End of HDF5 error back trace

Can't set attribute 'metadata' in node:
 /building1 (Group) ''.
```

At this point, I  checked the contents of the disaggregated HDF5 produced.

```python

In [18]: import pandas as pd

In [19]: st = pd.Da
pd.DataFrame      pd.DateOffset     pd.DatetimeIndex  

In [19]: st = pd.HDFStore(disagout)

In [20]: st
Out[20]: 
<class 'pandas.io.pytables.HDFStore'>
File path: iawe-disag.h5
/building1/elec/meter1             frame_table  (typ->appendable,nrows->74551,ncols->1,indexers->[index])
/building1/elec/meter10            frame_table  (typ->appendable,nrows->74551,ncols->1,indexers->[index])
/building1/elec/meter11            frame_table  (typ->appendable,nrows->74551,ncols->1,indexers->[index])
/building1/elec/meter12            frame_table  (typ->appendable,nrows->74551,ncols->1,indexers->[index])
/building1/elec/meter3             frame_table  (typ->appendable,nrows->74551,ncols->1,indexers->[index])
/building1/elec/meter4             frame_table  (typ->appendable,nrows->74551,ncols->1,indexers->[index])
/building1/elec/meter5             frame_table  (typ->appendable,nrows->74551,ncols->1,indexers->[index])
/building1/elec/meter6             frame_table  (typ->appendable,nrows->74551,ncols->1,indexers->[index])
/building1/elec/meter7             frame_table  (typ->appendable,nrows->74551,ncols->1,indexers->[index])
/building1/elec/meter8             frame_table  (typ->appendable,nrows->74551,ncols->1,indexers->[index])
/building1/elec/meter9             frame_table  (typ->appendable,nrows->74551,ncols->1,indexers->[index])

In [21]: st['/building1/elec/meter12']
Out[21]: 
                           power
                          active
2013-05-24 05:30:00+05:30      0
2013-05-24 05:31:00+05:30      0
2013-05-24 05:32:00+05:30      0
2013-05-24 05:33:00+05:30      0
2013-05-24 05:34:00+05:30    228
2013-05-24 05:35:00+05:30      0
2013-05-24 05:36:00+05:30    228
2013-05-24 05:37:00+05:30      0
2013-05-24 05:38:00+05:30      0
2013-05-24 05:39:00+05:30    228
2013-05-24 05:40:00+05:30      0
2013-05-24 05:41:00+05:30      0
2013-05-24 05:42:00+05:30      0
2013-05-24 05:43:00+05:30      0
2013-05-24 05:44:00+05:30      0
2013-05-24 05:45:00+05:30      0
2013-05-24 05:46:00+05:30      0
2013-05-24 05:47:00+05:30      0
2013-05-24 05:48:00+05:30      0
2013-05-24 05:49:00+05:30      0
2013-05-24 05:50:00+05:30      0
2013-05-24 05:51:00+05:30      0
2013-05-24 05:52:00+05:30      0
2013-05-24 05:53:00+05:30    228
2013-05-24 05:54:00+05:30      0
2013-05-24 05:55:00+05:30      0
2013-05-24 05:56:00+05:30      0
2013-05-24 05:57:00+05:30      0
2013-05-24 05:58:00+05:30      0
2013-05-24 05:59:00+05:30      0
...                          ...
2013-07-19 23:30:00+05:30      0
2013-07-19 23:31:00+05:30    228
2013-07-19 23:32:00+05:30      0
2013-07-19 23:33:00+05:30      0
2013-07-19 23:34:00+05:30    228
2013-07-19 23:35:00+05:30      0
2013-07-19 23:36:00+05:30      0
2013-07-19 23:37:00+05:30    228
2013-07-19 23:38:00+05:30      0
2013-07-19 23:39:00+05:30    228
2013-07-19 23:40:00+05:30      0
2013-07-19 23:41:00+05:30      0
2013-07-19 23:42:00+05:30      0
2013-07-19 23:43:00+05:30      0
2013-07-19 23:44:00+05:30      0
2013-07-19 23:45:00+05:30    228
2013-07-19 23:46:00+05:30      0
2013-07-19 23:47:00+05:30    228
2013-07-19 23:48:00+05:30      0
2013-07-19 23:49:00+05:30      0
2013-07-19 23:50:00+05:30      0
2013-07-19 23:51:00+05:30    228
2013-07-19 23:52:00+05:30    228
2013-07-19 23:53:00+05:30    228
2013-07-19 23:54:00+05:30      0
2013-07-19 23:55:00+05:30      0
2013-07-19 23:56:00+05:30    228
2013-07-19 23:57:00+05:30    228
2013-07-19 23:58:00+05:30    228
2013-07-19 23:59:00+05:30      0

[74551 rows x 1 columns]

```

Then, I tried reducing the window and then disaggregate.

```python

In [22]: iawe.set_window(start='2013-05-24 00:00:00', end='2013-06-20 00:00:00')

In [23]: co.disaggregate(mains, output)
```

This ran to completion.

@akshay-sn : You are right that this seems to be related to #216. 

@JackKelly : Do you know how to approach this?

**Comment by JackKelly** [comment]
I'll look into this now (sorry for the slow reply; I was away last week and this week has been busy)...

**Comment by JackKelly** [comment]
making progress.  At line 264 in `combinatorial_optimisation.py`, we do this:

```python
        output_datastore.save_metadata(building_path, building_metadata)
```

I think the problem is that `building_metadata['elec_meters'][<instance>]['statistics']['good_sections']` contains some large lists of good sections (too large to fit into the metadata).  But, as discussed in #216, we're no longer keeping `good_sections` cache in the metadata.  So I'll do some more digging and make some changes...

**Comment by JackKelly** [comment]
OK, the fix was simple: we no longer store `good_sections` in the disag metadata.  This fixes the issue (on my install, at least!)  Please re-open if this issue isn't fixed for you.
