### ISSUE TITLE
Scoring FHMM prediction

### ISSUE THREAD

**Issue by knoxm** [nilmtk/nilmtk#449]
I’m a bit confused as to how the predicted data is scored (and perhaps more importantly loaded). It seems that whenever I try to use 2 scoring metrics back-to-back (e.g. score F1 and rms for a given prediction), python bugs out with 'section_start not found’. I get a similar error when I try to score the results by simply loading the prediction, which was previously stored in an h5 file (as opposed to running the FHMM again). I’ve copied the code below, and the error message below that. Note: the error message is for the case that I load previous results. The error when I try to run 2 scoring methods (after training the FHMM and running on the test set) has the same style of error but occurs at the "rms = rms_error_power(disag_elec, elec)" line.

```python
from __future__ import print_function, division
from nilmtk import DataSet, HDFDataStore
from os.path import join
import matplotlib.pyplot as plt
import mysys
from matplotlib import rcParams
import math
from nilmtk.metrics import f1_score # metrics is actually different; need to look at this
from nilmtk.metrics import rms_error_power
from nilmtk.metrics import mean_normalized_error_power
from nilmtk.disaggregate import fhmm_exact # OK, only different in what is printed to screen (and this is diagonal covariance matrix)

rcParams.update({'figure.autolayout': True})
axis_font = {'size':'20'}
title_font = {'size':'22'}
in_data_dir = 'inputPath'
out_data_dir = 'outputPath'
infoStr = '_60s_trainFirstHalf_diagCov'
titleStr = 'FHMM results for 60 seconds'
mysys.makepath(out_data_dir)

## this file is modified from tests_on_large_datasets/redd_house3_f1_score.py 
for iHouse in range(1): #changed this to to 1 (from 6); now only works on house 1
    building_number = iHouse + 1
    print('working on building number', building_number)
    disag_filename = join(out_data_dir, 'disag-fhmm' + str(building_number) + infoStr + '.h5')
    train = DataSet(join(in_data_dir, 'redd.h5'))
    test = DataSet(join(in_data_dir, 'redd.h5'))

    ## find middle data point in entire dataset, to split training and testing
    elec = train.buildings[building_number].elec
    mains = elec.mains()
    df_all = mains.power_series_all_data() #df_all has a bunch of NaNs
    df_all_noNan = df_all.dropna()
    a = df_all_noNan.keys()
    middleTime = a[int(math.floor(a.size/2))]
    middleTimeStr = "%d-%02d-%02d %02d:%02d:%02d" % (middleTime.year, middleTime.month, middleTime.day, middleTime.hour, middleTime.minute, middleTime.second)
    print(middleTimeStr) 

    train.set_window(end=middleTimeStr)
    test.set_window(start=middleTimeStr)

    train_elec = train.buildings[building_number].elec
    test_elec = test.buildings[building_number].elec

    top_train_elec = train_elec.submeters().select_top_k(k=5)

    # don't train it and run it; instead, load previous training
    #fhmm = fhmm_exact.FHMM() #mk change this later  to default
    #fhmm.train(top_train_elec, sample_period=60, resample=True)
    #output = HDFDataStore(disag_filename, 'w')
    #fhmm.disaggregate(test_elec.mains(), output, sample_period=60, resample=True)
    #output.close()

    ### f1score fhmm
    disag = DataSet(disag_filename) #load FHMM prediction
    disag_elec = disag.buildings[building_number].elec

    f1 = f1_score(disag_elec, test_elec)
    f1.index = disag_elec.get_labels(f1.index)
    f1.plot(kind='barh')
    plt.ylabel('appliance', **axis_font);
    plt.xlabel('f-score', **axis_font);
    plt.title(titleStr, **title_font);
    plt.savefig(join(out_data_dir, 'check-fhmm' + str(building_number) + infoStr + '_f1.png'))

    #rms = rms_error_power(disag_elec, elec)
    #rms.index = disag_elec.get_labels(rms.index)
    #rms.plot(kind='barh')
    #plt.ylabel('appliance', **axis_font);
    #plt.xlabel('rms', **axis_font);
    #plt.title(titleStr, **title_font);
    #plt.savefig(join(out_data_dir, 'check-fhmm' + str(building_number) + infoStr + '_rms.png'))

    #mne = mean_normalized_error_power(disag_elec, elec)
    #mne.index = disag_elec.get_labels(mne.index)
    #mne.plot(kind='barh')
    #plt.ylabel('appliance', **axis_font);
    #plt.xlabel('mne', **axis_font);
    #plt.title(titleStr, **title_font);
    #plt.savefig(join(out_data_dir, 'fhmm' + str(building_number) + infoStr + '_mne.png'))

    disag.store.close()
    print("Finishing building " + str(building_number))
```

Error message:
```python
Traceback (most recent call last):
  File "mtk_scoreFromLoadedResults.py", line 74, in <module>
    f1 = f1_score(disag_elec, test_elec)
  File "/home/lab/Research/generalPackages/nilm/otherNilm/nilmtk/nilmtk/metrics.py", line 225, in f1_score
    for aligned_states_chunk in aligned_meters:
  File "/home/lab/Research/generalPackages/nilm/otherNilm/nilmtk/nilmtk/electric.py", line 828, in align_two_meters
    sections = master.good_sections()
  File "/home/lab/Research/generalPackages/nilm/otherNilm/nilmtk/nilmtk/elecmeter.py", line 632, in good_sections
    nodes, results_obj, loader_kwargs)        
  File "/home/lab/Research/generalPackages/nilm/otherNilm/nilmtk/nilmtk/elecmeter.py", line 686, in _get_stat_from_cache_or_compute
    results_obj.import_from_cache(cached_stat, sections)
  File "/home/lab/Research/generalPackages/nilm/otherNilm/nilmtk/nilmtk/stats/goodsectionsresults.py", line 118, in import_from_cache
    section_start = tz_localize_naive(row['section_start'], tz)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/series.py", line 551, in __getitem__
    result = self.index.get_value(self, key)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/index.py", line 1713, in get_value
    return s[key]
  File "/usr/local/lib/python2.7/dist-packages/pandas/tseries/base.py", line 100, in __getitem__
    val = getitem(key)
ValueError: field named section_start not found
Closing remaining open files:/home/lab/Research/Output/ttmp/nilm/data/redd.h5...done/home/lab/Research/Output/ttmp/nilm/data/redd.h5...done/home/lab/Research/Output/ttmp/nilm/2015.10.14.mtk.run.fhmm.on.redd/traintest/disag-fhmm1_60s_trainFirstHalf_diagCov.h5...done
```

**Comment by knoxm** [comment]
I forgot to include the version information.

```python
show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-65-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.0
nose: 1.3.7
pip: 1.5.4
setuptools: 3.3
Cython: 0.23.3
numpy: 1.8.2
scipy: 0.13.3
statsmodels: None
IPython: 4.0.0
sphinx: None
patsy: None
dateutil: 1.5
pytz: 2012c
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.3.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
httplib2: 0.8
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
None

Date: 2015-10-26 17:17:41.548402
Platform: Linux-3.13.0-65-generic-x86_64-with-Ubuntu-14.04-trusty
System version: 2.7
nilmtk version: 0.2.0.dev-
nilm_metadata version: 0.2.0.dev-4834d3c
numpy version: 1.8.2
matplotlib version: 1.3.1
pandas version: 0.17.0
sklearn version: 0.16.1
hmmlearn version: 0.1.1
```

**Comment by nipunreddevil** [comment]
I'm on this issue now and will update when I make progress.

**Comment by nipunreddevil** [comment]
I wasn't able to reproduce the bug. Here is the output when I tried running your code: https://github.com/nilmtk/nilmtk/blob/master/notebooks/issues/449.ipynb

I wonder if the issue is due to interpreter retaining variables (like store) and doing so in an inconsistent state. Maybe, if you restart your interpreter and rerun all your code, it'll be fine?

**Comment by knoxm** [comment]
I just looked at the code I posted and I forgot to uncomment the rms error computation. When you uncomment these lines (in addition to running the f1 lines), do you get an error? I was getting the error when I tried to run 2 scoring methods back to back or loading in the results file (instead of running the trained algorithm).

```python
    rms = rms_error_power(disag_elec, elec)
    rms.index = disag_elec.get_labels(rms.index)
    rms.plot(kind='barh')
    plt.ylabel('appliance', **axis_font);
    plt.xlabel('rms', **axis_font);
    plt.title(titleStr, **title_font);
    plt.savefig(join(out_data_dir, 'check-fhmm' + str(building_number) + infoStr + '_rms.png'))
```

I agree that it seems to be a storing/opening file and loading issue. 

Also, I'm running the files from the command line. I'm not sure if this makes a difference. I would assume not.

**Comment by nipunreddevil** [comment]
I think the easiest way to avoid such errors is to open a new Python terminal and run the code from there. New terminal will help avoid H5 store open/close issues.

**Comment by nipunbatra** [comment]
@knoxm : did you get this to work?

**Comment by knoxm** [comment]
I was able to score using multiple metrics if I reran the code multiple times. I was just hoping that since the information was stored, I wouldn't have to retrain/retest multiple times.
