### ISSUE TITLE
Issues with pandas when loading data

### ISSUE THREAD

**Issue by jingkungao** [nilmtk/nilmtk#456]
I am new to nilmtk and not sure if I am doing it correctly but I came across this issue when I was trying to load ukdale.h5 dataset to pandas.

I followed the same procedure as is shown in  [IPython Notebook](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/loading_data_into_memory.ipynb).

```
>>> from nilmtk import DataSet
>>> ukdale = DataSet('../ukdale.h5')
>>> elec = ukdale.buildings[1].elec
>>> light = elec['light']
>>> df=light.load().next()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/PythonPackages/neuralnilm/src/nilmtk-master/nilmtk/datastore/hdfdatastore.py", line 123, in load
    start=chunk_start_i, stop=chunk_end_i)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/pytables.py", line 682, in select
    return it.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/pytables.py", line 1365, in get_result
    results = self.func(self.start, self.stop, where)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/pytables.py", line 675, in func
    columns=columns, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/pytables.py", line 4031, in read
    index_ = Index(index, name=getattr(index, 'name', None))
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/index.py", line 126, in __new__
    result = DatetimeIndex(data, copy=copy, name=name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/util/decorators.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/tseries/index.py", line 345, in __new__
    ambiguous=ambiguous)
  File "pandas/tslib.pyx", line 3753, in pandas.tslib.tz_localize_to_utc (pandas/tslib.c:64516)
pytz.exceptions.AmbiguousTimeError: Cannot infer dst time from Timestamp('2013-10-27 01:00:04'), try using the 'ambiguous' argument
```
The verions of nilmtk and pandas:
```
>>> nilmtk.__version__
'0.2.0.dev-bfcc88f'
>>> >>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-51-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.0
nose: 1.3.7
pip: 1.5.4
setuptools: 18.5
Cython: 0.23.4
numpy: 1.10.1
scipy: 0.16.1
statsmodels: None
IPython: 1.2.1
sphinx: 1.3.1
patsy: None
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.5.0
openpyxl: 2.3.0
xlrd: 0.9.2
xlwt: 0.7.5
xlsxwriter: None
lxml: 3.3.3
bs4: 4.2.1
html5lib: 0.999
httplib2: 0.8
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
```

Also,  I noticed I got error when running nosetests;
```
..F.....................................F.
======================================================================
FAIL: test_process_chunk (nilmtk.stats.tests.test_locategoodsections.TestLocateGoodSections)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/PythonPackages/nilmtk/nilmtk/stats/tests/test_locategoodsections.py", line 77, in test_process_chunk
    self.assertEqual(results[0].timedelta.total_seconds(), 30)
AssertionError: 30.000000000000004 != 30

======================================================================
FAIL: test_time_delta (nilmtk.tests.test_timeframe.TestTimeFrame)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/PythonPackages/nilmtk/nilmtk/tests/test_timeframe.py", line 31, in test_time_delta
    self.assertEqual(tf.timedelta.total_seconds(), 60*60*24*366)
AssertionError: 31622400.000000004 != 31622400

----------------------------------------------------------------------
Ran 42 tests in 12.700s

FAILED (failures=2)
Closing remaining open files:/opt/PythonPackages/nilmtk/data/energy.h5...done
```
This one is a rounding issue and I was able to resolve it by changing assertEqual to assertAlmostEqual. I don't think this one is related to AmbiguousTimeError, but it maybe useful to modify the test case.

Appreciate it if any one can look into this. Thanks in advance!

**Comment by JackKelly** [comment]
I have just replicated this issue using Pandas 0.17.

Before I upgraded from Pandas 0.16.2 to 0.17, this bug didn't exist.  So this bug is definitely something to do with NILMTK not playing nicely with Pandas 0.17.  I'll investigate now...

**Comment by JackKelly** [comment]
This bug might be related to this Pandas bug: https://github.com/pydata/pandas/issues/11619

**Comment by JackKelly** [comment]
This is definitely related to daylight saving.  If you set the window to exclude any DST changes then it loads fine:

```python
from nilmtk import DataSet
ukdale = DataSet('/data/mine/vadeec/merged/ukdale.h5')
ukdale.set_window("2014-05-01", "2014-10-01")
elec = ukdale.buildings[1].elec
light = elec['light']
df = light.load().next()
```

**Comment by JackKelly** [comment]
Yup, this definitely appears to be a bug in Pandas 0.17.  I have submitted [a new Pandas bug report](https://github.com/pydata/pandas/issues/11624).

@jingkungao In the mean time, you could either constrain your analyses to a time period with no DST changes (using `DataSet.set_window`) or you could downgrade to Pandas 0.16.2 until this bug is fixed.

**Comment by JackKelly** [comment]
@jreback (from Pandas) did an amazing job of fixing this Pandas bug within minutes of my bug report :)

@jingkungao try installing the latest version of Pandas from git.  This should fix the issue.  e.g. do something like this:

```bash
pip uninstall pandas
pip install -e git+https://github.com/pydata/pandas.git@91407ffd5f6d497949239b2ab956368dec2ac32b#egg=pandas
```

I'll close this bug report for now and add a note to the installation instructions...

**Comment by jingkungao** [comment]
@JackKelly Thanks, Jack! Amazing work. The neuralnilm is working smoothly now! Really appreciate all your efforts!

**Comment by JackKelly** [comment]
Just for anyone else reading this issue: Pandas 0.17.1 was released on the 20th November and includes a fix for this bug.  So you can just do `pip install --upgrade pandas` to get Pandas 0.17.1 instead of having to install Pandas from `git`
