### ISSUE TITLE
Travis build failure: ValueError: Found array with dim 3. Estimator expected <= 2.

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#460]
https://travis-ci.org/nilmtk/nilmtk/builds/93143067

```
$ nosetests --with-coverage
/home/travis/build/nilmtk/nilmtk/nilmtk/node.py:2: ImportWarning: Not importing directory '/home/travis/build/nilmtk/nilmtk/nilm_metadata': missing __init__.py
  from nilm_metadata import recursively_update_dict
.......................E...................
======================================================================
ERROR: test_fhmm_correctness (nilmtk.tests.test_fhmm.TestFHMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/nilmtk/nilmtk/nilmtk/tests/test_fhmm.py", line 26, in test_fhmm_correctness
    fhmm.train(elec)
  File "/home/travis/build/nilmtk/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 223, in train
    learnt_model[meter].fit([X])
  File "/home/travis/miniconda/lib/python2.7/site-packages/hmmlearn/base.py", line 410, in fit
    X = check_array(X)
  File "/home/travis/miniconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 396, in check_array
    % (array.ndim, estimator_name))
ValueError: Found array with dim 3. Estimator expected <= 2.
```

I can't replicate this problem on my local machine yet.  I suspect I need to upgrade hmmlearn... will look into it...

**Comment by JackKelly** [comment]
ah, yes, travis is installing hmmlearn 0.2.0 but we decided a while ago that we'd support hmmlearn 0.1.1.  Let me see if I can get travis to respect our `requirements.txt` file...
