### ISSUE TITLE
hmmlearn test errors within (nilmtk-env) using new install instructions

### ISSUE THREAD

**Issue by SydBal** [nilmtk/nilmtk#467]
I'm not sure if I should be posting this here or @hmmlearn, but since I'm mostly interested in using Nilmtk (once I can convert my data into hdf5 format), and I'm using the new conda environment install, I thought this would be the best place.

nosetests grants one error in regards to hmmlearn:
```
$ nosetests 
.......................E...................
======================================================================
ERROR: test_fhmm_correctness (nilmtk.tests.test_fhmm.TestFHMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dxm/nilmtk/nilmtk/tests/test_fhmm.py", line 26, in test_fhmm_correctness
    fhmm.train(elec)
  File "/home/dxm/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 223, in train
    learnt_model[meter].fit([X])
  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 420, in fit
    X = check_array(X)
  File "/home/dxm/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/sklearn/utils/validation.py", line 396, in check_array
    % (array.ndim, estimator_name))
ValueError: Found array with dim 3. Estimator expected <= 2.
-------------------- >> begin captured stdout << ---------------------
Training model for submeter 'ElecMeter(instance=2, building=1, dataset=None, appliances=[])'

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 43 tests in 10.088s

FAILED (errors=1) 
```

Moving into the hmmlearn directory, and running its own test script I get this output:

```
$ py.test --doctest-modules hmmlearn
============================= test session starts ==============================
platform linux2 -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.2
rootdir: /home/dxm/nilmtk/hmmlearn, inifile: 
collected 0 items / 14 errors 

==================================== ERRORS ====================================
______________________ ERROR collecting hmmlearn/base.py _______________________
hmmlearn/base.py:7: in <module>
    import numpy as np
E   ImportError: No module named numpy
_______________________ ERROR collecting hmmlearn/hmm.py _______________________
hmmlearn/hmm.py:13: in <module>
    import numpy as np
E   ImportError: No module named numpy
______________________ ERROR collecting hmmlearn/utils.py ______________________
hmmlearn/utils.py:1: in <module>
    import numpy as np
E   ImportError: No module named numpy
_________________ ERROR collecting hmmlearn/tests/__init__.py __________________
hmmlearn/tests/__init__.py:1: in <module>
    import numpy as np
E   ImportError: No module named numpy
_________________ ERROR collecting hmmlearn/tests/test_base.py _________________
/usr/lib/python2.7/dist-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
hmmlearn/tests/__init__.py:1: in <module>
    import numpy as np
E   ImportError: No module named numpy
_________________ ERROR collecting hmmlearn/tests/test_base.py _________________
/usr/lib/python2.7/dist-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
hmmlearn/tests/__init__.py:1: in <module>
    import numpy as np
E   ImportError: No module named numpy
_____________ ERROR collecting hmmlearn/tests/test_gaussian_hmm.py _____________
/usr/lib/python2.7/dist-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
hmmlearn/tests/__init__.py:1: in <module>
    import numpy as np
E   ImportError: No module named numpy
_____________ ERROR collecting hmmlearn/tests/test_gaussian_hmm.py _____________
/usr/lib/python2.7/dist-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
hmmlearn/tests/__init__.py:1: in <module>
    import numpy as np
E   ImportError: No module named numpy
_______________ ERROR collecting hmmlearn/tests/test_gmm_hmm.py ________________
/usr/lib/python2.7/dist-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
hmmlearn/tests/__init__.py:1: in <module>
    import numpy as np
E   ImportError: No module named numpy
_______________ ERROR collecting hmmlearn/tests/test_gmm_hmm.py ________________
/usr/lib/python2.7/dist-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
hmmlearn/tests/__init__.py:1: in <module>
    import numpy as np
E   ImportError: No module named numpy
___________ ERROR collecting hmmlearn/tests/test_multinomial_hmm.py ____________
/usr/lib/python2.7/dist-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
hmmlearn/tests/__init__.py:1: in <module>
    import numpy as np
E   ImportError: No module named numpy
___________ ERROR collecting hmmlearn/tests/test_multinomial_hmm.py ____________
/usr/lib/python2.7/dist-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
hmmlearn/tests/__init__.py:1: in <module>
    import numpy as np
E   ImportError: No module named numpy
________________ ERROR collecting hmmlearn/tests/test_utils.py _________________
/usr/lib/python2.7/dist-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
hmmlearn/tests/__init__.py:1: in <module>
    import numpy as np
E   ImportError: No module named numpy
________________ ERROR collecting hmmlearn/tests/test_utils.py _________________
/usr/lib/python2.7/dist-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
hmmlearn/tests/__init__.py:1: in <module>
    import numpy as np
E   ImportError: No module named numpy
=========================== 14 error in 0.20 seconds ===========================
```

This is obviously a problem with hmmlearn importing python.

Has anyone ran into the same issue, or know how to fix this?
Thanks in advance.

**Comment by JackKelly** [comment]
Hi.  Thanks for posting.  Well... hmmlearn is complaining that it can't find `numpy`.  Are you sure numpy is installed?  (what happens if you start `ipython` and type `import numpy`?)  Also, do you know which version of hmmlearn has been installed on your system?  At present, NILMTK only works with hmmlearn 0.1.1 (*not* 0.2)

**Comment by SydBal** [comment]
Thanks for reminding me about the 0.1.1 dependency, I believe that fixed the numpy problem. Now, I am getting this error from testing nilmtk:

```
$ la
.coveragerc      .git            nilmtk           setup.py
data             .gitignore      nilmtk.egg-info  tests_on_large_datasets
docs             hmmlearn-0.1.1  notebooks        .travis.yml
environment.yml  LICENSE         README.md
(nilmtk-env)dxm@AnyColorYouLike:~/nilmtk$ nosetests
.......................E...................
======================================================================
ERROR: test_fhmm_correctness (nilmtk.tests.test_fhmm.TestFHMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dxm/nilmtk/nilmtk/tests/test_fhmm.py", line 26, in test_fhmm_correctness
    fhmm.train(elec)
  File "/home/dxm/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 223, in train
    learnt_model[meter].fit([X])
  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 420, in fit
    X = check_array(X)
  File "/home/dxm/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/sklearn/utils/validation.py", line 396, in check_array
    % (array.ndim, estimator_name))
ValueError: Found array with dim 3. Estimator expected <= 2.
-------------------- >> begin captured stdout << ---------------------
Training model for submeter 'ElecMeter(instance=2, building=1, dataset=None, appliances=[])'

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 43 tests in 9.950s

FAILED (errors=1)
Closing remaining open files:/home/dxm/nilmtk/data/energy.h5...done
```

I'm reinstalling on a new computer, and I believe I have run into this error before. I'll continue to look for a solution.

Thanks again for the help.
For the record I'm using Ubuntu 15.10

**Comment by JackKelly** [comment]
The error that you are getting (i.e. `ValueError: Found array with dim 3. Estimator expected <= 2`) is the same error that we've seen in the past when HMMLearn 0.2 is installed (e.g. see issues #426 and #460).  Are you sure HMMLearn 0.1.1 is installed on your system?  Try running this at your Linux shell: `python -c 'import hmmlearn;print hmmlearn.__version__'` and tell us which version number it prints out, please.

**Comment by nipunbatra** [comment]
For me, the output is the following:
```python
In [19]: import hmmlearn

In [20]: hmmlearn.__version__
Out[20]: '0.1a'
```

**Comment by SydBal** [comment]
Ok, it seems I must have been setting it up outside the virtual environment, or something. After setting up hmmlearn 0.1.1,  nosetests runs without errors.

```
~/nilmtk$ python -c 'import hmmlearn;print hmmlearn.__version__'
0.1.1
```
