### ISSUE TITLE
Failing to import DataSet

### ISSUE THREAD

**Issue by olga-pokrovsky** [nilmtk/nilmtk#474]
Hi,
I'm trying to run NILMTK on Windows7 after following the installation instructions. 
At the very beginning I get an error - I guess I missed something during the installation?

>>> from nilmtk import DataSet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\nilmtk\nilmtk\nilmtk\__init__.py", line 8, in <module>
    from nilmtk.elecmeter import ElecMeter
  File "c:\nilmtk\nilmtk\nilmtk\elecmeter.py", line 8, in <module>
    import matplotlib.pyplot as plt
  File "C:\Anaconda2\lib\site-packages\matplotlib\pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "C:\Anaconda2\lib\site-packages\matplotlib\backends\__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "C:\Anaconda2\lib\site-packages\matplotlib\backends\backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "C:\Anaconda2\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "C:\Anaconda2\lib\site-packages\matplotlib\backends\backend_qt5.py", line 27, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Anaconda2\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 17, in
<module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "C:\Anaconda2\lib\site-packages\matplotlib\backends\qt_editor\formlayout.py", line 58, in <mo
dule>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "C:\Anaconda2\lib\site-packages\matplotlib\backends\qt_compat.py", line 144, in <module>
    QtCore.Signal = QtCore.pyqtSignal
AttributeError: 'module' object has no attribute 'pyqtSignal'

Thanks a lot,
Olga

**Comment by nipunbatra** [comment]
Hi @olga-pokrovsky. This seems to be a case of matplotlib not installed properly. I wonder why matplotlib backend issues are popping up in the recent few days. 

To confirm this being a matplotlib issue, can you try the following:

```
python
import matplotlib.pyplot as plt
plt.figure()
```

**Comment by nipunbatra** [comment]
I think `conda update matplotlib` might work for you.

**Comment by olga-pokrovsky** [comment]
Thanks! Indeed there was some kind of mess with packages dependencies of matplotlib (pyqt maybe).
Actually I re-installed Anaconda and NILMTK and now I don't get the error from above.
