### ISSUE TITLE
ImportError: cannot import name DataSet

### ISSUE THREAD

**Issue by ineswater** [nilmtk/nilmtk#483]
In[2]: from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore

Traceback (most recent call last):
  File "C:\Users\water_000\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-8a26c2cbaf88>", line 1, in <module>
    from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
ImportError: cannot import name DataSet

Hi, i don't understand the error because at the others days this work perfectly and now I got this error.

Can anyone help me?

**Comment by JackKelly** [comment]
sounds like NILMTK is not in your Python path.  I would guess that `from nilmtk import DataSet` only works when you run Python from the `nilmtk/` path?

How did you install NILMTK?

**Comment by ineswater** [comment]
Using this:


Install NILM Metadata.
git clone https://github.com/nilmtk/nilm_metadata/
cd nilm_metadata
python setup.py develop
cd ..
Install psycopg2 First you need to install Postgres:
sudo apt-get install postgresql postgresql-contrib
sudo apt-get install postgresql-server-dev-all
pip install psycopg2
Misc. pip installs
pip install nose coveralls coverage
Finally! Install NILMTK
git clone https://github.com/nilmtk/nilmtk.git
cd nilmtk
python setup.py develop
cd..

**Comment by JackKelly** [comment]
ok, that sounds correct :)

were there any error messages during installation?  (especially the last step)

**Comment by ineswater** [comment]
no, but I installed it again and the previous error don't appear anymore. :)

unfortunately another error appears, so i put "hmmlearn" inside "disaggregate" and the following appears:


In[17]: from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore

In[18]: from nilmtk.disaggregate import CombinatorialOptimisation
Traceback (most recent call last):
  File "C:\Users\water_000\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-280cab9d47e5>", line 1, in <module>
    from nilmtk.disaggregate import CombinatorialOptimisation
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "c:\users\water_000\nilm_metadata\nilmtk\nilmtk\disaggregate\__init__.py", line 3, in <module>
    from .fhmm_exact import FHMM
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "c:\users\water_000\nilm_metadata\nilmtk\nilmtk\disaggregate\fhmm_exact.py", line 10, in <module>
    from hmmlearn import hmm
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "c:\users\water_000\nilm_metadata\nilmtk\nilmtk\disaggregate\hmmlearn\hmm.py", line 21, in <module>
    from .base import _BaseHMM, decoder_algorithms
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "c:\users\water_000\nilm_metadata\nilmtk\nilmtk\disaggregate\hmmlearn\base.py", line 8, in <module>
    from . import _hmmc
ImportError: cannot import name _hmmc

should i change some name ?

**Comment by ineswater** [comment]
no, but I installed it again and the previous error don't appear anymore. :)

thankks

**Comment by ancordova25** [comment]
I have the same problem but I installed the numpy with a wheel file in order to install it with MKL (numpy-1.11.3+mkl-cp35-cp35m-win32.whl) recommended [here](https://stackoverflow.com/questions/37267399/importerror-cannot-import-name-numpy-mkl). How can I solve it?

**Comment by nipunbatra** [comment]
@ancordova25 What installation instructions did you use?

**Comment by ancordova25** [comment]
The instructions of: https://stackoverflow.com/questions/37267399/importerror-cannot-import-name-numpy-mkl

**Comment by nipunbatra** [comment]
I meant instructions for installing NILMTK.

**Comment by ancordova25** [comment]
I downloaded the whl file in http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy. This one: numpy‑1.13.0+mkl‑cp35‑cp35m‑win32.whl. Then, I wrote: pip install C:/.../numpy‑1.13.0+mkl‑cp35‑cp35m‑win32.whl and numpy with mtk. I don't know what NILMTK is... My problem is when importing Dataset: from skmultilearn.dataset import Dataset. The error which appear is: 
from skmultilearn.dataset import Dataset ImportError: cannot import name 'Dataset'.
I'm trying to replicate the work of here: http://scikit.ml/api/loading.html

**Comment by nipunbatra** [comment]
@ancordova25 This repo is for NILMTK. Please file the bug in a relevant repository.
