### ISSUE TITLE
Plot problem (disaggregation_and_metrics)

### ISSUE THREAD

**Issue by InesSoares** [nilmtk/nilmtk#485]
Hi, when i run the code below appears that error and the code it's equal to the original one.

``` python
In[3]: from __future__ import print_function, division
import time
from matplotlib import rcParams
import matplotlib.pyplot as plt
%matplotlib 
rcParams['figure.figsize'] = (13, 6)
plt.style.use('ggplot')
Using matplotlib backend: Qt4Agg
In[4]: from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import CombinatorialOptimisation

In[5]: train = DataSet('C:/Users/water_000/nilm_metadata/nilmtk/nilmtk/dataset_converters/redd/redd.h5')
test = DataSet('C:/Users/water_000/nilm_metadata/nilmtk/nilmtk/dataset_converters/redd/redd.h5')

In[6]: building = 1

In[7]: train.buildings[building].elec.mains().plot()
Traceback (most recent call last):
  File "C:\Users\water_000\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-56216a3561a1>", line 1, in <module>
    train.buildings[building].elec.mains().plot()
  File "c:\users\water_000\nilm_metadata\nilmtk\nilmtk\metergroup.py", line 1373, in plot
    .format(kind))
ValueError: 'separate lines' not a valid setting for 'kind' parameter.
```

**Comment by nipunbatra** [comment]
I'd urge you to inspect at each variable you're using. That'll help you to develop a better understanding of nilmtk, Pandas, their inter-relationship.

Like, first inspect what `elec` contains, where we define `elec=train.buildings[building].elec`. Now, also inspect what `mains=elec.mains()` is. Then, inspect what data is in `mains`, by doing `mains.load().next()`.

**Comment by PMeira** [comment]
Since there is not enough information to investigate the issue and it's very old, I'm closing it. Please reopen if necessary.
