### ISSUE TITLE
Misleading exception when loading empty window

### ISSUE THREAD

**Issue by tonicebrian** [nilmtk/nilmtk#507]
I was trying to reproduce experiments from @JackKelly 's neuralnilm repo https://github.com/JackKelly/neuralnilm/blob/master/experiment_definitions/e575.py but I'm getting at first difficult to understand exceptions.

The code:

```python
from nilmtk import DataSet
import warnings
warnings.simplefilter('ignore')

dataset = DataSet('/home/cebrian/data/ukdale.h5')

dataset.set_window('2015-07-02', None)
meter = dataset.buildings[1].elec['kettle']

print meter.total_energy()

meter.get_activations(sample_period=6)
```

produces exception:

```
$ python test.py 
Series([], dtype: float64)
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    meter.get_activations(sample_period=6)
  File "/home/cebrian/GIT/nilmtk/nilmtk/electric.py", line 807, in get_activations
    for chunk in self.power_series(**kwargs):
  File "/home/cebrian/GIT/nilmtk/nilmtk/electric.py", line 629, in load_series
    for chunk in generator:
  File "/home/cebrian/GIT/nilmtk/nilmtk/preprocessing/apply.py", line 15, in process
    new_chunk = self.func(chunk)
  File "/home/cebrian/GIT/nilmtk/nilmtk/electric.py", line 145, in resample_func
    return safe_resample(df, **resample_kwargs)
  File "/home/cebrian/GIT/nilmtk/nilmtk/utils.py", line 383, in safe_resample
    data = data.resample(**resample_kwargs)
  File "/home/cebrian/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 3976, in resample
    base=base)
  File "/home/cebrian/.local/lib/python2.7/site-packages/pandas/tseries/resample.py", line 898, in resample
    return tg._get_resampler(obj, kind=kind)
  File "/home/cebrian/.local/lib/python2.7/site-packages/pandas/tseries/resample.py", line 1012, in _get_resampler
    "but got an instance of %r" % type(ax).__name__)
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
Closing remaining open files:/home/cebrian/data/ukdale.h5...done
```

So my question is, should the code handle the situation were empty signals are provided? And how? I'm willing to create a PR.

Did something change with UKDale dataset at http://data.ukedc.rl.ac.uk/simplebrowse/edc/efficiency/residential/EnergyConsumption/Domestic/UK-DALE-2015/UK-DALE-disaggregated/ukdale.h5.tgz that cannot be dealt with current master version of nilmtk?

Best regards.

**Comment by JackKelly** [comment]
> did something change with UKDale dataset at http://data.ukedc.rl.ac.uk/simplebrowse/edc/efficiency/residential/EnergyConsumption/Domestic/UK-DALE-2015/UK-DALE-disaggregated/ukdale.h5.tgz that cannot be dealt with current master version of nilmtk?

That's unlikely.  Not least because the version of UK-DALE available from the UKEDC is actually quite old :).   You could try downloading UK-DALE from my own FTP server.  Details here: https://www.doc.ic.ac.uk/~dk3810/data/

**Comment by tonicebrian** [comment]
@JackKelly with latest ukdale.h5 from your FTP server the above script works. So maybe it was some code that wasn't able to deal with missing series. Thanks.
