### ISSUE TITLE
nilmtk on BeagleBone

### ISSUE THREAD

**Issue by brunomb91** [nilmtk/nilmtk#520]
Hi,

I installed nilmtk on a BeagleBone Black, with operating system Debian, and I got these errors when I type nosetests:
# 
## ERROR: test suite for <class 'nilmtk.stats.tests.test_dropoutrate.TestLocateGoodSections'>

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 478, in try_run
    return func()
  File "/home/debian/nilmtk/nilmtk/stats/tests/test_dropoutrate.py", line 25, in setUpClass
    ElecMeter.load_meter_devices(cls.datastore)
  File "/home/debian/nilmtk/nilmtk/elecmeter.py", line 145, in load_meter_devices
    dataset_metadata = store.load_metadata('/')
  File "/home/debian/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, _args, *_kwargs)
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 180, in load_metadata
    node = self.store.root
AttributeError: 'HDFStore' object has no attribute 'root'
# 
## ERROR: test suite for <class 'nilmtk.stats.tests.test_locategoodsections.TestLocateGoodSections'>

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 478, in try_run
    return func()
  File "/home/debian/nilmtk/nilmtk/stats/tests/test_locategoodsections.py", line 24, in setUpClass
    ElecMeter.load_meter_devices(cls.datastore)
  File "/home/debian/nilmtk/nilmtk/elecmeter.py", line 145, in load_meter_devices
    dataset_metadata = store.load_metadata('/')
  File "/home/debian/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, _args, *_kwargs)
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 180, in load_metadata
    node = self.store.root
AttributeError: 'HDFStore' object has no attribute 'root'
# 
## ERROR: test suite for <class 'nilmtk.stats.tests.test_totalenergy.TestEnergy'>

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 478, in try_run
    return func()
  File "/home/debian/nilmtk/nilmtk/stats/tests/test_totalenergy.py", line 31, in setUpClass
    ElecMeter.load_meter_devices(cls.datastore)
  File "/home/debian/nilmtk/nilmtk/elecmeter.py", line 145, in load_meter_devices
    dataset_metadata = store.load_metadata('/')
  File "/home/debian/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, _args, *_kwargs)
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 180, in load_metadata
    node = self.store.root
AttributeError: 'HDFStore' object has no attribute 'root'
# 
## ERROR: test suite for <class 'nilmtk.tests.test_combinatorial_optimisation.TestCO'>

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 478, in try_run
    return func()
  File "/home/debian/nilmtk/nilmtk/tests/test_combinatorial_optimisation.py", line 17, in setUpClass
    cls.dataset = DataSet(filename)
  File "/home/debian/nilmtk/nilmtk/dataset.py", line 44, in **init**
    self.import_metadata(get_datastore(filename, format))
  File "/home/debian/nilmtk/nilmtk/dataset.py", line 53, in import_metadata
    self.metadata = store.load_metadata()
  File "/home/debian/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, _args, *_kwargs)
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 180, in load_metadata
    node = self.store.root
AttributeError: 'HDFStore' object has no attribute 'root'
# 
## ERROR: test_load (nilmtk.tests.test_datastore.TestCSVDataStore)

Traceback (most recent call last):
  File "/home/debian/nilmtk/nilmtk/tests/test_datastore.py", line 37, in test_load
    df = next(gen)
  File "/home/debian/nilmtk/nilmtk/datastore/csvdatastore.py", line 72, in load
    chunksize=chunksize)
  File "/usr/lib/pymodules/python2.7/pandas/io/parsers.py", line 236, in read_csv
    return _read(TextParser, filepath_or_buffer, kwds)
  File "/usr/lib/pymodules/python2.7/pandas/io/parsers.py", line 171, in _read
    f = com._get_handle(filepath_or_buffer, 'r', encoding=encoding)
  File "/usr/lib/pymodules/python2.7/pandas/core/common.py", line 861, in _get_handle
    f = open(path, mode)
IOError: [Errno 2] No such file or directory: '/home/debian/nilmtk/data/random_csv/building1/elec/meter1.csv'
# 
## ERROR: test_load_chunks (nilmtk.tests.test_datastore.TestCSVDataStore)

Traceback (most recent call last):
  File "/home/debian/nilmtk/nilmtk/tests/test_datastore.py", line 47, in test_load_chunks
    for chunk in chunks:
  File "/home/debian/nilmtk/nilmtk/datastore/csvdatastore.py", line 72, in load
    chunksize=chunksize)
  File "/usr/lib/pymodules/python2.7/pandas/io/parsers.py", line 236, in read_csv
    return _read(TextParser, filepath_or_buffer, kwds)
  File "/usr/lib/pymodules/python2.7/pandas/io/parsers.py", line 171, in _read
    f = com._get_handle(filepath_or_buffer, 'r', encoding=encoding)
  File "/usr/lib/pymodules/python2.7/pandas/core/common.py", line 861, in _get_handle
    f = open(path, mode)
IOError: [Errno 2] No such file or directory: '/home/debian/nilmtk/data/random_csv/building1/elec/meter1.csv'
# 
## ERROR: test_load_chunks_small_chunksize (nilmtk.tests.test_datastore.TestCSVDataStore)

Traceback (most recent call last):
  File "/home/debian/nilmtk/nilmtk/tests/test_datastore.py", line 86, in test_load_chunks_small_chunksize
    for i, chunk in enumerate(chunks):
  File "/home/debian/nilmtk/nilmtk/datastore/csvdatastore.py", line 72, in load
    chunksize=chunksize)
  File "/usr/lib/pymodules/python2.7/pandas/io/parsers.py", line 236, in read_csv
    return _read(TextParser, filepath_or_buffer, kwds)
  File "/usr/lib/pymodules/python2.7/pandas/io/parsers.py", line 171, in _read
    f = com._get_handle(filepath_or_buffer, 'r', encoding=encoding)
  File "/usr/lib/pymodules/python2.7/pandas/core/common.py", line 861, in _get_handle
    f = open(path, mode)
IOError: [Errno 2] No such file or directory: '/home/debian/nilmtk/data/random_csv/building1/elec/meter1.csv'
# 
## ERROR: test_timeframe (nilmtk.tests.test_datastore.TestCSVDataStore)

Traceback (most recent call last):
  File "/home/debian/nilmtk/nilmtk/tests/test_datastore.py", line 21, in test_timeframe
    self.assertEqual(self.datastore.get_timeframe(key), self.TIMEFRAME)
  File "/home/debian/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, _args, *_kwargs)
  File "/home/debian/nilmtk/nilmtk/datastore/csvdatastore.py", line 224, in get_timeframe
    chunksize=MAX_MEM_ALLOWANCE_IN_BYTES)
  File "/usr/lib/pymodules/python2.7/pandas/io/parsers.py", line 236, in read_csv
    return _read(TextParser, filepath_or_buffer, kwds)
  File "/usr/lib/pymodules/python2.7/pandas/io/parsers.py", line 171, in _read
    f = com._get_handle(filepath_or_buffer, 'r', encoding=encoding)
  File "/usr/lib/pymodules/python2.7/pandas/core/common.py", line 861, in _get_handle
    f = open(path, mode)
IOError: [Errno 2] No such file or directory: '/home/debian/nilmtk/data/random_csv/building1/elec/meter1.csv'
# 
## ERROR: test_column_names (nilmtk.tests.test_datastore.TestHDFDataStore)

Traceback (most recent call last):
  File "/home/debian/nilmtk/nilmtk/tests/test_datastore.py", line 112, in test_column_names
    self.assertEqual(self.datastore._column_names(key),
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 251, in _column_names
    self._check_key(key)
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 316, in _check_key
    raise KeyError(key + ' not in store')
KeyError: '/building1/elec/meter1 not in store'
# 
## ERROR: test_estimate_memory_requirement (nilmtk.tests.test_datastore.TestHDFDataStore)

Traceback (most recent call last):
  File "/home/debian/nilmtk/nilmtk/tests/test_datastore.py", line 128, in test_estimate_memory_requirement
    mem = self.datastore._estimate_memory_requirement(key, self.datastore._nrows(key))
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 293, in _nrows
    coords = self.store.select_as_coordinates(key, terms)
AttributeError: 'HDFStore' object has no attribute 'select_as_coordinates'
# 
## ERROR: test_load (nilmtk.tests.test_datastore.TestHDFDataStore)

Traceback (most recent call last):
  File "/home/debian/nilmtk/nilmtk/tests/test_datastore.py", line 37, in test_load
    df = next(gen)
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 90, in load
    coords = self.store.select_as_coordinates(key=key, where=terms)
AttributeError: 'HDFStore' object has no attribute 'select_as_coordinates'
# 
## ERROR: test_load_chunks (nilmtk.tests.test_datastore.TestHDFDataStore)

Traceback (most recent call last):
  File "/home/debian/nilmtk/nilmtk/tests/test_datastore.py", line 47, in test_load_chunks
    for chunk in chunks:
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 82, in load
    section_end_i = self.store.get_storer(key).nrows
AttributeError: 'HDFStore' object has no attribute 'get_storer'
# 
## ERROR: test_load_chunks_small_chunksize (nilmtk.tests.test_datastore.TestHDFDataStore)

Traceback (most recent call last):
  File "/home/debian/nilmtk/nilmtk/tests/test_datastore.py", line 86, in test_load_chunks_small_chunksize
    for i, chunk in enumerate(chunks):
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 90, in load
    coords = self.store.select_as_coordinates(key=key, where=terms)
AttributeError: 'HDFStore' object has no attribute 'select_as_coordinates'
# 
## ERROR: test_n_rows (nilmtk.tests.test_datastore.TestHDFDataStore)

Traceback (most recent call last):
  File "/home/debian/nilmtk/nilmtk/tests/test_datastore.py", line 120, in test_n_rows
    self.assertEqual(self.datastore._nrows(key), 10*60)
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 293, in _nrows
    coords = self.store.select_as_coordinates(key, terms)
AttributeError: 'HDFStore' object has no attribute 'select_as_coordinates'
# 
## ERROR: test_timeframe (nilmtk.tests.test_datastore.TestHDFDataStore)

Traceback (most recent call last):
  File "/home/debian/nilmtk/nilmtk/tests/test_datastore.py", line 21, in test_timeframe
    self.assertEqual(self.datastore.get_timeframe(key), self.TIMEFRAME)
  File "/home/debian/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, _args, *_kwargs)
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 220, in get_timeframe
    data_start_date = self.store.select(key, [0]).index[0]
  File "/usr/lib/pymodules/python2.7/pandas/io/pytables.py", line 317, in select
    return self._read_group(group, where)
  File "/usr/lib/pymodules/python2.7/pandas/io/pytables.py", line 803, in _read_group
    return handler(group, where)
  File "/usr/lib/pymodules/python2.7/pandas/io/pytables.py", line 830, in _read_frame_table
    return self._read_panel_table(group, where)['value']
  File "/usr/lib/pymodules/python2.7/pandas/io/pytables.py", line 834, in _read_panel_table
    fields = table._v_attrs.fields
  File "/usr/lib/python2.7/dist-packages/tables/attributeset.py", line 302, in __getattr__
    (name, self._v__nodePath)
AttributeError: Attribute 'fields' does not exist in node: '/building1/elec/meter1/table'
# 
## ERROR: Failure: AttributeError ('HDFStore' object has no attribute 'root')

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/debian/nilmtk/nilmtk/tests/test_datastore_converter.py", line 15, in <module>
    convert_datastore(input_store, output_store)
  File "/home/debian/nilmtk/nilmtk/datastore/datastore.py", line 233, in convert_datastore
    metadata = input_store.load_metadata()
  File "/home/debian/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, _args, *_kwargs)
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 180, in load_metadata
    node = self.store.root
AttributeError: 'HDFStore' object has no attribute 'root'
# 
## ERROR: test suite for <class 'nilmtk.tests.test_elecmeter.TestElecMeter'>

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 478, in try_run
    return func()
  File "/home/debian/nilmtk/nilmtk/tests/test_elecmeter.py", line 22, in setUpClass
    ElecMeter.load_meter_devices(cls.datastore)
  File "/home/debian/nilmtk/nilmtk/elecmeter.py", line 145, in load_meter_devices
    dataset_metadata = store.load_metadata('/')
  File "/home/debian/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, _args, *_kwargs)
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 180, in load_metadata
    node = self.store.root
AttributeError: 'HDFStore' object has no attribute 'root'
# 
## ERROR: test suite for <class 'nilmtk.tests.test_fhmm.TestFHMM'>

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 478, in try_run
    return func()
  File "/home/debian/nilmtk/nilmtk/tests/test_fhmm.py", line 17, in setUpClass
    cls.dataset = DataSet(filename)
  File "/home/debian/nilmtk/nilmtk/dataset.py", line 44, in **init**
    self.import_metadata(get_datastore(filename, format))
  File "/home/debian/nilmtk/nilmtk/dataset.py", line 53, in import_metadata
    self.metadata = store.load_metadata()
  File "/home/debian/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, _args, *_kwargs)
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 180, in load_metadata
    node = self.store.root
AttributeError: 'HDFStore' object has no attribute 'root'
# 
## ERROR: test suite for <class 'nilmtk.tests.test_metergroup.TestMeterGroup'>

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 478, in try_run
    return func()
  File "/home/debian/nilmtk/nilmtk/tests/test_metergroup.py", line 17, in setUpClass
    ElecMeter.load_meter_devices(cls.datastore)
  File "/home/debian/nilmtk/nilmtk/elecmeter.py", line 145, in load_meter_devices
    dataset_metadata = store.load_metadata('/')
  File "/home/debian/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, _args, *_kwargs)
  File "/home/debian/nilmtk/nilmtk/datastore/hdfdatastore.py", line 180, in load_metadata
    node = self.store.root
AttributeError: 'HDFStore' object has no attribute 'root'

---

Ran 24 tests in 8.431s

FAILED (errors=19)

I coudn't install anaconda on BeagleBone, so I had to install for the old installation. What do you think about it? Do I need to install any package?

**Comment by nipunbatra** [comment]
System installation issues apart, I think nilmtk isn't optimised to be installed on embedded platforms.

**Comment by nipunbatra** [comment]
@brunomb91 : Did you have any success?
