### ISSUE TITLE
Nosetest failure - Testfhmm

### ISSUE THREAD

**Issue by JoshuaC3** [nilmtk/nilmtk#527]
Here is the error

I used the old windows install as other installs also failed.

```
(pynlimtk) C:\Users\admin\nilmtk>nosetests
C:\Anaconda\envs\pynlimtk\lib\site-packages\matplotlib\backends\qt_compat.py:97:
 ImportWarning: Not importing directory 'C:\Anaconda\envs\pynlimtk\sip': missing
 __init__.py
  import sip
.......................E....................Unlink of file 'data/energy.h5' fail
ed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n)
Sorry, I did not understand your answer. Please type 'y' or 'n'
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) n
error: unable to unlink old 'data/energy.h5' (Invalid argument)
E
======================================================================
ERROR: test_fhmm_correctness (nilmtk.tests.test_fhmm.TestFHMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\admin\nilmtk\nilmtk\tests\test_fhmm.py", line 26, in test_fhmm_
correctness
    fhmm.train(elec)
  File "C:\Users\admin\nilmtk\nilmtk\disaggregate\fhmm_exact.py", line 287, in t
rain
    learnt_model[meter].fit([X])
  File "C:\Users\admin\AppData\Roaming\Python\Python27\site-packages\hmmlearn\ba
se.py", line 420, in fit
    X = check_array(X)
  File "C:\Anaconda\envs\pynlimtk\lib\site-packages\sklearn\utils\validation.py"
, line 396, in check_array
    % (array.ndim, estimator_name))
ValueError: Found array with dim 3. Estimator expected <= 2.
-------------------- >> begin captured stdout << ---------------------
Training model for submeter 'ElecMeter(instance=2, building=1, dataset=None, app
liances=[])'

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test suite for <module 'nilmtk' from 'C:\Users\admin\nilmtk\nilmtk\__init
__.pyc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda\envs\pynlimtk\lib\site-packages\nose\suite.py", line 228, in
 run
    self.tearDown()
  File "C:\Anaconda\envs\pynlimtk\lib\site-packages\nose\suite.py", line 351, in
 tearDown
    self.teardownContext(ancestor)
  File "C:\Anaconda\envs\pynlimtk\lib\site-packages\nose\suite.py", line 367, in
 teardownContext
    try_run(context, names)
  File "C:\Anaconda\envs\pynlimtk\lib\site-packages\nose\util.py", line 471, in
try_run
    return func()
  File "C:\Users\admin\nilmtk\nilmtk\__init__.py", line 29, in teardown_package
    subprocess.check_output(cmd, shell=True, cwd=data_dir())
  File "C:\Anaconda\envs\pynlimtk\lib\subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'git checkout -- C:\Users\admin\nilmtk\data' returne
d non-zero exit status 255

----------------------------------------------------------------------
Ran 44 tests in 39.522s

FAILED (errors=2)
Closing remaining open files:C:\Users\admin\nilmtk\data\energy.h5...done
```

Would you like any further info?

**Comment by JackKelly** [comment]
Hi @JoshuaC3, thanks for the issue post.  Please see issue #361 as I believe that it is the same issue as the one you are having?

**Comment by JoshuaC3** [comment]
Yes. It looks like it. My apologies for opening another issue.
