### ISSUE TITLE
F1-score error

### ISSUE THREAD

**Issue by InesSoares** [nilmtk/nilmtk#546]

**Comment by nipunbatra** [comment]
Can you help us to replicate this bug? We'd need all the usual details- script, dataset, etc.

**Comment by InesSoares** [comment]
from nilmtk import DataSet
train = DataSet('nilmtk/data/redd.h5')
test = DataSet('nilmtk/data/redd.h5')

building = 1
train.buildings[building].elec.mains().plot()

from __future__ import print_function, division
import time
from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import CombinatorialOptimisation

train.set_window(end="30-4-2011")
test.set_window(start="30-4-2011")


train_elec = train.buildings[1].elec
test_elec = test.buildings[1].elec

test_elec.mains().plot()
fridge_meter = train_elec['fridge']
fridge_df = fridge_meter.load().next()
fridge_df.head()

mains = train_elec.mains()
mains_df = mains.load().next()
mains_df.head()

top_3_train_elec=train_elec.submeters().select_using_appliances(type=['fridge','microwave','electric oven'])

start = time.time()
from nilmtk.disaggregate import fhmm_exact
fhmm = fhmm_exact.FHMM()
fhmm.train(top_3_train_elec, sample_period=60)
end = time.time()
print("Runtime =", end-start, "seconds.")


output = HDFDataStore('nilmtk/data/redd-disag-fhmm.h5', 'w')
fhmm.disaggregate(test_elec.mains(), output, sample_period=60)
output.close()

**Comment by InesSoares** [comment]
And when i try to run:

top_5_train_elec = train_elec.submeters().select_top_k(k=5)

the "ValueError: Iteration of zero-sized operands is not enabled" appears again:

OUTPUT:

1/16 ElecMeter(instance=5, building=1, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])Traceback (most recent call last):
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-5438c0269107>", line 1, in <module>
    top_5_train_elec = train_elec.submeters().select_top_k(k=5)
  File "c:\users\aisoares.desktop-lssbbal\nilmtk\nilmtk\metergroup.py", line 1300, in select_top_k
    top_k_series = function_map[by](**kwargs)
  File "c:\users\aisoares.desktop-lssbbal\nilmtk\nilmtk\metergroup.py", line 1179, in fraction_per_meter
    energy_per_meter = self.energy_per_meter(**load_kwargs).max()
  File "c:\users\aisoares.desktop-lssbbal\nilmtk\nilmtk\metergroup.py", line 1127, in energy_per_meter
    meter_energy = meter.total_energy(**load_kwargs)
  File "c:\users\aisoares.desktop-lssbbal\nilmtk\nilmtk\elecmeter.py", line 586, in total_energy
    nodes, TotalEnergy.results_class(), loader_kwargs)
  File "c:\users\aisoares.desktop-lssbbal\nilmtk\nilmtk\elecmeter.py", line 664, in _get_stat_from_cache_or_compute
    results_obj_copy = deepcopy(results_obj)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\copy.py", line 174, in deepcopy
    y = copier(memo)
ValueError: Iteration of zero-sized operands is not enabled

**Comment by InesSoares** [comment]
Hi, @nipunbatra 
I'm using the dataset=redd to use FHMM disag.
So I'm capable to train and disaggregate but when i try to get the metrics this give me an error

IN: 
f1_fhmm = f1_score(disag_fhmm_elec, test_elec)

OUT:
Traceback (most recent call last):
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-c5b0874789e1>", line 2, in <module>
    f1_fhmm = f1_score(disag_fhmm_elec.select(instance=6), test_elec.select(instance=6))
  File "c:\users\aisoares.desktop-lssbbal\nilmtk\nilmtk\metrics.py", line 225, in f1_score
    for aligned_states_chunk in aligned_meters:
  File "c:\users\aisoares.desktop-lssbbal\nilmtk\nilmtk\electric.py", line 848, in align_two_meters
    yield pd.DataFrame({'master': master_chunk, 'slave': slave_chunk})
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\site-packages\pandas\core\frame.py", line 223, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\site-packages\pandas\core\frame.py", line 359, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\site-packages\pandas\core\frame.py", line 5240, in _arrays_to_mgr
    index = extract_index(arrays)
  File "C:\Users\aisoares.DESKTOP-LSSBBAL\Anaconda2\lib\site-packages\pandas\core\frame.py", line 5288, in extract_index
    raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length


Other strange thing that happen is when I get the disag. output. 
When we are disaggregating all the appliances, we know, that some of them are in the 1st main and others are in the second one. So, what happen is the following:

(additional information to understand)
                 train = DataSet('nilmtk/data/redd.h5')
                 test = DataSet('nilmtk/data/redd.h5')

                 building = 2
                 train.set_window(end="30-4-2011")
                 test.set_window(start="30-4-2011")

                 train_elec = train.buildings[building].elec
                 test_elec = test.buildings[building].elec

                 start = time.time()
                 fhmm = fhmm_exact.FHMM()
                 fhmm.train(train_elec, sample_period=60)
                 end = time.time()
                 print("Runtime =", end-start, "seconds.")

                 disag_filename = 'nilmtk/data/redd-disag-fhmm.h5'
                 output = HDFDataStore(disag_filename, 'w')
                 fhmm.disaggregate(test_elec.select.mains(), output, sample_period=60)
                  output.close()

                 disag_fhmm = DataSet(disag_filename)
                 disag_fhmm_elec = disag_fhmm.buildings[building].elec

IN: 
disag_fhmm_elec

OUT:
MeterGroup(meters=
  ElecMeter(instance=1, building=2, dataset='FHMM', site_meter, appliances=[])
  ElecMeter(instance=3, building=2, dataset='FHMM', appliances=[Appliance(type='sockets',instance=1)])
  ElecMeter(instance=4, building=2, dataset='FHMM', appliances=[Appliance(type='light', instance=1)])
  ElecMeter(instance=5, building=2, dataset='FHMM', appliances=[Appliance(type='electric stove', instance=1)])
  ElecMeter(instance=6, building=2, dataset='FHMM', appliances=[Appliance(type='microwave', instance=1)])
  ElecMeter(instance=7, building=2, dataset='FHMM', appliances=[Appliance(type='washer dryer', instance=1)])
  ElecMeter(instance=8, building=2, dataset='FHMM', appliances=[Appliance(type='sockets', instance=2)])
  ElecMeter(instance=9, building=2, dataset='FHMM', appliances=[Appliance(type='fridge', instance=1)])
  ElecMeter(instance=10, building=2, dataset='FHMM', appliances=[Appliance(type='dish washer', instance=1)])
  ElecMeter(instance=11, building=2, dataset='FHMM', appliances=[Appliance(type='waste disposal unit', instance=1)])
)

I only got the output disag. of the 1st main and in the middle i have one appliance that is disaggregated from the second main.

**Comment by nipunbatra** [comment]
>I only got the output disag. of the 1st main and in the middle i have one appliance that is disaggregated from the second main. Why?

`instance` refers to the instance of the appliance. In this case, there are multiple sockets. Thus, the second sockets appliance/appliance group has instance=2. Disaggregation is here done on the total mains, i.e., the sum of the two mains. I hope this clarifies your doubt. I'll now try and replicate your bug.

**Comment by InesSoares** [comment]
@nipunbatra Thank you !

**Comment by nipunbatra** [comment]
I tested your code. I get a different error.
PS this notebook: https://github.com/nilmtk/nilmtk/blob/master/notebooks/issues/546.ipynb

The following two images show the train and the test data set plots.
![1](https://cloud.githubusercontent.com/assets/60985/23853032/c099f0e0-0810-11e7-902f-00f9187a399a.png)
![2](https://cloud.githubusercontent.com/assets/60985/23853033/c09c69b0-0810-11e7-8709-6ab3467cc38b.png)

I believe that the bug can be caused due to the high amount of missing data in this house.

Can you please test if you get a similar error on some other home from the dataset?

**Comment by nipunbatra** [comment]
Ok, I believe that the error mainly come due to the HDF5 store. I plan to simplify NILMTK. For now, here is how you can get the desired results.

```python
import pandas as pd
import numpy as np

pred = {}
gt= {}

for i, chunk in enumerate(test_elec.mains().load(sample_period=120)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    
    for meter in test_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)    
        gt[i][meter] = meter.load(sample_period=120).next()
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in gt[i].iteritems()}, index=gt[i].values()[0].index).dropna()


# If everything can fit in memory
gt_overall = pd.concat(gt)
gt_overall.index = gt_overall.index.droplevel()
pred_overall = pd.concat(pred)
pred_overall.index = pred_overall.index.droplevel()

# Having the same order of columns
gt_overall = gt_overall[pred_overall.columns]

from sklearn.metrics import mean_squared_error

rmse={}
for col in pred_overall.columns:
    rmse[col] = np.sqrt(mean_squared_error(gt_overall[col], pred_overall[col]))

pd.Series(rmse).plot(kind="barh")
```

![1](https://cloud.githubusercontent.com/assets/60985/23886081/f8791968-089d-11e7-98f8-1f8772b6492f.png)

Hope this helps.

Please see: https://github.com/nilmtk/nilmtk/blob/master/notebooks/issues/546.ipynb for the corresponding notebook.
