### ISSUE TITLE
Unlink of file 'data/energy.h5' failed                                                                                                                                                                                                                                                                   

### ISSUE THREAD

**Issue by WangChunyi** [nilmtk/nilmtk#549]
it occur the problem when I run NILMTK tests, please help me look look, Thank you, good luck for you.

$ nosetests
C:\Users\Administrator\Anaconda2\lib\site-packages\matplotlib\backends\qt_compat                                                                                                                                                                                               .py:97: ImportWarning: Not importing directory 'C:\Users\Administrator\Anaconda2                                                                                                                                                                                               \sip': missing __init__.py
  import sip
............................................Unlink of file 'data/energy.h5' fail                                                                                                                                                                                               ed. Should I try again? (y/n) n
error: unable to unlink old 'data/energy.h5': Invalid argument
E
======================================================================
ERROR: test suite for <module 'nilmtk' from 'C:\Users\Administrator\Git\nilmtk\n                                                                                                                                                                                               ilmtk\__init__.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\nose\suite.py", line                                                                                                                                                                                                228, in run
    self.tearDown()
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\nose\suite.py", line                                                                                                                                                                                                351, in tearDown
    self.teardownContext(ancestor)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\nose\suite.py", line                                                                                                                                                                                                367, in teardownContext
    try_run(context, names)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\nose\util.py", line 4                                                                                                                                                                                               71, in try_run
    return func()
  File "C:\Users\Administrator\Git\nilmtk\nilmtk\__init__.py", line 29, in teard                                                                                                                                                                                               own_package
    subprocess.check_output(cmd, shell=True, cwd=data_dir())
  File "C:\Users\Administrator\Anaconda2\lib\subprocess.py", line 219, in check_                                                                                                                                                                                               output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'git checkout -- C:\Users\Administrator\Git\nilmtk\d                                                                                                                                                                                               ata' returned non-zero exit status 255

----------------------------------------------------------------------
Ran 44 tests in 151.390s

FAILED (errors=1)
Closing remaining open files:C:\Users\Administrator\Git\nilmtk\data\energy.h5...                                                                                                                                                                                               done

**Comment by nipunbatra** [comment]
I'd say not to worry about this error. You can continue to use NILMTK.
