### ISSUE TITLE
ValueError: The truth value of a Series is ambiguous (Disaggregate chunk using CO)

### ISSUE THREAD

**Issue by manojm18** [nilmtk/nilmtk#550]
@nipunbatra 
based on the codes in [546](https://github.com/nilmtk/nilmtk/blob/master/notebooks/issues/546.ipynb), i tried to reproduce the same with CombinatorialOptimisation. I ran into the error the code below

```Python
import time
start = time.time()
co = CombinatorialOptimisation()
co.train(train_elec, sample_period=60)
end = time.time()
print("Runtime =", end-start, "seconds.")


pred = {}
gt = {}

for i, chunk in enumerate(test_elec.mains().load(sample_period=60)):
    chunk_drop_na = chunk.dropna()
    pred[i] = co.disaggregate_chunk(chunk_drop_na)
    gt[i] = {}
    
    for meter in test_elec.submeters().meters:
        gt[i][meter] = meter.load(sample_period=120).next()
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in gt[i].iteritems()},index=gt[i].values()[0].index).dropna()
```
The error being
```Python
Training model for submeter 'ElecMeter(instance=2, building=1, dataset='Dataport', appliances=[Appliance(type='air conditioner', instance=1)])'
Training model for submeter 'ElecMeter(instance=3, building=1, dataset='Dataport', appliances=[Appliance(type='air conditioner', instance=2)])'
Training model for submeter 'ElecMeter(instance=4, building=1, dataset='Dataport', appliances=[Appliance(type='dish washer', instance=1)])'
Training model for submeter 'ElecMeter(instance=5, building=1, dataset='Dataport', appliances=[Appliance(type='spin dryer', instance=1)])'
Training model for submeter 'ElecMeter(instance=6, building=1, dataset='Dataport', appliances=[Appliance(type='sockets', instance=1)])'
Training model for submeter 'ElecMeter(instance=7, building=1, dataset='Dataport', appliances=[Appliance(type='light', instance=1)])'
Training model for submeter 'ElecMeter(instance=8, building=1, dataset='Dataport', appliances=[Appliance(type='sockets', instance=2)])'
Training model for submeter 'ElecMeter(instance=9, building=1, dataset='Dataport', appliances=[Appliance(type='fridge', instance=1)])'
Done training!
('Runtime =', 5.266999959945679, 'seconds.')
Traceback (most recent call last):

  File "<ipython-input-6-23a0b52bdb18>", line 14, in <module>
    pred[i] = co.disaggregate_chunk(chunk_drop_na)

  File "c:\users\manoj\nilmtk\nilmtk\disaggregate\combinatorial_optimisation.py", line 231, in disaggregate_chunk
    if vampire_power > 0:

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\core\generic.py", line 731, in __nonzero__
    .format(self.__class__.__name__))

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```
I tried to change the pandas version. But it gives the same error. I have pandas 0.17.1 right now.
How can I fix this ?

**Comment by nipunbatra** [comment]
I closed this in the latest commit. Please pull nilmtk to the latest version, restart your kernel and you should be good to go.  PS: https://github.com/nilmtk/nilmtk/blob/master/notebooks/issues/550.ipynb for a working example.
