### ISSUE TITLE
AmbiguousTimeError: Cannot infer dst time from Timestamp - Dataport Converter 

### ISSUE THREAD

**Issue by manojm18** [nilmtk/nilmtk#551]
@oliparson @nipunbatra 
I was trying to download dataport data for a specific building (6636) year 2013 from October to December.
I tried with different buildings, but i am getting the same error. guess it has to do with the query range (october - december)

the query being
`download_dataport('username',
                          'password',
                          'path/6636_oct_to_dec_2013.h5',
                          periods_to_load = {6636: ('2013-10-01', '2014-01-01')})
`
```Python
runfile('C:/Users/MANOJ/nilmtk/nilmtk/dataset_converters/dataport/download_dataport.py', wdir='C:/Users/MANOJ/nilmtk/nilmtk/dataset_converters/dataport')
Reloaded modules: nilmtk.stats.totalenergy, nilmtk.preprocessing, nilmtk.timeframegroup, nilmtk, nilmtk.stats.dropoutrate, nilmtk.version, nilm_metadata.version, nilmtk.preprocessing.apply, nilmtk.stats, nilmtk.electric, nilmtk.node, nilmtk.stats.goodsections, nilmtk.stats.dropoutrateresults, nilmtk.elecmeter, nilmtk.consts, nilm_metadata.object_concatenation, nilmtk.datastore.hdfdatastore, nilm_metadata, nilm_metadata.convert_yaml_to_hdf5, nilmtk.measurement, nilmtk.dataset, nilmtk.docinherit, nilmtk.stats.totalenergyresults, nilmtk.plots, nilmtk.building, nilmtk.datastore.csvdatastore, nilmtk.datastore, nilmtk.preprocessing.clip, nilmtk.timeframe, nilmtk.stats.goodsectionsresults, nilmtk.utils, nilmtk.appliance, nilmtk.datastore.datastore, nilmtk.hashable, nilmtk.stats.histogram, nilm_metadata.file_management, nilmtk.datastore.key, nilmtk.exceptions, nilmtk.metergroup, nilmtk.results
Loading building 6636 @ 2017-03-16 12:43:58.749000
  Loading table electricity_egauge_minutes
    2013-10-01 00:00:00-05:00 -> 2013-10-10 23:59:59-05:00: 14400 rows
    2013-10-11 00:00:00-05:00 -> 2013-10-20 23:59:59-05:00: 14400 rows
    2013-10-21 00:00:00-05:00 -> 2013-10-30 23:59:59-05:00: 14400 rows
Traceback (most recent call last):

  File "<ipython-input-2-abbc29a94b3f>", line 1, in <module>
    runfile('C:/Users/MANOJ/nilmtk/nilmtk/dataset_converters/dataport/download_dataport.py', wdir='C:/Users/MANOJ/nilmtk/nilmtk/dataset_converters/dataport')

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/MANOJ/nilmtk/nilmtk/dataset_converters/dataport/download_dataport.py", line 410, in <module>
    periods_to_load = {6636: ('2013-10-01', '2014-01-01')})

  File "C:/Users/MANOJ/nilmtk/nilmtk/dataset_converters/dataport/download_dataport.py", line 276, in download_dataport
    building_id)

  File "C:/Users/MANOJ/nilmtk/nilmtk/dataset_converters/dataport/download_dataport.py", line 318, in _dataport_dataframe_to_hdf
    local_dataframe = local_dataframe.tz_localize('US/Central')

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\util\decorators.py", line 89, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\core\generic.py", line 4361, in tz_localize
    ax =  _tz_localize(ax, tz, ambiguous)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\core\generic.py", line 4349, in _tz_localize
    ax = ax.tz_localize(tz, ambiguous=ambiguous)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\util\decorators.py", line 89, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\tseries\index.py", line 1724, in tz_localize
    ambiguous=ambiguous)

  File "pandas\tslib.pyx", line 3772, in pandas.tslib.tz_localize_to_utc (pandas\tslib.c:64823)

AmbiguousTimeError: Cannot infer dst time from Timestamp('2013-11-03 01:00:00'), try using the 'ambiguous' argument
```
some thing to do with the time zone offset ?

or it possible i can skip this date (2013-11-03). split the year at this date, download 2 separate h5 files and then join them?

**Comment by manojm18** [comment]
Thanks Grant(from Pecan Street - Dataport Team)for the fix

The problem seems to be related to the ending of the Daylight savings time
(DST).  setting the localized timezone to tz_localize('US/Central', ambiguous='infer').
This is from a pull request that addressed this at [502](https://github.com/nilmtk/nilmtk/pull/502/commits/f3ca23de8446ab8dddb6d90e37ed1cde2d6bf5ce)
