### ISSUE TITLE
Proper IDE tool for developing algorithm of nilmtk

### ISSUE THREAD

**Issue by lee813** [nilmtk/nilmtk#557]
Hi Nipun,

Thank you for developing this tool kit, it helps us a lot.
I have setup the nilmtk environment and run some test successfully.
But I need an IDE to develop my own algorithm, it's hard to use jupyter notebook to do this. I have used also spyder of anaconda, but it always show me lot of unexpected error, and it is running ok on jupyter notebook.
So I want to know which IDE to use recommand to use? or is there any guide to use nilmtk in spyder?

Thank you very much

**Comment by nipunbatra** [comment]
I prefer to use PyCharm for writing code and Jupyter notebook when I need interactive running.

**Comment by lee813** [comment]
Thank you for your comment,
I tried also PyCharm, But still the code is not working in PyCharm either. However it is working in Jupyter notebook.
Here is my code:
```
from nilmtk import *
from nilmtk.disaggregate import fhmm_exact

train = DataSet('/path/redd.h5')

building = 1
train.set_window(start="2011-04-29",end="2011-4-30")
train_elec = train.buildings[building].elec

top_5_train_elec = train_elec.submeters().select_top_k(k=5)
```

I get this error when I am calling select_top_k()

```
Traceback (most recent call last):
  File "/path/Documents/nilmtk/nilmtk/redd.py", line 23, in <module>
1/9 ElecMeter(instance=3, building=2, dataset='REDD', appliances=[Appliance(type='sockets', instance=1)])    top_5_train_elec = train_elec.submeters().select_top_k(k=5)
  File "/path/Documents/nilmtk/nilmtk/nilmtk/metergroup.py", line 1300, in select_top_k
    top_k_series = function_map[by](**kwargs)
  File "/path/Documents/nilmtk/nilmtk/nilmtk/metergroup.py", line 1179, in fraction_per_meter
    energy_per_meter = self.energy_per_meter(**load_kwargs).max()
  File "/path/Documents/nilmtk/nilmtk/nilmtk/metergroup.py", line 1127, in energy_per_meter
    meter_energy = meter.total_energy(**load_kwargs)
  File "/path/Documents/nilmtk/nilmtk/nilmtk/elecmeter.py", line 586, in total_energy
    nodes, TotalEnergy.results_class(), loader_kwargs)
  File "/path/Documents/nilmtk/nilmtk/nilmtk/elecmeter.py", line 664, in _get_stat_from_cache_or_compute
    results_obj_copy = deepcopy(results_obj)
  File "/path/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/path/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/path/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/path/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/path/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/path/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/path/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/path/anaconda2/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/path/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/path/anaconda2/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/path/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/path/anaconda2/lib/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/path/anaconda2/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/path/anaconda2/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/path/anaconda2/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
ValueError: Iteration of zero-sized operands is not enabled
```
is there any configuration I need to set up?

Thank you

**Comment by nipunbatra** [comment]
I think you'd need to set the interpreter corresponding to nilmtk-env in your IDE. See the screenshot below.
<img width="1280" alt="screenshot 2017-03-29 19 13 18" src="https://cloud.githubusercontent.com/assets/60985/24457452/f3230d94-14b3-11e7-87fc-c0d1e31ba455.png">

**Comment by lee813** [comment]
Great, it is working.
Thank you very much Nipun.
PS: A little suggestion, maybe you can write this into the dev guide, I think it will help the newbies in Python.

**Comment by nipunbatra** [comment]
Yes. That's a good suggestion. I have indeed just mentioned this in the guide.

**Comment by wangdan19941208** [comment]
i  am sorry,but i want to inquery about the process of Configuring the interpreter in your IDE to use nilmtk-env.thanks
