### ISSUE TITLE
Problem on activate environment

### ISSUE THREAD

**Issue by noravees** [nilmtk/nilmtk#561]
I'm using windows 10 64-bit.
After installed using "conda env create" command no error found.
But when run command "activate nilmtk-env" I got some error
```
D:\NILMTK>activate nilmtk-env
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: 874
Logged from file exceptions.py, line 574
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: 874
Logged from file exceptions.py, line 579
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: 874
Logged from file exceptions.py, line 580
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: 874
Logged from file exceptions.py, line 581
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: 874
Logged from file exceptions.py, line 582
```

I think this is a minor issue so I create Jupyter kernel and it completed.
But when I try to run ipython and import nilmtk I got error

```
(nilmtk-env) D:\NILMTK>ipython
Python 2.7.13 |Anaconda 4.3.1 (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import nilmtk
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-34c348a98f20> in <module>()
----> 1 import nilmtk

ImportError: No module named nilmtk
```

**Comment by nipunbatra** [comment]
Did this get resolved for you? I think the issue was the encoding for the command line?

```LookupError: unknown encoding: 874
Logged from file exceptions.py, line 582
```

**Comment by noravees** [comment]
I changed to install by developer method instead and it works.
Is it function the same?

**Comment by nipunbatra** [comment]
Yup. Functions the same way.
