### ISSUE TITLE
"conda env create" on Windows7

### ISSUE THREAD

**Issue by zhiweiSunday** [nilmtk/nilmtk#567]
I Used VM Windows 7 Ultimate x64.

I fllowed the guide：https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md

First，I downloaded the "Anaconda2-4.3.1-Windows-x86_64.exe(Python 2.7 version)” 
from https://www.continuum.io/downloads#windows and installed successfully

Second，I downloaded the appropriate version of VS C++ compiler for Python version.  from  https://www.microsoft.com/en-us/download/details.aspx?id=44266
it is also installed successfully.

After these,I downloaded the "environment.yml" from https://raw.githubusercontent.com/nilmtk/nilmtk/master/environment.yml

I scanned it maybe need Git.,So I installed Git-2.13.0-64-bit.exe

**When I command ”conda env create“** 

C:\Users\zhiwei\Desktop>conda env create
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: .
mkl-2017.0.1-0 100% |###############################| Time: 0:16:39 135.07 kB/s
python-2.7.13- 100% |###############################| Time: 0:01:13 340.41 kB/s
colorama-0.3.9 100% |###############################| Time: 0:00:00 476.17 kB/s
coverage-4.3.4 100% |###############################| Time: 0:00:00 331.75 kB/s
future-0.16.0- 100% |###############################| Time: 0:00:02 320.98 kB/s
ipython_genuti 100% |###############################| Time: 0:00:00 305.30 kB/s
numpy-1.12.1-p 100% |###############################| Time: 0:00:18 188.51 kB/s
path.py-10.3.1 100% |###############################| Time: 0:00:00 192.26 kB/s
pygments-2.2.0 100% |###############################| Time: 0:00:07 192.25 kB/s
pytz-2017.2-py 100% |###############################| Time: 0:00:00 199.36 kB/s
scandir-1.5-py 100% |###############################| Time: 0:00:00 256.48 kB/s
bottleneck-1.2 100% |###############################| Time: 0:00:00 218.40 kB/s
numexpr-2.6.2- 100% |###############################| Time: 0:00:00 217.12 kB/s
pathlib2-2.2.1 100% |###############################| Time: 0:00:00 489.95 kB/s
prompt_toolkit 100% |###############################| Time: 0:00:01 193.24 kB/s
qt-5.6.2-vc9_4   8% |##                             | Time: 0:00:35 137.36 kB/s

**A few minutes later,There are some error:**
Traceback (most recent call last):
  File "D:\Anaconda2\envs\nilmtk-env\Scripts\pip-script.py", line 3, in <module>

    import pip
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\pip\__init__.py", line 28
, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\pip\vcs\mercurial.py", li
ne 9, in <module>
    from pip.download import path_to_url
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\pip\download.py", line 37
, in <module>
    from pip.utils.ui import DownloadProgressBar, DownloadProgressSpinner
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\pip\utils\ui.py", line 57
, in <module>
    _BaseBar = _select_progress_class(IncrementalBar, Bar)
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\pip\utils\ui.py", line 50
, in _select_progress_class
    six.text_type().join(characters).encode(encoding)
LookupError: unknown encoding: cp65001
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : D:\Anaconda2  (writable)
    default environment : D:\Anaconda2
       envs directories : D:\Anaconda2\envs
                          C:\Users\zhiwei\AppData\Local\conda\conda\envs
                          C:\Users\zhiwei\.conda\envs
          package cache : D:\Anaconda2\pkgs
                          C:\Users\zhiwei\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Windows/7
Windows/6.1.7600

`$ D:\Anaconda2\Scripts\conda-env-script.py create`

    Traceback (most recent call last):
      File "D:\Anaconda2\lib\site-packages\conda\exceptions.py", line 573, in co
nda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\Anaconda2\lib\site-packages\conda_env\cli\main_create.py", line 1
08, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "D:\Anaconda2\lib\site-packages\conda_env\installers\pip.py", line 8,
 in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
      File "D:\Anaconda2\lib\site-packages\conda_env\pip_util.py", line 30, in p
ip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').spli
t()[1]
      File "D:\Anaconda2\lib\subprocess.py", line 219, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    CalledProcessError: Command '[u'D:\\Anaconda2\\envs\\nilmtk-env\\python.exe'
, u'D:\\Anaconda2\\envs\\nilmtk-env\\Scripts\\pip-script.py', '-V']' returned no
n-zero exit status 1

C:\Users\zhiwei\Desktop>

I don't know how to solve.

**Comment by zhiweiSunday** [comment]
**I have solved this problem.But now,it has a new problem :**
after command
python -m ipykernel install --user --name nilmtk-env --display-name "Python (nilmtk)"
the result:
Installed kernelspec nilmtk-env in C:\Users\zhiwei\AppData\Roaming\jupyter\kernels\nilmtk-env

**Finaly ,I Configured the interpreter in PyCHarm to use nilmtk-env**
**Running my project:
ImportError: No module named notebook.notebookapp**
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
Traceback (most recent call last):
  File "D:\Anaconda2\envs\nilmtk-env\Scripts\ipython-script.py", line 5, in <module>
    sys.exit(IPython.start_ipython())
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-110>", line 2, in initialize
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\terminal\ipapp.py", line 300, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\application.py", line 446, in initialize
    self.parse_command_line(argv)
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\terminal\ipapp.py", line 295, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\traitlets\config\application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\application.py", line 236, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\traitlets\config\application.py", line 445, in initialize_subcommand
    subapp = import_item(subapp)
  File "D:\Anaconda2\envs\nilmtk-env\lib\site-packages\ipython_genutils\importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])

**Comment by nipunbatra** [comment]
Please do the following

1. activate nilmtk-env
2. Install Jupyter `conda install jupyter`
3. Run Jupyter notebook- on command line write: `jupyter notebook`

**Comment by zhiweiSunday** [comment]
Many Thanks，it works well now.I’m truly grateful for your help.
