### ISSUE TITLE
error in tests_on_large_datasets

### ISSUE THREAD

**Issue by sirawichj** [nilmtk/nilmtk#577]
when I run the code it happened to be error in 
f1 = f1_score(disag_elec, elec)

the output shown : 

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pydev\pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/Sirawich/Desktop/learning_python/tests_on_large_datasets/redd_house3_f1_score.py", line 45, in <module>
    f1 = f1_score(disag_elec, elec)
  File "C:\Users\Sirawich\Anaconda2\lib\site-packages\nilmtk-0.2.1-py2.7.egg\nilmtk\metrics.py", line 225, in f1_score
    for aligned_states_chunk in aligned_meters:
  File "C:\Users\Sirawich\Anaconda2\lib\site-packages\nilmtk-0.2.1-py2.7.egg\nilmtk\electric.py", line 845, in align_two_meters
    yield pd.DataFrame({'master': master_chunk, 'slave': slave_chunk})
  File "C:\Users\Sirawich\Anaconda2\lib\site-packages\pandas\core\frame.py", line 266, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "C:\Users\Sirawich\Anaconda2\lib\site-packages\pandas\core\frame.py", line 402, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "C:\Users\Sirawich\Anaconda2\lib\site-packages\pandas\core\frame.py", line 5398, in _arrays_to_mgr
    index = extract_index(arrays)
  File "C:\Users\Sirawich\Anaconda2\lib\site-packages\pandas\core\frame.py", line 5446, in extract_index
    raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length

could you help me on this issue please 
Thank you so much

**Comment by nipunbatra** [comment]
I'd recommend you start with the documentation. This code isn't reflective
of the latest code.
