### ISSUE TITLE
Error finding F1 score 

### ISSUE THREAD

**Issue by suni9915** [nilmtk/nilmtk#592]
# In [15] :
print "Out [15] F1 score , FHMM :"
disag_filename = join(data_dir, fhmm_output_name)
disag = DataSet(disag_filename)
disag_elec = disag.buildings[building_number].elec
f1 = f1_score(disag_elec, elec)
f1.index = disag_elec.get_labels(f1.index)
plt.figure(5)
f1.plot(kind='barh')
plt.ylabel('appliance');
plt.xlabel('f-score');
plt.title("FHMM");
disag.store.close()

Out [15] F1 score , FHMM :
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.4\helpers\pydev\pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.4\helpers\pydev\pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/final project/nilmtk-master/nilmtk-master/6_fhmm_orig.py", line 218, in <module>
    f1 = f1_score(disag_elec, elec)
  File "D:/final project/nilmtk-master/nilmtk-master\nilmtk\metrics.py", line 225, in f1_score
    for aligned_states_chunk in aligned_meters:
  File "D:/final project/nilmtk-master/nilmtk-master\nilmtk\electric.py", line 846, in align_two_meters
    yield pd.DataFrame({'master': master_chunk, 'slave': slave_chunk})
  File "C:\Users\User\Anaconda2\lib\site-packages\pandas\core\frame.py", line 266, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "C:\Users\User\Anaconda2\lib\site-packages\pandas\core\frame.py", line 402, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "C:\Users\User\Anaconda2\lib\site-packages\pandas\core\frame.py", line 5398, in _arrays_to_mgr
    index = extract_index(arrays)
  File "C:\Users\User\Anaconda2\lib\site-packages\pandas\core\frame.py", line 5446, in extract_index
    raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length
Closing remaining open files:data/REDD/fhmm_disaggregate.h5...donedata/REDD/redd.h5...done

Process finished with exit code 1

I got this error when tried to find F1 score of fhmm using REDD dataset, building1 ,please help me solve this error.   Thank you.

**Comment by nipunbatra** [comment]
What documentation are you referring?
