### ISSUE TITLE
Multiple test failing on newer versions of libraries

### ISSUE THREAD

**Issue by nipunbatra** [nilmtk/nilmtk#629]
```
EEE.E..EEEEE..EEE..E.EE.E...E...EE.EE.......
======================================================================
ERROR: test_pipeline (nilmtk.stats.tests.test_dropoutrate.TestLocateGoodSections)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/stats/tests/test_dropoutrate.py", line 37, in test_pipeline
    dropout_rate.run()
  File "/Users/nipun/git/nilmtk/nilmtk/node.py", line 43, in run
    for _ in self.process():
  File "/Users/nipun/git/nilmtk/nilmtk/stats/dropoutrate.py", line 18, in process
    for chunk in self.upstream.process():
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/hdfdatastore.py", line 46, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_pipeline (nilmtk.stats.tests.test_locategoodsections.TestLocateGoodSections)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/stats/tests/test_locategoodsections.py", line 48, in test_pipeline
    good_sections.run()
  File "/Users/nipun/git/nilmtk/nilmtk/node.py", line 43, in run
    for _ in self.process():
  File "/Users/nipun/git/nilmtk/nilmtk/stats/goodsections.py", line 32, in process
    for chunk in self.upstream.process():
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/hdfdatastore.py", line 46, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_process_chunk (nilmtk.stats.tests.test_locategoodsections.TestLocateGoodSections)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/stats/tests/test_locategoodsections.py", line 74, in test_process_chunk
    locate._process_chunk(df, metadata)
  File "/Users/nipun/git/nilmtk/nilmtk/stats/goodsections.py", line 76, in _process_chunk
    self.results.append(timeframe, {'sections': [good_sections]})
  File "/Users/nipun/git/nilmtk/nilmtk/stats/goodsectionsresults.py", line 35, in append
    new_results['sections'] = [TimeFrameGroup(new_results['sections'][0])]
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_pipeline (nilmtk.stats.tests.test_totalenergy.TestEnergy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/stats/tests/test_totalenergy.py", line 54, in test_pipeline
    energy.run()
  File "/Users/nipun/git/nilmtk/nilmtk/node.py", line 43, in run
    for _ in self.process():
  File "/Users/nipun/git/nilmtk/nilmtk/stats/totalenergy.py", line 26, in process
    for chunk in self.upstream.process():
  File "/Users/nipun/git/nilmtk/nilmtk/preprocessing/clip.py", line 27, in process
    for chunk in self.upstream.process():
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/hdfdatastore.py", line 46, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_co_correctness (nilmtk.tests.test_combinatorial_optimisation.TestCO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_combinatorial_optimisation.py", line 27, in test_co_correctness
    co.train(elec)
  File "/Users/nipun/git/nilmtk/nilmtk/disaggregate/combinatorial_optimisation.py", line 79, in train
    chunk = next(power_series)
  File "/Users/nipun/git/nilmtk/nilmtk/electric.py", line 629, in load_series
    for chunk in generator:
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/hdfdatastore.py", line 46, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'
-------------------- >> begin captured stdout << ---------------------
Training model for submeter 'ElecMeter(instance=2, building=1, dataset=None, appliances=[])'

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_load (nilmtk.tests.test_datastore.TestCSVDataStore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_datastore.py", line 38, in test_load
    df = next(gen)
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/csvdatastore.py", line 59, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_load_chunks (nilmtk.tests.test_datastore.TestCSVDataStore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_datastore.py", line 48, in test_load_chunks
    for chunk in chunks:
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/csvdatastore.py", line 59, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_load_chunks_small_chunksize (nilmtk.tests.test_datastore.TestCSVDataStore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_datastore.py", line 87, in test_load_chunks_small_chunksize
    for i, chunk in enumerate(chunks):
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/csvdatastore.py", line 59, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_timeframe (nilmtk.tests.test_datastore.TestCSVDataStore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_datastore.py", line 22, in test_timeframe
    self.assertEqual(self.datastore.get_timeframe(key), self.TIMEFRAME)
  File "/Users/nipun/git/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/csvdatastore.py", line 228, in get_timeframe
    chunksize=MAX_MEM_ALLOWANCE_IN_BYTES)
  File "/Users/nipun/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/nipun/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/nipun/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 764, in __init__
    self._make_engine(self.engine)
  File "/Users/nipun/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 985, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/nipun/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1605, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas/_libs/parsers.c:8873)
FileNotFoundError: File b'/Users/nipun/git/nilmtk/data/random_csv/building1/elec/meter1.csv' does not exist

======================================================================
ERROR: test_load (nilmtk.tests.test_datastore.TestHDFDataStore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_datastore.py", line 38, in test_load
    df = next(gen)
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/hdfdatastore.py", line 46, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_load_chunks (nilmtk.tests.test_datastore.TestHDFDataStore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_datastore.py", line 48, in test_load_chunks
    for chunk in chunks:
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/hdfdatastore.py", line 46, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_load_chunks_small_chunksize (nilmtk.tests.test_datastore.TestHDFDataStore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_datastore.py", line 87, in test_load_chunks_small_chunksize
    for i, chunk in enumerate(chunks):
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/hdfdatastore.py", line 46, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: Failure: AttributeError (module 'pandas.tseries' has no attribute 'period')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/anaconda3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/nipun/anaconda3/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/nipun/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/nipun/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/nipun/anaconda3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/nipun/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_datastore_converter.py", line 15, in <module>
    convert_datastore(input_store, output_store)
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/datastore.py", line 240, in convert_datastore
    for df in input_store.load(meter_key):
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/hdfdatastore.py", line 46, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_proportion_of_energy (nilmtk.tests.test_elecmeter.TestElecMeter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_elecmeter.py", line 66, in test_proportion_of_energy
    self.assertEquals(meter.proportion_of_energy(meter), 1.0)
  File "/Users/nipun/git/nilmtk/nilmtk/electric.py", line 284, in proportion_of_energy
    good_other_sections = other.good_sections(**loader_kwargs)
  File "/Users/nipun/git/nilmtk/nilmtk/elecmeter.py", line 625, in good_sections
    nodes, results_obj, loader_kwargs)
  File "/Users/nipun/git/nilmtk/nilmtk/elecmeter.py", line 672, in _get_stat_from_cache_or_compute
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_total_energy (nilmtk.tests.test_elecmeter.TestElecMeter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_elecmeter.py", line 41, in test_total_energy
    energy = meter.total_energy()
  File "/Users/nipun/git/nilmtk/nilmtk/elecmeter.py", line 586, in total_energy
    nodes, TotalEnergy.results_class(), loader_kwargs)
  File "/Users/nipun/git/nilmtk/nilmtk/elecmeter.py", line 672, in _get_stat_from_cache_or_compute
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_fhmm_correctness (nilmtk.tests.test_fhmm.TestFHMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_fhmm.py", line 26, in test_fhmm_correctness
    fhmm.train(elec)
  File "/Users/nipun/git/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 269, in train
    meter_data = next(power_series).dropna()
  File "/Users/nipun/git/nilmtk/nilmtk/electric.py", line 629, in load_series
    for chunk in generator:
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/hdfdatastore.py", line 46, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'

======================================================================
ERROR: test_dual_supply (nilmtk.tests.test_metergroup.TestMeterGroup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_metergroup.py", line 95, in test_dual_supply
    self.assertEqual(mg['washer dryer'].total_energy()['active'],
  File "/Users/nipun/git/nilmtk/nilmtk/metergroup.py", line 829, in total_energy
    load_kwargs, 'total_energy', full_results)
  File "/Users/nipun/git/nilmtk/nilmtk/metergroup.py", line 845, in _collect_stats_on_all_meters
    **load_kwargs)
  File "/Users/nipun/git/nilmtk/nilmtk/elecmeter.py", line 586, in total_energy
    nodes, TotalEnergy.results_class(), loader_kwargs)
  File "/Users/nipun/git/nilmtk/nilmtk/elecmeter.py", line 672, in _get_stat_from_cache_or_compute
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'
-------------------- >> begin captured stdout << ---------------------
Calculating total_energy for ElecMeterID(instance=1, building=1, dataset='REDD') ...   
--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_load (nilmtk.tests.test_metergroup.TestMeterGroup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_metergroup.py", line 141, in test_load
    df = next(elec.load())
  File "/Users/nipun/git/nilmtk/nilmtk/metergroup.py", line 686, in load
    index, columns, self.meters, kwargs)
  File "/Users/nipun/git/nilmtk/nilmtk/metergroup.py", line 1738, in combine_chunks_from_generators
    chunk_from_next_meter = next(generator)
  File "/Users/nipun/git/nilmtk/nilmtk/preprocessing/apply.py", line 14, in process
    for chunk in self.upstream.process():
  File "/Users/nipun/git/nilmtk/nilmtk/datastore/hdfdatastore.py", line 46, in load
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'
-------------------- >> begin captured stdout << ---------------------
Loading data for meter ElecMeterID(instance=1, building=1, dataset=None)     
--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_proportion_of_energy_submetered (nilmtk.tests.test_metergroup.TestMeterGroup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_metergroup.py", line 78, in test_proportion_of_energy_submetered
    self.assertEqual(mg.proportion_of_energy_submetered(), 1.0)
  File "/Users/nipun/git/nilmtk/nilmtk/metergroup.py", line 1046, in proportion_of_energy_submetered
    downstream_meters = self.meters_directly_downstream_of_mains()
  File "/Users/nipun/git/nilmtk/nilmtk/metergroup.py", line 793, in meters_directly_downstream_of_mains
    meters = nodes_adjacent_to_root(self.wiring_graph())
  File "/Users/nipun/git/nilmtk/nilmtk/utils.py", line 91, in nodes_adjacent_to_root
    root = tree_root(graph)
  File "/Users/nipun/git/nilmtk/nilmtk/utils.py", line 80, in tree_root
    roots = [node for node, in_degree in graph.in_degree_iter()
AttributeError: 'DiGraph' object has no attribute 'in_degree_iter'
-------------------- >> begin captured stdout << ---------------------
Running MeterGroup.proportion_of_energy_submetered...

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_total_energy (nilmtk.tests.test_metergroup.TestMeterGroup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_metergroup.py", line 132, in test_total_energy
    ds.buildings[1].elec.total_energy()
  File "/Users/nipun/git/nilmtk/nilmtk/metergroup.py", line 829, in total_energy
    load_kwargs, 'total_energy', full_results)
  File "/Users/nipun/git/nilmtk/nilmtk/metergroup.py", line 845, in _collect_stats_on_all_meters
    **load_kwargs)
  File "/Users/nipun/git/nilmtk/nilmtk/elecmeter.py", line 586, in total_energy
    nodes, TotalEnergy.results_class(), loader_kwargs)
  File "/Users/nipun/git/nilmtk/nilmtk/elecmeter.py", line 672, in _get_stat_from_cache_or_compute
    sections = TimeFrameGroup(sections)
  File "/Users/nipun/git/nilmtk/nilmtk/timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: module 'pandas.tseries' has no attribute 'period'
-------------------- >> begin captured stdout << ---------------------
Calculating total_energy for ElecMeterID(instance=1, building=1, dataset=None) ...   
--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_wiring_graph (nilmtk.tests.test_metergroup.TestMeterGroup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nipun/git/nilmtk/nilmtk/tests/test_metergroup.py", line 65, in test_wiring_graph
    self.assertEqual(mg.meters_directly_downstream_of_mains().meters, [meter2])
  File "/Users/nipun/git/nilmtk/nilmtk/metergroup.py", line 793, in meters_directly_downstream_of_mains
    meters = nodes_adjacent_to_root(self.wiring_graph())
  File "/Users/nipun/git/nilmtk/nilmtk/utils.py", line 91, in nodes_adjacent_to_root
    root = tree_root(graph)
  File "/Users/nipun/git/nilmtk/nilmtk/utils.py", line 80, in tree_root
    roots = [node for node, in_degree in graph.in_degree_iter()
AttributeError: 'DiGraph' object has no attribute 'in_degree_iter'

----------------------------------------------------------------------
Ran 44 tests in 2.799s

FAILED (errors=21)
Closing remaining open files:/Users/nipun/git/nilmtk/data/energy.h5...done/Users/nipun/git/nilmtk/data/co_test.h5...done/Users/nipun/git/nilmtk/data/random.h5...donedata/random.h5...done
```

**Comment by PMeira** [comment]
I forked the repo to upload some changes I made some months ago to use all recent versions of the dependencies. Most changes are simply due to API changes. All nosetests pass with it but I didn't test it further. 

Since I saw the notice that NILMTK is not being actively developed anymore, I won't make a pull request yet, but it's in https://github.com/PMeira/nilmtk

**Comment by oliparson** [comment]
Great work! I'm very happy to merge a PR if Nipun doesn't have time to review it :)

**Comment by PMeira** [comment]
Oh, nice! I'm going to create the PR in a sec.

**Comment by PMeira** [comment]
Closing this one as the PR was merged.
