### ISSUE TITLE
export_model creates error saying unable to pickle

### ISSUE THREAD

**Issue by SrivathshanKS** [nilmtk/nilmtk#639]
Hi 

I was using niltk CombinatorialOptimization with REDD dataset.  When I try to export(using export_model) the model or pickle the model object to save as a file I find some error. Please find the trace below. Please check and help me understand the problem I am facing.

Traceback (most recent call last):
  File "pert_redd_co_train.py", line 28, in <module>
    clf.train(top_5_train_elec, sample_period=sample_period)
  File "/home/ec2-user/pert/nilmtk/disaggregate/combinatorial_optimisation.py",  line 103, in train
    self.export_model("co_model")
  File "/home/ec2-user/pert/nilmtk/disaggregate/combinatorial_optimisation.py",  line 281, in export_model
    exported_model = copy.deepcopy(self)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 19 0, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 33 4, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 25 7, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 23 0, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 25 7, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 19 0, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 33 4, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 25 7, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 19 0, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 33 4, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 25 7, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 19 0, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 33 4, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 25 7, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 19 0, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 33 4, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 23 7, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 25 7, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 19 0, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 33 4, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 25 7, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 19 0, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 33 4, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 23 7, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 23 0, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 19 0, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 33 4, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 23 7, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
 File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 16 3, in deepcopy
    y = copier(x, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 25 7, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ec2-user/anaconda3/envs/nilmtk-env/lib/python2.7/copy.py", line 18 2, in deepcopy
    rv = reductor(2)
  File "stringsource", line 2, in tables.lrucacheextension.ObjectCache.__reduce_ cython__
TypeError: self.ratimes,self.rsizes cannot be converted to a Python object for p ickling
Closing remaining open files:/home/ec2-user/pert/redd.h5...done

I dont understand what these objects (self.ratimes,self.rsizes) are as I dont see them in the nilmtk source also I dont have any such occurrence in mine

**Comment by nipunbatra** [comment]
Please can you provide minimal complete example to help reproduce this bug?

**Comment by PMeira** [comment]
Here's a modified runnable example:

```python
from nilmtk import DataSet
from nilmtk.disaggregate import CombinatorialOptimisation

train = DataSet('/data/REDD/redd.h5')
train.set_window(end="30-04-2011")
train_elec = train.buildings[1].elec
top_5_train_elec = train_elec.submeters().select_top_k(k=5) 
sample_period = 120

clf = CombinatorialOptimisation()
clf.train(top_5_train_elec, sample_period=sample_period)
clf.export_model("model")

clf2 = CombinatorialOptimisation()
clf2.import_model("model")
```

I'm testing again and should commit the fix soon. This error was a side effect of changes in pytables.
