### ISSUE TITLE
Selecting top 5 appliances-TypeError()

### ISSUE THREAD

**Issue by metwebber** [nilmtk/nilmtk#647]
I am using iawe dataset to run codes of nilmtk. Everything before "selecting top 5 appliances" work well. However, when I run;
top_5_train_elec = train_elec.submeters().select_top_k(k=5)
It gives the error:

top_5_train_elec = train_elec.submeters().select_top_k(k=5)
10/10 ElecMeter(instance=12, building=1, dataset='iAWE', appliances=[Appliance(type='motor', instance=1)])ce=1)]))Traceback (most recent call last):

  File "<ipython-input-59-5438c0269107>", line 1, in <module>
    top_5_train_elec = train_elec.submeters().select_top_k(k=5)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.py", line 1303, in select_top_k
    top_k_metergroup = self.from_list(top_k_elec_meter_ids)

  File "C:\Users\dilan.agkoc\AppData\Local\Continuum\anaconda2\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.py", line 425, in from_list
    append_meter_group(meter_id)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.py", line 415, in append_meter_group
    metergroup = self.from_list(meter_id.meters)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.py", line 427, in from_list
    raise TypeError()

TypeError

Can you please help me?

**Comment by nipunbatra** [comment]
Can you provide a minimal working example? Can you also please format it here using Github markdown formatting?

**Comment by PMeira** [comment]
Somewhere along the way, the `ElecMeterID` namedtuple info is being dropped and a normal tuple is left. Funny that it doesn't happen with all datasets though.

I can't track it right now but I tested a simple workaround that works without breaking any test. We really need to investigate the root cause though. I'll make a PR soon.

**Comment by metwebber** [comment]
Thank you @PMeira, I am waiting for your news.

And do you know other datasets open to public? Maybe I can try with different datasets for now if it is working.

**Comment by PMeira** [comment]
@metwebber [One of the tests](https://github.com/nilmtk/nilmtk/blob/master/tests_on_large_datasets/redd_house3_f1_score.py) uses the [REDD dataset](http://redd.csail.mit.edu/) and that runs fine -- for the official download you need to request a password though. 

If you want to give it a try, you can grab the metergroup.py with a workaround for the issue [here](https://github.com/PMeira/nilmtk/blob/7d609c4c2acb8ddd9b26276213f4ab2b77eb39fd/nilmtk/metergroup.py).

I'll try to test some other datasets in a few days.

**Comment by metwebber** [comment]
I have requested for a password to reach REDD dataset but they did not still send it. 

Also, I have another problem about disaggregation. If you can  also look at it, I will be so glad.

https://github.com/nilmtk/nilmtk/issues/652

**Comment by PMeira** [comment]
@metwebber Hey, did they ever reply about the REDD password?

**Comment by PMeira** [comment]
@metwebber Since apparently it's been listed online in multiple places for a couple of years, might as well give you a link (slide 29): https://www.cse.iitb.ac.in/~cs620/disaggregation

**Comment by metwebber** [comment]
Thank you so much @PMeira, I'll now try algorithms with REDD dataset.
