### ISSUE TITLE
ValueError: 'covars' must be symmetric, positive-definite

### ISSUE THREAD

**Issue by metwebber** [nilmtk/nilmtk#649]
I am getting "ValueError: 'covars' must be symmetric, positive-definite" while trying to train IAWE dataset.  Do you know what the reason is?

fhmm.train(train_elec, sample_period= 60)
Training model for submeter 'ElecMeter(instance=3, building=1, dataset='iAWE', appliances=[Appliance(type='fridge', instance=1)])'
Training model for submeter 'ElecMeter(instance=4, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=1)])'
Training model for submeter 'ElecMeter(instance=5, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=2)])'
Training model for submeter 'ElecMeter(instance=6, building=1, dataset='iAWE', appliances=[Appliance(type='washing machine', instance=1)])'
Training model for submeter 'ElecMeter(instance=7, building=1, dataset='iAWE', appliances=[Appliance(type='computer', instance=1)])'
Training model for submeter 'ElecMeter(instance=8, building=1, dataset='iAWE', appliances=[Appliance(type='clothes iron', instance=1)])'
Training model for submeter 'ElecMeter(instance=9, building=1, dataset='iAWE', appliances=[Appliance(type='unknown', instance=1)])'
Training model for submeter 'ElecMeter(instance=10, building=1, dataset='iAWE', appliances=[Appliance(type='television', instance=1)])'
Training model for submeter 'ElecMeter(instance=11, building=1, dataset='iAWE', appliances=[Appliance(type='wet appliance', instance=1)])'
Training model for submeter 'ElecMeter(instance=12, building=1, dataset='iAWE', appliances=[Appliance(type='motor', instance=1)])'
Traceback (most recent call last):

  File "<ipython-input-88-14f4493ec8b7>", line 1, in <module>
    fhmm.train(train_elec, sample_period= 60)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\envs\nilmtk-env\lib\site-packages\nilmtk\disaggregate\fhmm_exact.py", line 287, in train
    learnt_model[meter].fit([X])

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\hmmlearn\hmm.py", line 328, in fit
    return super(GaussianHMM, self).fit(obs)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\hmmlearn\base.py", line 377, in fit
    framelogprob = self._compute_log_likelihood(seq)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\hmmlearn\hmm.py", line 185, in _compute_log_likelihood
    obs, self._means_, self._covars_, self._covariance_type)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\utils\deprecation.py", line 78, in wrapped
    return fun(*args, **kwargs)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\mixture\gmm.py", line 72, in log_multivariate_normal_density
    X, means, covars)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\mixture\gmm.py", line 735, in _log_multivariate_normal_density_full
    raise ValueError("'covars' must be symmetric, "

ValueError: 'covars' must be symmetric, positive-definite

**Comment by nipunbatra** [comment]
@metwebber 

1. can you please format your code in the issue using Github markdown?
1. can you please provide the minimal code to replicate this bug?

**Comment by metwebber** [comment]
Sorry @nipunbatra 
Here is my full code;

`

import numpy as np

import pandas as pd

from os.path import join

import matplotlib.pyplot as plt

import nilmtk

# Loading the data
iawe = DataSet('nilmtk-m/nilmtk-master/data/iawe.h5')

train = DataSet('nilmtk-m/nilmtk-master/data/iawe.h5')

test = DataSet('nilmtk-m/nilmtk-master/data/iawe.h5')

# Analyzing the data
print(iawe.buildings)
OrderedDict([(1, Building(instance=1, dataset='iAWE'))])

print(iawe.buildings[1].metadata)
{'instance': 1, 'dataset': 'iAWE', 'original_name': 'house_1'}

elec = iawe.buildings[1].elec

elec
Out[137]: 
MeterGroup(meters=
  ElecMeter(instance=1, building=1, dataset='iAWE', site_meter, appliances=[])
  ElecMeter(instance=2, building=1, dataset='iAWE', site_meter, appliances=[])
  ElecMeter(instance=3, building=1, dataset='iAWE', appliances=[Appliance(type='fridge', instance=1)])
  ElecMeter(instance=4, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=1)])
  ElecMeter(instance=5, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=2)])
  ElecMeter(instance=6, building=1, dataset='iAWE', appliances=[Appliance(type='washing machine', instance=1)])
  ElecMeter(instance=7, building=1, dataset='iAWE', appliances=[Appliance(type='computer', instance=1)])
  ElecMeter(instance=8, building=1, dataset='iAWE', appliances=[Appliance(type='clothes iron', instance=1)])
  ElecMeter(instance=9, building=1, dataset='iAWE', appliances=[Appliance(type='unknown', instance=1)])
  ElecMeter(instance=10, building=1, dataset='iAWE', appliances=[Appliance(type='television', instance=1)])
  ElecMeter(instance=11, building=1, dataset='iAWE', appliances=[Appliance(type='wet appliance', instance=1)])
  ElecMeter(instance=12, building=1, dataset='iAWE', appliances=[Appliance(type='motor', instance=1)])
)

elec.appliances
Out[138]: 
[Appliance(type='fridge', instance=1),
 Appliance(type='unknown', instance=1),
 Appliance(type='washing machine', instance=1),
 Appliance(type='clothes iron', instance=1),
 Appliance(type='television', instance=1),
 Appliance(type='wet appliance', instance=1),
 Appliance(type='air conditioner', instance=1),
 Appliance(type='air conditioner', instance=2),
 Appliance(type='motor', instance=1),
 Appliance(type='computer', instance=1)]

elec.mains()
Out[139]: 
MeterGroup(meters=
  ElecMeter(instance=1, building=1, dataset='iAWE', site_meter, appliances=[])
  ElecMeter(instance=2, building=1, dataset='iAWE', site_meter, appliances=[])
)

elec.mains().power_series_all_data().head()
Loading data for meter ElecMeterID(instance=1, building=1, dataset='iAWE')     

Loading data for meter ElecMeterID(instance=2, building=1, dataset='iAWE')     

Done loading data all meters for this chunk.
Out[140]: 
2013-05-24 05:30:00+05:30    282.744995
2013-05-24 05:30:01+05:30    288.757996
2013-05-24 05:30:02+05:30    288.757996
2013-05-24 05:30:03+05:30    297.394012
2013-05-24 05:30:04+05:30    303.722992
Name: (power, active), dtype: float32Out[141]: 
MeterGroup(meters=
  ElecMeter(instance=3, building=1, dataset='iAWE', appliances=[Appliance(type='fridge', instance=1)])
  ElecMeter(instance=4, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=1)])
  ElecMeter(instance=5, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=2)])
  ElecMeter(instance=6, building=1, dataset='iAWE', appliances=[Appliance(type='washing machine', instance=1)])
  ElecMeter(instance=7, building=1, dataset='iAWE', appliances=[Appliance(type='computer', instance=1)])
  ElecMeter(instance=8, building=1, dataset='iAWE', appliances=[Appliance(type='clothes iron', instance=1)])
  ElecMeter(instance=9, building=1, dataset='iAWE', appliances=[Appliance(type='unknown', instance=1)])
  ElecMeter(instance=10, building=1, dataset='iAWE', appliances=[Appliance(type='television', instance=1)])
  ElecMeter(instance=11, building=1, dataset='iAWE', appliances=[Appliance(type='wet appliance', instance=1)])
  ElecMeter(instance=12, building=1, dataset='iAWE', appliances=[Appliance(type='motor', instance=1)])
)

mains.available_ac_types('power')
Out[143]: ['active', 'reactive', 'apparent']

elec.submeters().available_ac_types('power')
Out[144]: ['active', 'reactive', 'apparent']

elec.mains().total_energy() # returns kWh
Calculating total_energy for ElecMeterID(instance=2, building=1, dataset='iAWE') ...   Out[145]: 
active      1366.069880
reactive     127.476065
apparent    1430.854277
dtype: float64

energy_per_meter = elec.submeters().energy_per_meter() # kWh, again
10/10 ElecMeter(instance=12, building=1, dataset='iAWE', appliances=[Appliance(type='motor', instance=1)])ce=1)]))

energy_per_meter
Out[147]: 
          (3, 1, iAWE)  (4, 1, iAWE)  (5, 1, iAWE)  (6, 1, iAWE)  \
active       82.958385    203.569523    203.889213      2.152638   
apparent           NaN           NaN           NaN           NaN   
reactive           NaN           NaN           NaN           NaN   

          (7, 1, iAWE)  (8, 1, iAWE)  (9, 1, iAWE)  (10, 1, iAWE)  \
active       24.351512      0.885766      0.722616      11.495919   
apparent           NaN           NaN           NaN            NaN   
reactive           NaN           NaN           NaN            NaN   

          (11, 1, iAWE)  (12, 1, iAWE)  
active         0.558717       1.067078  
apparent            NaN            NaN  
reactive            NaN            NaN  

fridge = elec['fridge']

print (fridge)
ElecMeter(instance=3, building=1, dataset='iAWE', appliances=[Appliance(type='fridge', instance=1)])

df = next(fridge.load())

print (df.head())
physical_quantity         current    power  frequency     voltage    power  \
type                              apparent                        reactive   
2013-06-07 05:30:00+05:30   0.011    2.486  50.070000  235.070007    2.483   
2013-06-07 05:30:01+05:30   0.011    2.555  50.080002  235.020004    2.547   
2013-06-07 05:30:02+05:30   0.011    2.485  50.080002  234.979996    2.480   
2013-06-07 05:30:03+05:30   0.010    2.449  50.060001  235.000000    2.444   
2013-06-07 05:30:04+05:30   0.011    2.519  50.060001  234.949997    2.510   

physical_quantity                 
type                      active  
2013-06-07 05:30:00+05:30  0.111  
2013-06-07 05:30:01+05:30  0.200  
2013-06-07 05:30:02+05:30  0.152  
2013-06-07 05:30:03+05:30  0.159  
2013-06-07 05:30:04+05:30  0.215  

# Train and Test
train.set_window(end="2013-08-05")

test.set_window(start="2013-08-05")

train_elec = train.buildings[1].elec

test_elec = test.buildings[1].elec


fridge_meter = train_elec['fridge']

fridge_df = next(fridge_meter.load())

fridge_df.head()
Out[176]: 
physical_quantity         current    power  frequency     voltage    power  \
type                              apparent                        reactive   
2013-06-07 05:30:00+05:30   0.011    2.486  50.070000  235.070007    2.483   
2013-06-07 05:30:01+05:30   0.011    2.555  50.080002  235.020004    2.547   
2013-06-07 05:30:02+05:30   0.011    2.485  50.080002  234.979996    2.480   
2013-06-07 05:30:03+05:30   0.010    2.449  50.060001  235.000000    2.444   
2013-06-07 05:30:04+05:30   0.011    2.519  50.060001  234.949997    2.510   

physical_quantity                 
type                      active  
2013-06-07 05:30:00+05:30  0.111  
2013-06-07 05:30:01+05:30  0.200  
2013-06-07 05:30:02+05:30  0.152  
2013-06-07 05:30:03+05:30  0.159  
2013-06-07 05:30:04+05:30  0.215  

mains = train_elec.mains()

mains_df = next(mains.load())
Loading data for meter ElecMeterID(instance=2, building=1, dataset='iAWE')     
Done loading data all meters for this chunk.

mains_df.head()
Out[179]: 
physical_quantity         current       power power factor       power  \
type                          NaN    apparent          NaN      active   
2013-05-24 05:30:00+05:30     NaN  295.160004          NaN  282.744995   
2013-05-24 05:30:01+05:30     NaN  307.010010          NaN  288.757996   
2013-05-24 05:30:02+05:30     NaN  307.010010          NaN  288.757996   
2013-05-24 05:30:03+05:30     NaN  313.783997          NaN  297.394012   
2013-05-24 05:30:04+05:30     NaN  324.006012          NaN  303.722992   

physical_quantity          voltage      power frequency  
type                      apparent   reactive  apparent  
2013-05-24 05:30:00+05:30      NaN -52.148102       NaN  
2013-05-24 05:30:01+05:30      NaN -59.433601       NaN  
2013-05-24 05:30:02+05:30      NaN -59.433601       NaN  
2013-05-24 05:30:03+05:30      NaN -48.224499       NaN  
2013-05-24 05:30:04+05:30      NaN -55.869999       NaN  

fridge_meter.device
Out[180]: 
{'description': None,
 'max_sample_period': 300,
 'measurements': [{'lower_limit': 0,
   'physical_quantity': 'power',
   'type': 'active',
   'upper_limit': 10000},
  {'lower_limit': 0,
   'physical_quantity': 'power',
   'type': 'apparent',
   'upper_limit': 10000},
  {'lower_limit': 0,
   'physical_quantity': 'power',
   'type': 'reactive',
   'upper_limit': 10000},
  {'lower_limit': 0,
   'physical_quantity': 'frequency',
   'type': None,
   'upper_limit': 70},
  {'lower_limit': 0,
   'physical_quantity': 'voltage',
   'type': None,
   'upper_limit': 270},
  {'lower_limit': 0,
   'physical_quantity': 'current',
   'type': None,
   'upper_limit': 100},
  {'lower_limit': 0,
   'physical_quantity': 'power factor',
   'type': None,
   'upper_limit': 1}],
 'sample_period': 1,
 'wireless': True}

# Training
start = time.time()

fhmm = fhmm_exact.FHMM()

fhmm.train(train_elec, sample_period= 60)
Training model for submeter 'ElecMeter(instance=3, building=1, dataset='iAWE', appliances=[Appliance(type='fridge', instance=1)])'
Training model for submeter 'ElecMeter(instance=4, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=1)])'
Training model for submeter 'ElecMeter(instance=5, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=2)])'
Training model for submeter 'ElecMeter(instance=6, building=1, dataset='iAWE', appliances=[Appliance(type='washing machine', instance=1)])'
Training model for submeter 'ElecMeter(instance=7, building=1, dataset='iAWE', appliances=[Appliance(type='computer', instance=1)])'
Training model for submeter 'ElecMeter(instance=8, building=1, dataset='iAWE', appliances=[Appliance(type='clothes iron', instance=1)])'
Training model for submeter 'ElecMeter(instance=9, building=1, dataset='iAWE', appliances=[Appliance(type='unknown', instance=1)])'
Training model for submeter 'ElecMeter(instance=10, building=1, dataset='iAWE', appliances=[Appliance(type='television', instance=1)])'
Training model for submeter 'ElecMeter(instance=11, building=1, dataset='iAWE', appliances=[Appliance(type='wet appliance', instance=1)])'
Training model for submeter 'ElecMeter(instance=12, building=1, dataset='iAWE', appliances=[Appliance(type='motor', instance=1)])'
Traceback (most recent call last):

  File "<ipython-input-191-14f4493ec8b7>", line 1, in <module>
    fhmm.train(train_elec, sample_period= 60)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\envs\nilmtk-env\lib\site-packages\nilmtk\disaggregate\fhmm_exact.py", line 288, in train
    learnt_model[meter].fit([X])

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\hmmlearn\hmm.py", line 328, in fit
    return super(GaussianHMM, self).fit(obs)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\hmmlearn\base.py", line 377, in fit
    framelogprob = self._compute_log_likelihood(seq)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\hmmlearn\hmm.py", line 185, in _compute_log_likelihood
    obs, self._means_, self._covars_, self._covariance_type)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\utils\deprecation.py", line 78, in wrapped
    return fun(*args, **kwargs)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\mixture\gmm.py", line 72, in log_multivariate_normal_density
    X, means, covars)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\mixture\gmm.py", line 735, in _log_multivariate_normal_density_full
    try:

ValueError: 'covars' must be symmetric, positive-definite`

**Comment by nipunbatra** [comment]
Please can you format the code. See: https://guides.github.com/features/mastering-markdown/

Example:

```python
import time
```

**Comment by PMeira** [comment]
@metwebber I edited your post to reformat it.

I tested the following minimal example and it didn't raise any errors with the current version (not sure if I fixed it accidentally through other commits):

```python
from nilmtk import DataSet
from nilmtk.disaggregate import fhmm_exact

train = DataSet('/data/iawe/iawe.h5')
train.set_window(end="2013-08-05")
train_elec = train.buildings[1].elec
fhmm = fhmm_exact.FHMM()
fhmm.train(train_elec, sample_period=60)
```

Can you confirm it's working for you now?

**Comment by PMeira** [comment]
As usual, closing due to inactivity and no feedback. The issue seems to be fixed but feel free to reopen if anything pops ups.
