### ISSUE TITLE
HDF5ExtError: HDF5 error back trace

### ISSUE THREAD

**Issue by walidsliti** [nilmtk/nilmtk#663]
hello i'm trying to run this tuto  https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb

But when i'm trying to split the data i got this error 

```
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-10-2b8825b7e2a7> in <module>()
----> 1 train = DataSet('/home/ubuntu/nilmtk/data/REDD/low_freq/redd.h5')
      2 test = DataSet('/home/ubuntu/nilmtk/data/REDD/low_freq/redd.h5')

/home/ubuntu/nilmtk/nilmtk/dataset.pyc in __init__(self, filename, format)
     44         self.metadata = {}
     45         if filename is not None:
---> 46             self.import_metadata(get_datastore(filename, format))
     47 
     48     def import_metadata(self, store):

/home/ubuntu/nilmtk/nilmtk/utils.pyc in get_datastore(filename, format, mode)
    319     if filename is not None:
    320         if format == 'HDF':
--> 321             return HDFDataStore(filename, mode)
    322         elif format == 'CSV':
    323             return CSVDataStore(filename)

/home/ubuntu/nilmtk/nilmtk/docinherit.pyc in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__', '__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

/home/ubuntu/nilmtk/nilmtk/datastore/hdfdatastore.pyc in __init__(self, filename, mode)
     20         if mode == 'a' and not isfile(filename):
     21             raise IOError("No such file as " + filename)
---> 22         self.store = pd.HDFStore(filename, mode, complevel=9, complib='blosc')
     23         super(HDFDataStore, self).__init__()
     24 

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/pandas/io/pytables.pyc in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    465         self._fletcher32 = fletcher32
    466         self._filters = None
--> 467         self.open(mode=mode, **kwargs)
    468 
    469     def __fspath__(self):

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/pandas/io/pytables.pyc in open(self, mode, **kwargs)
    578 
    579         try:
--> 580             self._handle = tables.open_file(self._path, self._mode, **kwargs)
    581         except (IOError) as e:  # pragma: no cover
    582             if 'can not be written' in str(e):

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/tables/file.pyc in open_file(filename, mode, title, root_uep, filters, **kwargs)
    318 
    319     # Finally, create the File instance, and return it
--> 320     return File(filename, mode, title, root_uep, filters, **kwargs)
    321 
    322 

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/tables/file.pyc in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
    782 
    783         # Now, it is time to initialize the File extension
--> 784         self._g_new(filename, mode, **params)
    785 
    786         # Check filters and set PyTables format version for new files.

tables/hdf5extension.pyx in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 586, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1305, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1839, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 940, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/home/ubuntu/nilmtk/data/REDD/low_freq/redd.h5'
```

![image](https://user-images.githubusercontent.com/26322476/39182907-3b9433ec-47b6-11e8-8e6a-24e57ce90b3d.png)

and this is the code 
![image](https://user-images.githubusercontent.com/26322476/39183024-8e909bf8-47b6-11e8-9dad-a8a2704ae75c.png)
any idea ?

(EDIT BY @PMeira: formatting -- use triple backticks for multi-line code/output blocks)

**Comment by PMeira** [comment]
Assuming you have previously successfully converted the REDD dataset into `/home/ubuntu/nilmtk/data/REDD/low_freq/redd.h5`, looks like the HDF5 files is locked by another process. Try closing extra processes (including extra Jupyter notebook kernels) that could be have a lock on the file.

**Comment by kimhongsu** [comment]
I have the same issue. 
As far as I know, get_datastore() of __init__() in DataSet class opens dataset as "append mode" by default. If it was a "read mode" or have an option argument to change to a "read mode", there was no problem even though an user opens REDD datasets simultaneously in the Jupyter notebooks.
