### ISSUE TITLE
F1-score

### ISSUE THREAD

**Issue by walidsliti** [nilmtk/nilmtk#678]
is this code valid only for house 3 ? and why ? 

https://github.com/nilmtk/nilmtk/blob/master/tests_on_large_datasets/redd_house3_f1_score.py

how can i make it for other houses ?

**Comment by walidsliti** [comment]
hi @PMeira @nipunbatra 
 do you have any ideas guys ?
thx

**Comment by PMeira** [comment]
@walidsliti Unless I'm missing something, it should work fine for other houses. Just tested it with house 1.

You can make a copy of that script and customize the parameters on the begging of the file:
```python
data_dir = '/data/REDD'
building_number = 3
```

Especially, change the `building_number` to the one corresponding to the desired house. 
You can check the metadata for more info, either by inspecting the dataset object or the original YAML files on its converter folder.

**Comment by walidsliti** [comment]
but i got this error 
ValueError: cannot reindex a non-unique index with a method or limit

**Comment by PMeira** [comment]
I can try to reproduce that. Which building?

**Comment by walidsliti** [comment]
any builduig except building number 3

**Comment by PMeira** [comment]
@walidsliti I just pushed a fix on 852382b for this specific resampling issue. I'd suggest updating to the latest revision and trying again.

**Comment by EliseBcm** [comment]
@PMeira I changed electric.py according to your fix [85232b](https://github.com/nilmtk/nilmtk/commit/852382ba5145476f750e0b120301f6515affd5fe), but I still got an error with with the training with REFIT data (top 5 appliances of building 1), with these settings  : 
```
train.set_window(end="2015-1-01")
test.set_window(start="2015-01-01", end="2015-06-01")
# Type of data to disaggregate
physical_quantity = 'power'
ac_type = 'active'
```
The error : 

```
Traceback (most recent call last):
  File "~/nilmtk_work/disaggregationTestsREFIT_new.py", line 84, in <module>
    clf.train(top_5_train_elec, sample_period=sp, physical_quantity=physical_quantity, ac_type=ac_type)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\disaggregate\combinatorial_optimisation.py", line 80, in train
    chunk = next(power_series)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\electric.py", line 629, in load_series
    for chunk in generator:
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\preprocessing\apply.py", line 15, in process
    new_chunk = self.func(chunk)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\electric.py", line 145, in resample_func
    return safe_resample(df, **resample_kwargs)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\utils.py", line 424, in safe_resample
    data = _resample_chain(data, resample_kwargs)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\utils.py", line 420, in _resample_chain
    return how(fill_method(data.resample(rule, **resample_kwargs)))
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\utils.py", line 407, in <lambda>
    fill_method = lambda df: getattr(df, fill_method_str)()
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\resample.py", line 471, in pad
    return self._upsample('pad', limit=limit)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\resample.py", line 820, in _upsample
    limit=limit, fill_value=fill_value)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\util\_decorators.py", line 127, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py", line 2935, in reindex
    return super(DataFrame, self).reindex(**kwargs)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\generic.py", line 3023, in reindex
    fill_value, copy).__finalize__(self)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py", line 2870, in _reindex_axes
    fill_value, limit, tolerance)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py", line 2878, in _reindex_index
    tolerance=tolerance)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\indexes\base.py", line 2993, in reindex
    raise ValueError("cannot reindex a non-unique index "
ValueError: cannot reindex a non-unique index with a method or limit
```

**Comment by walidsliti** [comment]
@PMeira thanks it works now for houses 3,4,5 and 6  but not with houses number 1 and 2

**Comment by PMeira** [comment]
@walidsliti With REDD, houses 1 and 2 always worked fine for me. I'll reconvert and retest when I have some more time.

@EliseBcm I'll check with REFIT later, the converter still needs to be fixed before I can do that. Please note that code snippets don't add much value for the investigation, we need full running examples to reproduce issues and save time in general.

**Comment by EliseBcm** [comment]
@PMeira Thank you for your answers ! And sorry, I should have precised that I am using the same code as in nilmtk/docs/manual/user_guide/comparing_nilm_algorithms.ipynb, with little modifications to precise the type of power used for the disaggregation . Here is the full code :
```
from __future__ import print_function, division
import time
from matplotlib import rcParams
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings
from six import iteritems

warnings.filterwarnings('ignore')

from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import CombinatorialOptimisation, FHMM

path  = 'E:/2 - Analyse des conso DONNEES/H5_format'
train = DataSet(path+'/REFIT.h5')
test = DataSet(path+'/REFIT.h5')

building = 1
# REFIT temporal coverage : 	Oct 2013 - Jun 2015
train.set_window(end="2015-1-01")
test.set_window(start="2015-01-01", end="2015-06-01")

train_elec = train.buildings[building].elec
test_elec = test.buildings[building].elec

top_5_train_elec = train_elec.submeters().select_top_k(k=5)
print(top_5_train_elec)

-- > # Type of data to disaggregate
physical_quantity = 'power'
ac_type = 'active'

## Predict function to get ground truth gt and prediction pred on the test sample
--> def predict(clf, test_elec, sample_period, timezone, physical_quantity, ac_type):
    pred = {}
    gt = {}

-->    for i, chunk in enumerate(test_elec.mains().load(sample_period=sample_period, physical_quantity=physical_quantity, ac_type=ac_type)):
        print(chunk)
        chunk_drop_na = chunk.dropna()
        #print(chunk_drop_na)
        pred[i] = clf.disaggregate_chunk(chunk_drop_na)
        gt[i] = {}

        for meter in test_elec.submeters().meters:
            # Only use the meters that we trained on (this saves time!)
            gt[i][meter] = next(meter.load(sample_period=sample_period))
            #print(meter.load(sample_period=sample_period))
        gt[i] = pd.DataFrame({k: v.squeeze() for k, v in iteritems(gt[i])},
                             index=next(iter(gt[i].values())).index).dropna()

    # If everything can fit in memory
    gt_overall = pd.concat(gt)
    gt_overall.index = gt_overall.index.droplevel()
    pred_overall = pd.concat(pred)
    pred_overall.index = pred_overall.index.droplevel()

    # Having the same order of columns
    gt_overall = gt_overall[pred_overall.columns]

    # Intersection of index
    gt_index_utc = gt_overall.index.tz_convert("UTC")
    pred_index_utc = pred_overall.index.tz_convert("UTC")
    common_index_utc = gt_index_utc.intersection(pred_index_utc)

    common_index_local = common_index_utc.tz_convert(timezone)
    gt_overall = gt_overall.ix[common_index_local]
    pred_overall = pred_overall.ix[common_index_local]
    appliance_labels = [m.label() for m in gt_overall.columns.values]
    gt_overall.columns = appliance_labels
    pred_overall.columns = appliance_labels
    return gt_overall, pred_overall


classifiers = {'CO':CombinatorialOptimisation(), 'FHMM':FHMM()}
# classifiers = {'FHMM':FHMM()}
predictions = {}
sp = 60 #sample time
for clf_name, clf in classifiers.items():
    print("*"*20)
    print(clf_name)
    print("*" *20)
-->    clf.train(top_5_train_elec, sample_period=sp, physical_quantity=physical_quantity, ac_type=ac_type)
-->    gt, predictions[clf_name] = predict(clf, test_elec, sp, train.metadata['timezone'])

```

**Comment by PMeira** [comment]
@EliseBcm No problem, thanks for providing more info. So far I found that there are repeated timestamps in the **original** REFIT dataset and that's what's causing that error. 

There is a newer version [here](https://pure.strath.ac.uk/portal/en/datasets/refit-electrical-load-measurements-cleaned\(9ab14b0e-19ac-4279-938f-27f643078cec\).html) that fixes this:

> This version of the dataset has been cleaned in the following ways:
> - Timestamp duplicates have been merged.
> (...)

I adapted the converter (on commit 00a0004) to handle the clean version as they also slightly changed the CSV layout. 

After adding the missing `physical_quantity` and `ac_type` to the last line of your sample, the code runs with the clean dataset. I didn't analyze the results though, so let me know if something else is still broken.

**Comment by PMeira** [comment]
> I'll reconvert and retest when I have some more time.

@walidsliti I just did it with a clean conversion, no issues again, so there must be some other detail we're missing. Are you using the recommended environment? Same error now as before?
