### ISSUE TITLE
Duplicate Indexes in UKDALE

### ISSUE THREAD

**Issue by OdysseasKr** [nilmtk/nilmtk#681]
I am not sure if this is considered an issue with the Dataset or with the toolkit. I just wanted to mention that loading data to memory fails when there are duplicate indexes in the Dataset.

An example using UKDALE:
```python
from nilmtk import DataSet
ds = DataSet('../../Datasets/ukdale.h5')
ds.set_window(start="13-4-2013", end="1-1-2014")
mains = ds.buildings[1].elec.mains()
series_generator = mains.power_series(sample_period=6)
next(series_generator)
```
results in the following error:
```bash
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    next(series_generator)
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/electric.py", line 629, in load_series
    for chunk in generator:
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/preprocessing/apply.py", line 15, in process
    new_chunk = self.func(chunk)
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/electric.py", line 145, in resample_func
    return safe_resample(df, **resample_kwargs)
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/utils.py", line 424, in safe_resample
    data = _resample_chain(data, resample_kwargs)
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/utils.py", line 420, in _resample_chain
    return how(fill_method(data.resample(rule, **resample_kwargs)))
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/utils.py", line 407, in <lambda>
    fill_method = lambda df: getattr(df, fill_method_str)()
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/resample.py", line 471, in pad
    return self._upsample('pad', limit=limit)
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/resample.py", line 820, in _upsample
    limit=limit, fill_value=fill_value)
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/pandas/util/_decorators.py", line 127, in wrapper
    return func(*args, **kwargs)
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/frame.py", line 2935, in reindex
    return super(DataFrame, self).reindex(**kwargs)
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/generic.py", line 3023, in reindex
    fill_value, copy).__finalize__(self)
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/frame.py", line 2870, in _reindex_axes
    fill_value, limit, tolerance)
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/frame.py", line 2878, in _reindex_index
    tolerance=tolerance)
  File "/home/odysseas/anaconda2/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2993, in reindex
    raise ValueError("cannot reindex a non-unique index "
ValueError: cannot reindex a non-unique index with a method or limit
Closing remaining open files:../../Datasets/ukdale.h5...done
```

Am I the only one that gets this error?
I have been able to fix this by modifying the __safe_resample__ function in utils.py but I am not sure whether I should make a pull request.

**Comment by nipunbatra** [comment]
All other things aside, I think this issue is a perfect example of how to write a *good* issue:

1. Meaningful title
2. Searchable issue (not image screenshots)
3. Minimal code to invoke the bug
4. Some analysis into the bug and finding the cause/remedy

Thanks @OdysseasKr Please keep reporting such bugs :)

I personally feel that this issue should be handled in both the converter and the toolkit. Each converter should check for such duplicate index. Further, NILMTK code should also have such sanity checks. 

Pinging @PMeira regarding the possibility of a pull request. I think this could also go into v0.3 which seems to be shaping very nicely.

**Comment by PMeira** [comment]
There are a couple more open issues with the UKDALE dataset (recent: #640, #658).

A couple of days ago (00a0004), I updated the REFIT importer to a new version of that dataset as the authors removed duplicated timestamps, so I didn't need to add handling duplicate timestamps on the occasion.

> Am I the only one that gets this error?

@OdysseasKr I can reproduce it, thanks for reporting.

Most of issues like this are technically errors in the datasets and only show up now because the default behavior in Pandas has changed.

> I personally feel that this issue should be handled in both the converter and the toolkit. Each converter should check for such duplicate index. Further, NILMTK code should also have such sanity checks.

@nipunbatra Agreed. If the sanity checks are too expensive, we could also add a flag to disable them, either in the methods or globally for the toolkit.

We need to rethink the whole resampling chain someday, but maybe it's best to leave that to v0.4. For v0.3, reproducing the behavior of older Pandas should be enough and would allow using existing (already converted) datasets without issues. 

The converters can be revisited to at least warn about the presence of duplicated timestamps now (v0.3) and maybe default to raising exceptions later (v0.4). I'll open a meta-ticket to track the state of each converter more easily.

> regarding the possibility of a pull request.

Of course a PR would be welcome -- even if doesn't address everything, it could be a good starting point. I can run some tests and investigate how Pandas changed next week (the [release notes](https://pandas.pydata.org/pandas-docs/stable/release.html) list a lot of changes regarding duplicated items).

**Comment by OdysseasKr** [comment]
Thank you for your quick response everybody. :smiley: 

I have submitted a relevant PR.

**Comment by OdysseasKr** [comment]
@PMeira I can confirm that this tweak works fine.

I can also confirm that I didn't encounter this issue using Pandas 0.17. Thank you for the quick response everybody! :smiley:

**Comment by PMeira** [comment]
@nipunbatra @OdysseasKr Almost a year later, I'm pretty convinced that the dataset should not contain duplicated timestamps and the converter should handle them if there are any. Some converters do already handle this and any reasonable database engine expects the same. Also, the less we have to worry about the integrity of the data after it is converted, the better, since it would simplify future changes such as implementing a different DataStore or even switching from Pandas to something else.

I'll start a simple (dataset) validation function to check some overall things like this and update the corresponding converters, such as UKDALE.

**Comment by PMeira** [comment]
Look at that... Pandas 0.24 restored the original behavior, it doesn't fail to resample data with duplicate index values nor raises any warning. Still, committing the updated converter that drops the duplicates now. The different is only 71 kB (out of around 6.2GB), so not much duplicated data.
