### ISSUE TITLE
UnicodeDecodeError when i try to convert_redd('low_freq', 'redd.h5')

### ISSUE THREAD

**Issue by professor-who** [nilmtk/nilmtk#689]
runfile('F:/nilm/nilmtk-master/nilmtk-master/untitled1.py', wdir='F:/nilm/nilmtk-master/nilmtk-master')
Loaded metadata
Traceback (most recent call last):

  File "<ipython-input-1-cb5204755998>", line 1, in <module>
    runfile('F:/nilm/nilmtk-master/nilmtk-master/untitled1.py', wdir='F:/nilm/nilmtk-master/nilmtk-master')

  File "E:\anaconda\envs\nilmtk\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "E:\anaconda\envs\nilmtk\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/nilm/nilmtk-master/nilmtk-master/untitled1.py", line 9, in <module>
    convert_redd('low_freq', 'redd.h5')

  File "F:\nilm\nilmtk-master\nilmtk-master\nilmtk\dataset_converters\redd\convert_redd.py", line 57, in convert_redd
    store)

  File "E:\anaconda\envs\nilmtk\lib\site-packages\nilm_metadata\convert_yaml_to_hdf5.py", line 79, in save_yaml_to_datastore
    meter_devices = _load_file(yaml_dir, 'meter_devices.yaml')

  File "E:\anaconda\envs\nilmtk\lib\site-packages\nilm_metadata\convert_yaml_to_hdf5.py", line 106, in _load_file
    return yaml.load(fh)

  File "E:\anaconda\envs\nilmtk\lib\site-packages\yaml\__init__.py", line 70, in load
    loader = Loader(stream)

  File "E:\anaconda\envs\nilmtk\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)

  File "E:\anaconda\envs\nilmtk\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()

  File "E:\anaconda\envs\nilmtk\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()

  File "E:\anaconda\envs\nilmtk\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)

UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 1561: illegal multibyte sequence

**Comment by nipunbatra** [comment]
Did you google the Unicode decode error?

**Comment by 272797900** [comment]
![image](https://user-images.githubusercontent.com/33648707/44000430-2a70d1ae-9e52-11e8-8f43-7b502b7a71be.png)
![image](https://user-images.githubusercontent.com/33648707/44000432-320a54c6-9e52-11e8-810c-a87953ede06b.png)
Professor, I have the same problem. I don't understand the solution you gave. I hope you can help me. Thank you.

**Comment by PMeira** [comment]
Since this keeps popping up, I'll try to send a PR to nilm_metadata to avoid using the default local encoding for the YAMLs. I'll try to do that in one or two days max.

**Comment by PMeira** [comment]
Forgot this: see https://github.com/nilmtk/nilmtk/issues/670#issuecomment-390661487 for more context and a potential workaround while we work on a permanent fix.

**Comment by 272797900** [comment]
Thank you very much for your reply，I changed it according to #670 https://github.com/nilmtk/nilmtk/issues/670#issuecomment-390661487，I succeeded

**Comment by PMeira** [comment]
This should be addressed as soon as https://github.com/nilmtk/nilm_metadata/pull/34 is merged. Please reopen if something similar still happens after that. 

If someone wants to test it before the fix/merge in the official repo, you can try cloning https://github.com/pmeira/nilm_metadata and installing from there.
