### ISSUE TITLE
Proportion_of_energy_submetered() with ECO dataset

### ISSUE THREAD

**Issue by nekovolta** [nilmtk/nilmtk#770]
When I use the instrucction:

 ```python
elec.proportion_of_energy_submetered()
 ```
 I get the next error:

 ```python
elec.proportion_of_energy_submetered()
Running MeterGroup.proportion_of_energy_submetered...
Traceback (most recent call last):

  File "<ipython-input-77-3cbee878059b>", line 1, in <module>
    elec.proportion_of_energy_submetered()

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.py", line 1065, in proportion_of_energy_submetered
    downstream_meters = self.meters_directly_downstream_of_mains()

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.py", line 813, in meters_directly_downstream_of_mains
    meters = list(nodes_adjacent_to_root(self.wiring_graph()))

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\utils.py", line 92, in nodes_adjacent_to_root
    root = tree_root(graph)

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\utils.py", line 85, in tree_root
    raise RuntimeError('Tree has more than one root!')

RuntimeError: Tree has more than one root!
 ```

The same happens with the instrucction

```python
elec.meters_directly_downstream_of_mains()
````

What is weird is that both instructions worked perfectly when I run the same example but with the REDD dataset. Then I did not have any error.

The code I am running is based on this example but as I mentioned with the ECO dataset:
[https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/elecmeter_and_metergroup.ipynb](url)

I send the piece of code until that line:

```python
import numpy as np
from matplotlib.sankey import Sankey
from matplotlib import rcParams
import matplotlib.pyplot as plt

rcParams['figure.figsize'] = (13, 6)
plt.style.use('ggplot')
import nilmtk
from nilmtk import DataSet

eco = DataSet('/ECO/eco.h5')
elec = eco.buildings[1].elec
elec

elec.nested_metergroups()
elec.mains().power_series_all_data().head()

# calculate energy submetered in building 1 in ECO dataset
elec.proportion_of_energy_submetered()
```

**Comment by nipunbatra** [comment]
Assigned to @ayushp20

**Comment by ayushp20** [comment]
Since it shows the tree to have more than one root, I decided to plot the wiring diagram for the dataset to see what sort of a graph is being passed on to the function. 
```python
elec.draw_wiring_graph()
```
The graph looks like this - 
![Screenshot from 2019-05-30 22-14-41](https://user-images.githubusercontent.com/36565028/58648933-620d8980-82fa-11e9-8f0d-0eb2319d836d.png)
So we can observe that the wiring graph of this data does have more than one root and the function will fail here. 
Could you tell me which building does your '*eco.h5*' consists of? I tested this on Building 1. I'll try testing on other buildings to see whether this is a problem of the building or the ECO dataset itself.

**Comment by nekovolta** [comment]
Thank you for your reply. I did the same experiment that you mentioned, that is testing just on building 1. I did not try with other building. Did you manage to check if it works with other buildings?

**Comment by ayushp20** [comment]
Yes, I did. All buildings in ECO dataset have more than 1 site meters. 
A graph with more than one root cannot be used as ultimately in the networkx diagraph class we require a connected graph.
The proportion of energy submetered can still be calculated by editing the building metadata itself. If we simply label all of them as "submeter of: 0", we can work around this and still get the desired output. 
I'll see if its possible to keep the changes to the metadata as it reflects the ECO dataset and shouldn't be for NILMTK to handle.

**Comment by PMeira** [comment]
Related: #169, #659 (working on this last one soon)

**Comment by Mohamadnet** [comment]
I am having the same problem
Any progress?
