### ISSUE TITLE
Unable to run all appliances in REDD dataset 

### ISSUE THREAD

**Issue by nekovolta** [nilmtk/nilmtk#792]
Following the example of disaggregation with REDD dataset:

[https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb](url)

As it is indicated in that notebook, the training is made selecting the top-5 appliances:

```python
top_5_train_elec = train_elec.submeters().select_top_k(k=5)
```

I am trying to perform the training phase over **all appliances**, this way:

```python
train_elec = train.buildings[1].elec

from nilmtk.disaggregate import fhmm_exact
fhmm = fhmm_exact.FHMM()
fhmm.train(train_elec, sample_period=sample_period)
```

But when I perform the testing, it stuck there, and it does not make any test at all. This code run the test phase:

```python
pred = {}
gt= {}

for i, chunk in enumerate(test_elec.mains().load(sample_period=sample_period)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    
    for meter in test_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)    
        gt[i][meter] = next(meter.load(sample_period=sample_period))
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i])}, index=next(iter(gt[i].values())).index).dropna()
```

Why is this happening? With ECO dataset I managed to replicate the notebook using all the appliances, as commented by @ayushp20 in #775, but with REDD does not work, it sticks here forever:

![image](https://user-images.githubusercontent.com/29656053/59254308-3a8abb00-8c30-11e9-82ec-ad90d33a8936.png)

**Comment by nekovolta** [comment]
I just realized that the notebook to try the disaggregation feature was updated a few days ago. However, still the same issue.

**Comment by nekovolta** [comment]
This is the code I am using to run all appliances:

```python
def predict(clf, test_elec, sample_period, timezone):
    pred = {}
    gt= {}
    
    # "ac_type" varies according to the dataset used. 
    # Make sure to use the correct ac_type before using the default parameters in this code.    
    for i, chunk in enumerate(test_elec.mains().load(physical_quantity = 'power', ac_type = 'apparent', sample_period=sample_period)):
        chunk_drop_na = chunk.dropna()
        pred[i] = clf.disaggregate_chunk(chunk_drop_na)
        gt[i]={}

        for meter in test_elec.submeters().meters:
            # Only use the meters that we trained on (this saves time!)    
            gt[i][meter] = next(meter.load(physical_quantity = 'power', ac_type = 'active', sample_period=sample_period))
        gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i]) if len(v)}, index=next(iter(gt[i].values())).index).dropna()
        
    # If everything can fit in memory
    gt_overall = pd.concat(gt)
    gt_overall.index = gt_overall.index.droplevel()
    pred_overall = pd.concat(pred)
    pred_overall.index = pred_overall.index.droplevel()

    # Having the same order of columns
    gt_overall = gt_overall[pred_overall.columns]
    
    #Intersection of index
    gt_index_utc = gt_overall.index.tz_convert("UTC")
    pred_index_utc = pred_overall.index.tz_convert("UTC")
    common_index_utc = gt_index_utc.intersection(pred_index_utc)
    
    common_index_local = common_index_utc.tz_convert(timezone)
    gt_overall = gt_overall.ix[common_index_local]
    pred_overall = pred_overall.ix[common_index_local]
    appliance_labels = [m for m in gt_overall.columns.values]
    gt_overall.columns = appliance_labels
    pred_overall.columns = appliance_labels
    return gt_overall, pred_overall

# Train using 2 benchmarking algorithms - Combinatorial Optimisation (CO) and Factorial Hidden Markov Model (FHMM)
classifiers = {'CO':CombinatorialOptimisation(), 'FHMM':FHMM()}
predictions = {}
sample_period = 120
for clf_name, clf in classifiers.items():
    print("*"*20)
    print(clf_name)
    print("*" *20)
    start = time.time()

    #clf.train(top_5_train_elec, sample_period=sample_period)
    clf.train(train_elec, sample_period=sample_period)
    end = time.time()
    print("Runtime =", end-start, "seconds.")
    gt, predictions[clf_name] = predict(clf, test_elec, sample_period, train.metadata['timezone'])
```

When I try with the training for all appliances, the code does not work. Why? Can anyone help?

**Comment by ayushp20** [comment]
After some fiddling around with the parameters, I discovered that training a large amount of data on FHMM uses up a lot of memory. At sample_period=60 the memory fills up while disaggregating, whereas at sample_period=1 the model cannot even be trained completely.
```python
classifiers = {'FHMM':FHMM()}
predictions = {}
sample_period = 1
for clf_name, clf in classifiers.items():
    print("*"*20)
    print(clf_name)
    print("*" *20)
    start = time.time()
    # fhmm.train(train_elec, sample_period=60)
    clf.train(train_elec, sample_period=sample_period)
    end = time.time()
    print("Runtime =", end-start, "seconds.")
    gt, predictions[clf_name] = predict(clf, test_elec, sample_period, train.metadata['timezone'])
```
```python
********************
FHMM
********************
Training model for submeter 'ElecMeter(instance=5, building=1, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Training model for submeter 'ElecMeter(instance=6, building=1, dataset='REDD', appliances=[Appliance(type='dish washer', instance=1)])'
Training model for submeter 'ElecMeter(instance=7, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=1)])'
Training model for submeter 'ElecMeter(instance=8, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=2)])'
Training model for submeter 'ElecMeter(instance=9, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=1)])'
Training model for submeter 'ElecMeter(instance=11, building=1, dataset='REDD', appliances=[Appliance(type='microwave', instance=1)])'
Training model for submeter 'ElecMeter(instance=12, building=1, dataset='REDD', appliances=[Appliance(type='unknown', instance=1)])'
Training model for submeter 'ElecMeter(instance=13, building=1, dataset='REDD', appliances=[Appliance(type='electric space heater', instance=1)])'
Training model for submeter 'ElecMeter(instance=14, building=1, dataset='REDD', appliances=[Appliance(type='electric stove', instance=1)])'
Training model for submeter 'ElecMeter(instance=15, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=3)])'
Training model for submeter 'ElecMeter(instance=16, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=4)])'
Training model for submeter 'ElecMeter(instance=17, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=2)])'
Training model for submeter 'ElecMeter(instance=18, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=3)])'
Training model for submeter 'ElecMeter(instance=19, building=1, dataset='REDD', appliances=[Appliance(type='unknown', instance=2)])'
Loading data for meter ElecMeterID(instance=4, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Training model for submeter 'MeterGroup(meters=
  ElecMeter(instance=3, building=1, dataset='REDD', appliances=[Appliance(type='electric oven', instance=1)])
  ElecMeter(instance=4, building=1, dataset='REDD', appliances=[Appliance(type='electric oven', instance=1)])
)'
Loading data for meter ElecMeterID(instance=20, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Training model for submeter 'MeterGroup(meters=
  ElecMeter(instance=10, building=1, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])
  ElecMeter(instance=20, building=1, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])
)'
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-25-4ec92ac792e0> in <module>
      8     start = time.time()
      9     # fhmm.train(train_elec, sample_period=60)
---> 10     clf.train(train_elec, sample_period=sample_period)
     11     end = time.time()
     12     print("Runtime =", end-start, "seconds.")

~/anaconda3/envs/n2/lib/python3.6/site-packages/nilmtk/disaggregate/fhmm_exact.py in train(self, metergroup, num_states_dict, **load_kwargs)
    322             self.meters.append(meter)
    323 
--> 324         learnt_model_combined = create_combined_hmm(new_learnt_models)
    325         self.individual = new_learnt_models
    326         self.model = learnt_model_combined

~/anaconda3/envs/n2/lib/python3.6/site-packages/nilmtk/disaggregate/fhmm_exact.py in create_combined_hmm(model)
    125 
    126     pi_combined = compute_pi_fhmm(list_pi)
--> 127     A_combined = compute_A_fhmm(list_A)
    128     [mean_combined, cov_combined] = compute_means_fhmm(list_means)
    129 

~/anaconda3/envs/n2/lib/python3.6/site-packages/nilmtk/disaggregate/fhmm_exact.py in compute_A_fhmm(list_A)
     84     result = list_A[0]
     85     for i in range(len(list_A) - 1):
---> 86         result = np.kron(result, list_A[i + 1])
     87     return result
     88 

~/anaconda3/envs/n2/lib/python3.6/site-packages/numpy/lib/shape_base.py in kron(a, b)
   1135             bs = (1,)*(nda-ndb) + bs
   1136             nd = nda
-> 1137     result = outer(a, b).reshape(as_+bs)
   1138     axis = nd-1
   1139     for _ in range(nd):

~/anaconda3/envs/n2/lib/python3.6/site-packages/numpy/core/numeric.py in outer(a, b, out)
   1201     a = asarray(a)
   1202     b = asarray(b)
-> 1203     return multiply(a.ravel()[:, newaxis], b.ravel()[newaxis, :], out)
   1204 
   1205 

MemoryError:
```
 So training on all appliances with FHMM works at a relatively higher sample rate, like sample_period=600, or training on less number of appliances, like top 5. Try a higher sampling rate for training on FHMM on all appliances.

**Comment by PMeira** [comment]
FHMM scales the matrix size exponentially with the number of appliances and states, so it just won't work or will be extremely slow due to the huge size of the (dense) state transition matrix.

Let's keep this open until we add a warning before trying to run with large numbers of appliances.

**Comment by nekovolta** [comment]
@PMeira could be a possible solution for this to train one appliance at a time? If you want to disaggregate all appliances to run the code as many times as the number of appliances you are interested in disaggregated.

**Comment by nekovolta** [comment]
By the way, I tried to run REDD with just **one appliance**.  I used this code:

```python
classifiers = {'CO':CombinatorialOptimisation(), 'FHMM':FHMM()}
predictions = {}
sample_period = 120
for clf_name, clf in classifiers.items():
    print("*"*20)
    print(clf_name)
    print("*" *20)
    start = time.time()
    clf.train(fridge_meter, sample_period=sample_period)
    end = time.time()
    print("Runtime =", end-start, "seconds.")
    gt, predictions[clf_name] = predict(clf, test_elec, sample_period, train.metadata['timezone'])
```

Where **fridge_meter** is:

`fridge_meter = train_elec['fridge']`

When I run this, I get this error:

```python
Traceback (most recent call last):

  File "<ipython-input-15-118e49d6c356>", line 14, in <module>
    clf.train(fridge_meter, sample_period=sample_period)

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\disaggregate\combinatorial_optimisation.py", line 70, in train
    num_meters = len(metergroup.meters)

AttributeError: 'ElecMeter' object has no attribute 'meters'
```

I guess the error is related to the fact that **fridge_meter** is not a **MeterGroup**. For instance, when it is used the **top_5_train_elec** :

`top_5_train_elec = train_elec.submeters().select_top_k(k=5)`

```python
top_5_train_elec = 

MeterGroup(meters=
  ElecMeter(instance=11, building=1, dataset='REDD', appliances=[Appliance(type='microwave', instance=1)])
  ElecMeter(instance=9, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=1)])
  ElecMeter(instance=5, building=1, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])
  ElecMeter(instance=8, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=2)])
  ElecMeter(instance=6, building=1, dataset='REDD', appliances=[Appliance(type='dish washer', instance=1)]) 
```

On the other hand, **fridge_meter** is an **ElecMeter**

```python
fridge_meter =

ElecMeter(instance=5, building=1, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])
```

Could it be this the error? How can I do if I just one to train one appliance to avoid overloading the computer?

**Comment by rajatgupta1234** [comment]
@nekovolta  Yes, `clf.train()` expects a metergroup object not an elecmeter object.
![1](https://user-images.githubusercontent.com/46721220/59768741-7f62c180-92c2-11e9-9e19-f78d07d15daa.PNG)

You can use this code.

**Comment by nekovolta** [comment]
@rajatgupta1234 

I did it that way because it just so happens that the fridge is the top 1 device in power consumption. But how would you select only one device that it is not the one with the highest power consumption?

**Comment by ayushp20** [comment]
You can select any appliance using:
```python
train_elec.select_using_appliances(type='hair dryer')
```
```MeterGroup(meters=
  ElecMeter(instance=5, building=1, dataset='ECO', appliances=[Appliance(type='hair dryer', instance=1)])
)
```

**Comment by PMeira** [comment]
> @PMeira could be a possible solution for this to train one appliance at a time? If you want to disaggregate all appliances to run the code as many times as the number of appliances you are interested in disaggregated.

This method already trains each appliance one at a time and then combines the data into the large model. You can see from your initial traceback that it is failing in this step (`create_combined_hmm()`). This large model is the issue here, as its dimensions depend on the total number of appliances and states, using a dense matrix.

**Comment by nekovolta** [comment]
@ayushp20 

> You can select any appliance using:
> 
> ```python
> train_elec.select_using_appliances(type='hair dryer')
> ```
> 
> It returns a MeterGroup object:
> 
> ```python
> MeterGroup(meters=
>   ElecMeter(instance=5, building=1, dataset='ECO', appliances=[Appliance(type='hair dryer', instance=1)])
> )
> ```

What if you want to select two appliances, for instance, the hair dryer and the fridge? I tried with these combinations but it does not work:

```python
train_elec.select_using_appliances(type='hair dryer', type='fridge')
train_elec.select_using_appliances(type='hair dryer', 'fridge')
train_elec.select_using_appliances(type='hair dryer, fridge')
```

**Comment by ayushp20** [comment]
It's really simple all you have to do is pass a list.
```python
train_elec.select_using_appliances(type=['hair dryer', 'fridge'])
```

**Comment by nekovolta** [comment]
@ayushp20 it is when you know it :) Thank you very much!

**Comment by beautifwhale** [comment]
Just to add you'll hit the `AttributeError: 'ElecMeter' object has no attribute 'meters'` error even if you choose for example 

```
train_elec.select_using_appliances(type=['electric oven'])
```
Because it seems to be nested, `MeterGroup` with two instances inside the root `MeterGroup`.
