### ISSUE TITLE
Issue while converting SMART*

### ISSUE THREAD

**Issue by klemenjak** [nilmtk/nilmtk#870]
Hello,

I was having some issues with the SMART* dataset converter. I'm using the latest version of NILMTK that I got from conda forge + the [SMART 2013 version](http://traces.cs.umass.edu/index.php/Smart/Smart) I downloaded from their website:

![image](https://user-images.githubusercontent.com/35270419/80276552-e5da1c80-86e9-11ea-9e35-1a43544ef7fa.png)

When I run the converter:

```python
from nilmtk.dataset_converters import convert_smart
convert_smart('/Users/christoph/thesis-dev/data/smart', 'smart-test.h5')
```

it gives me:

```python
Loading Home: A... Traceback (most recent call last):
  File "/Users/christoph/anaconda/envs/thesis/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Date & Time'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/christoph/anaconda/envs/thesis/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-36-fb48161daf63>", line 1, in <module>
    convert_smart('/Users/christoph/thesis-dev/data/smart', 'smart-test.h5')
  File "/Users/christoph/anaconda/envs/thesis/lib/python3.6/site-packages/nilmtk/dataset_converters/smart/convert_smart.py", line 46, in convert_smart
    _convert(smart_path, store, _smart_measurement_mapping_func, 'US/Eastern')
  File "/Users/christoph/anaconda/envs/thesis/lib/python3.6/site-packages/nilmtk/dataset_converters/smart/convert_smart.py", line 138, in _convert
    df_all_years['Date & Time'], utc=True)
  File "/Users/christoph/anaconda/envs/thesis/lib/python3.6/site-packages/pandas/core/frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/christoph/anaconda/envs/thesis/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Date & Time'
```

Have you had such issues before?

best,
C

**Comment by PMeira** [comment]
@klemenjak Pretty sure the current converter is for the 2017 release from the metadata:

https://github.com/nilmtk/nilmtk/blob/4e38fd5fbf43b43d82c81deeb11fa4a5564e1ac9/nilmtk/dataset_converters/smart/metadata/dataset.yaml#L3-L5

It's a good idea to add a converter for the 2013 release though, as well as document more explicitly the versions/releases handled by each dataset and the current expected URLs.
