### ISSUE TITLE
GREEND converter

### ISSUE THREAD

**Issue by klemenjak** [nilmtk/nilmtk#874]
Hi,

I tried to convert the [GREEND Dataset](https://sourceforge.net/projects/greend/files/GREEND_0-2_300615.zip/download) using *convert_greend*.

```
meter 1: 000D6F00029C2542
Putting into store...
meter 2: 000D6F00036BC42A
Putting into store...
meter 3: 000D6F0003BD8082
Putting into store...
meter 4: 000D6F0003BD8C8E
Putting into store...
meter 5: 000D6F0003BD76C4
Putting into store...
meter 6: 000D6F0003BD8103
Putting into store...
meter 7: 000D6F0003BD8293
Putting into store...
meter 8: 000D6F0003BD6E92
Putting into store...
meter 9: 000D6F0003B9C636
Putting into store...
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-7-a156af13ddce> in <module>
----> 1 convert_greend('/home/christoph/Downloads/GREEND_0-2_300615/GREEND_0-2_300615', '/home/christoph/Downloads/GREEND_0-2_300615/GREEND_0-2_300615/g.h5')

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/dataset_converters/greend/convert_greend.py in convert_greend(greend_path, hdf_filename, use_mp)
    175         # retrieve the dataset metadata in the metadata subfolder
    176     metadata_dir = join(get_module_directory(), 'dataset_converters', 'greend', 'metadata')
--> 177     convert_yaml_to_hdf5(metadata_dir, hdf_filename)
    178 
    179 #is only called when this file is the main file... only test purpose

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilm_metadata/convert_yaml_to_hdf5.py in convert_yaml_to_hdf5(yaml_dir, hdf_filename)
     30 
     31     assert isdir(yaml_dir)
---> 32     store = pd.HDFStore(hdf_filename, 'a')
     33 
     34     # Load Dataset and MeterDevice metadata

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/io/pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    503         self._fletcher32 = fletcher32
    504         self._filters = None
--> 505         self.open(mode=mode, **kwargs)
    506 
    507     def __fspath__(self):

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/io/pytables.py in open(self, mode, **kwargs)
    625 
    626         try:
--> 627             self._handle = tables.open_file(self._path, self._mode, **kwargs)
    628         except (IOError) as e:  # pragma: no cover
    629             if "can not be written" in str(e):

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/tables/file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
    313 
    314     # Finally, create the File instance, and return it
--> 315     return File(filename, mode, title, root_uep, filters, **kwargs)
    316 
    317 

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/tables/file.py in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
    776 
    777         # Now, it is time to initialize the File extension
--> 778         self._g_new(filename, mode, **params)
    779 
    780         # Check filters and set PyTables format version for new files.

tables/hdf5extension.pyx in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1567, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 959, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/home/christoph/Downloads/GREEND_0-2_300615/GREEND_0-2_300615/g.h5'

```

I guess there is some issue while converting the metadata in *convert_yaml_to_hdf5*. I'm still trying to fix the issue but wanted to have it noted here.

best,
C

**Comment by klemenjak** [comment]
Some more thoughts on this:

As the error indicated, the process isn't actually closing the HDF file (for whatever reasons). That could be the reason why the process is crashing in function *convert_yaml_to_hdf5*. 

So here's what I did to overcome this problem (dirty workaround):

1. Restart iPython
2. Convert YAML to HDF5 by hand:

```python
from os.path import join
from nilmtk.utils import get_module_directory
from nilm_metadata import convert_yaml_to_hdf5

hdf_filename = '/home/christoph/Downloads/GREEND_0-2_300615/GREEND_0-2_300615/greend.h5'
metadata_dir = join(get_module_directory(), 'dataset_converters', 'greend', 'metadata')

convert_yaml_to_hdf5(metadata_dir, hdf_filename)


```

It's not a beautiful fix but it gets the job done, as you can see:

```
In [1]: hdf_filename = '/home/christoph/Downloads/GREEND_0-2_300615/GREEND_0-2_300615/greend.h5'                                           

In [2]: from nilmtk import DataSet                                                                                                         

In [3]: greend = DataSet(hdf_filename)                                                                                                     

In [4]: greend.metadata                                                                                                                    
Out[4]: 
{'name': 'GREEND',
 'long_name': 'GREEND Electrical ENergy Dataset',
 'creators': ['Egarter, Dominik',
  'Elmenreich, Wilfried',
  'Monacchi, Andrea',
  'Pöchacker, Manfred'],
 'timezone': 'CET',
 'institution': 'Alpen-Adria-Universität',
 'number_of_buildings': 8,
 'geo_location': {'locality': 'Klagenfurt',
  'country': 'AT',
  'latitude': 46.61415,
  'longitude': 14.263321},
 'related_documents': ['http://arxiv.org/abs/1405.3100'],
 'schema': 'https://github.com/nilmtk/nilm_metadata/tree/v0.2',
 'meter_devices': {'circle': {'model': 'circle',
   'model_url': 'http://www.plugwise.com/product/circle',
   'manufacturer': 'Plugwise',
   'manufacturer_url': 'http://www.plugwise.com',
   'sample_period': 1,
   'max_sample_period': 30,
   'measurements': [{'physical_quantity': 'power',
     'type': 'active',
     'upper_limit': 3000,
     'lower_limit': 0}],
   'description': 'des',
   'pre_pay': False,
   'wireless': True,
   'wireless_configuration': {'base': 'Raspberry Pi',
    'protocol': 'zigbee',
    'carrier_frequency': 2400},
   'data_logger': 'log'}}}

```
