### ISSUE TITLE
AttributeError: module 'matplotlib.dates' has no attribute '_to_ordinalf'

### ISSUE THREAD

**Issue by yixinxu2020** [nilmtk/nilmtk#904]
Why when I try to test the package the error comes up?

**Comment by yixinxu2020** [comment]
python -c "import nilmtk"
-->
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/div/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/__init__.py", line 9, in <module>
    from nilmtk.elecmeter import ElecMeter
  File "/home/div/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/elecmeter.py", line 12, in <module>
    from .electric import Electric
  File "/home/div/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/electric.py", line 22, in <module>
    from .plots import plot_series
  File "/home/div/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/plots.py", line 7, in <module>
    _to_ordinalf_np_vectorized = np.vectorize(mdates._to_ordinalf)
AttributeError: module 'matplotlib.dates' has no attribute '_to_ordinalf'

**Comment by dungdao191299** [comment]
how can you troubleshoot it?
