### ISSUE TITLE
When I tried to run the REDD data set analysis code, the following error occurred. Could you help me analyze and solve it

### ISSUE THREAD

**Issue by 123456zxz** [nilmtk/nilmtk#927]
from __future__ import print_function, division
import time
from matplotlib import rcParams  
import matplotlib.pyplot as plt
import pandas as pd  
import numpy as np  
import warnings  

Traceback (most recent call last):
  File "F:/NILMTK1/ComOpt/do.py", line 20, in <module>
    train = DataSet('../low_freq/redd_low.h5')  
  File "F:\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\dataset.py", line 45, in __init__
    self.import_metadata(get_datastore(filename, format))
  File "F:\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\dataset.py", line 54, in import_metadata
AttributeError: Attribute 'metadata' does not exist in node: '/'
Closing remaining open files:C:\Users\ADMINI~1\AppData\Local\Temp\nilmtk-7agn1nq7.h5...done../low_freq/redd_low.h5...done

**Comment by hetvi0609** [comment]
@123456zxz Check whether you are creating redd_low.h5 file correctly or not.  Line 34-39 in convert_yaml_to_hdf5.py suggest it should contain metadata as an attribute.

```  
    #Load Dataset and MeterDevice metadata 
    metadata = _load_file(yaml_dir, 'dataset.yaml')
    meter_devices = _load_file(yaml_dir, 'meter_devices.yaml')
    metadata['meter_devices'] = meter_devices
    store.root._v_attrs.metadata = metadata
 ```

**Comment by drekisen** [comment]
Hola que tal, como se le dan los atributos de metadato?
