### ISSUE TITLE
I can't train on my data

### ISSUE THREAD

**Issue by Kraligan** [nilmtk/nilmtk#931]
Hi everyone,

I'm trying to use the nilmtk tool in order to test some disagregation algorithm on my datas.
For now, in order to test the toolkit, I did a little dataset with 4 .CSV: 
-1 csv with a signal that combine 3 equipments: 1 kettle, 1 heater and one laptop named "meter1.csv"
-3 csv with the samples of 1 equipment each in order to do the training (maybe it won't work well because I only have samples for 1-2hours but if I succed to use the toolkit I will add samples for few days) named "meter2/3/4.csv"

My problem for now is that I can't train on my datas. I wrote the yaml files, i generated the hdf5 file using the function :
nilm_metadata.convert_yaml_to_hdf5()

After that I store my datas in the hdf5 using the function: HDFStore : 
```store = pd.HDFStore(filename3)

df1 = pd.read_csv('metadata\\meter1.csv')
df2 = pd.read_csv('metadata\\meter2.csv')
df3 = pd.read_csv('metadata\\meter3.csv')
df4 = pd.read_csv('metadata\\meter4.csv')

store.append('building1/elec/meter1', df1)
store.append('building1/elec/meter2', df2)
store.append('building1/elec/meter3', df3)
store.append('building1/elec/meter4', df4)
```

If I try to print the datas it works : 
```
data1 = store['building1/elec/meter1']
data2 = store['building1/elec/meter2']
data3 = store['building1/elec/meter3']
data4 = store['building1/elec/meter4']
print(data1)
print(data2)
print(data3)
print(data4)
```
![image](https://user-images.githubusercontent.com/86051409/122394490-55f2d400-cf76-11eb-9ada-2b517a5c40d3.png)

But the I try to run the training and the disagregation by using the tutorial : https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/comparing_nilm_algorithms.ipynb 

And i got the error :
```
********************
FHMM
********************
Submeter 'ElecMeter(instance=2, building=1, dataset='ERL', appliances=[Appliance(type='electric heating element', instance=1)])' has no samples, skipping...
Submeter 'ElecMeter(instance=3, building=1, dataset='ERL', appliances=[Appliance(type='kettle', instance=1)])' has no samples, skipping...
Submeter 'ElecMeter(instance=4, building=1, dataset='ERL', appliances=[Appliance(type='laptop computer', instance=1)])' has no samples, skipping...
Traceback (most recent call last):
  File "C:/My Program Files/Git/nilmtk-env/test train et desa.py", line 113, in <module>
    clf.train(test, sample_period=sample_period)
  File "C:\My Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\legacy\disaggregate\fhmm_exact.py", line 364, in train
    learnt_model_combined = create_combined_hmm(new_learnt_models)
  File "C:\My Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\legacy\disaggregate\fhmm_exact.py", line 115, in create_combined_hmm
    pi_combined = compute_pi_fhmm(list_pi)
  File "C:\My Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\legacy\disaggregate\fhmm_exact.py", line 103, in compute_pi_fhmm
    result = list_pi[0]
IndexError: list index out of range
Closing remaining open files:test_ERL_m3.hdf5...doneC:\Users\fskv3470\AppData\Local\Temp\1\nilmtk-1azq1qiw.h5...donetest_ERL_m3.hdf5...done
```
Here is the entire code:

```
from nilmtk.api import API
import warnings
warnings.filterwarnings("ignore")
from nilmtk.disaggregate import CO
import nilm_metadata
import nilmtk
import numpy as np
import pandas as pd
#from __future__ import print_function, division
import time
from matplotlib import rcParams
import matplotlib.pyplot as plt
from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.legacy.disaggregate import CombinatorialOptimisation, FHMM
import nilmtk.utils
from six import iteritems
import datetime

nilm_metadata.convert_yaml_to_hdf5("C:\\My Program Files\\Git\\nilmtk-env\\metadata", "test_ERL_m3.hdf5")

filename3 = 'test_ERL_m3.hdf5'

store = pd.HDFStore(filename3)

df1 = pd.read_csv('metadata\\meter1.csv')
df2 = pd.read_csv('metadata\\meter2.csv')
df3 = pd.read_csv('metadata\\meter3.csv')
df4 = pd.read_csv('metadata\\meter4.csv')

store.append('building1/elec/meter1', df1)
store.append('building1/elec/meter2', df2)
store.append('building1/elec/meter3', df3)
store.append('building1/elec/meter4', df4)

data1 = store['building1/elec/meter1']
data2 = store['building1/elec/meter2']
data3 = store['building1/elec/meter3']
data4 = store['building1/elec/meter4']
print(data1)
print(data2)
print(data3)
print(data4)
store.close()
train = DataSet(filename3)
test = DataSet(filename3)
building = 1

train.set_window("2021-03-01 00:00:00", "2021-03-31 00:00:00")
test.set_window("2021-03-01 00:00:00", "2021-03-31 00:00:00")

train_elec = train.buildings[1].elec
test_elec = test.buildings[1].elec

#top_5_train_elec = train_elec.submeters()
test = train_elec.select_using_appliances(type=['electric heating element','kettle', 'laptop computer'])
print(test)

def predict(clf, test_elec, sample_period, timezone):
    pred = {}
    gt = {}

    for i, chunk in enumerate(test_elec.mains().load(physical_quantity = 'power', ac_type = 'apparent', sample_period=sample_period)):
        chunk_drop_na = chunk.dropna()
        pred[i] = clf.disaggregate_chunk(chunk_drop_na)
        gt[i] = {}

        for meter in test_elec.submeters().meters:
            # Only use the meters that we trained on (this saves time!)
            gt[i][meter] = next(meter.load(physical_quantity = 'power', ac_type = 'apparent', sample_period=sample_period))
        gt[i] = pd.DataFrame({k: v.squeeze() for k, v in iteritems(gt[i]) if len(v)},
                             index=next(iter(gt[i].values())).index).dropna()

    # If everything can fit in memory
    gt_overall = pd.concat(gt)
    gt_overall.index = gt_overall.index.droplevel()
    pred_overall = pd.concat(pred)
    pred_overall.index = pred_overall.index.droplevel()

    # Having the same order of columns
    gt_overall = gt_overall[pred_overall.columns]

    # Intersection of index
    gt_index_utc = gt_overall.index.tz_convert("UTC")
    pred_index_utc = pred_overall.index.tz_convert("UTC")
    common_index_utc = gt_index_utc.intersection(pred_index_utc)

    common_index_local = common_index_utc.tz_convert(timezone)
    gt_overall = gt_overall.loc[common_index_local]
    pred_overall = pred_overall.loc[common_index_local]
    appliance_labels = [m for m in gt_overall.columns.values]
    gt_overall.columns = appliance_labels
    pred_overall.columns = appliance_labels
    return gt_overall, pred_overall

classifiers = {'FHMM':FHMM(), 'CO':CombinatorialOptimisation() }
predictions = {}
sample_period = 2
for clf_name, clf in classifiers.items():
    print("*"*20)
    print(clf_name)
    print("*" *20)
    clf.train(test, sample_period=sample_period)
    gt, predictions[clf_name] = predict(clf, test_elec, sample_period, train.metadata['timezone'])
```

And my .CSV looks like : 
![image](https://user-images.githubusercontent.com/86051409/122395045-e4675580-cf76-11eb-836e-8a16bebad89f.png)

If someone have the solution I take it.
Thanks for your time.

**Comment by drekisen** [comment]
Hola que tal, disculpa lo solucionaste?
